/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.resources.trust;

import com.marketsdk.core.ClientOptions;
import com.marketsdk.core.MarketSDKHttpResponse;
import com.marketsdk.core.RequestOptions;
import com.marketsdk.resources.trust.requests.AddEvidenceDto;
import com.marketsdk.resources.trust.requests.CancelVerificationRequest;
import com.marketsdk.resources.trust.requests.CloseDisputeEvidenceRequest;
import com.marketsdk.resources.trust.requests.CreateVerificationDto;
import com.marketsdk.resources.trust.requests.DecideDisputeDto;
import com.marketsdk.resources.trust.requests.GetDisputeRequest;
import com.marketsdk.resources.trust.requests.GetVerificationRequest;
import com.marketsdk.resources.trust.requests.ListDisputeEvidenceRequest;
import com.marketsdk.resources.trust.requests.ListDisputesRequest;
import com.marketsdk.resources.trust.requests.ListVerificationsRequest;
import com.marketsdk.resources.trust.requests.OpenDisputeDto;
import com.marketsdk.types.DisputeEvidenceList;
import com.marketsdk.types.DisputeEvidenceObject;
import com.marketsdk.types.DisputeList;
import com.marketsdk.types.DisputeObject;
import com.marketsdk.types.VerificationList;
import com.marketsdk.types.VerificationObject;
import java.util.concurrent.CompletableFuture;

public class AsyncTrustClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawTrustClient rawClient;

    public AsyncTrustClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawTrustClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawTrustClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Creates a Stripe Identity session on your Stripe account and returns its page, once. Only the outcome and the session id are kept; no document image or document data. When seller verification is on, a seller can publish only once verified.
     */
    public CompletableFuture<VerificationObject> createVerification(String id) {
        CompletableFuture<MarketSDKHttpResponse<VerificationObject>> rawFuture = this.rawClient.createVerification(id);
        CompletableFuture<VerificationObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Creates a Stripe Identity session on your Stripe account and returns its page, once. Only the outcome and the session id are kept; no document image or document data. When seller verification is on, a seller can publish only once verified.
     */
    public CompletableFuture<VerificationObject> createVerification(String id, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<VerificationObject>> rawFuture =
                this.rawClient.createVerification(id, requestOptions);
        CompletableFuture<VerificationObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Creates a Stripe Identity session on your Stripe account and returns its page, once. Only the outcome and the session id are kept; no document image or document data. When seller verification is on, a seller can publish only once verified.
     */
    public CompletableFuture<VerificationObject> createVerification(String id, CreateVerificationDto request) {
        CompletableFuture<MarketSDKHttpResponse<VerificationObject>> rawFuture =
                this.rawClient.createVerification(id, request);
        CompletableFuture<VerificationObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Creates a Stripe Identity session on your Stripe account and returns its page, once. Only the outcome and the session id are kept; no document image or document data. When seller verification is on, a seller can publish only once verified.
     */
    public CompletableFuture<VerificationObject> createVerification(
            String id, CreateVerificationDto request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<VerificationObject>> rawFuture =
                this.rawClient.createVerification(id, request, requestOptions);
        CompletableFuture<VerificationObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<VerificationList> listVerifications() {
        CompletableFuture<MarketSDKHttpResponse<VerificationList>> rawFuture = this.rawClient.listVerifications();
        CompletableFuture<VerificationList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<VerificationList> listVerifications(RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<VerificationList>> rawFuture =
                this.rawClient.listVerifications(requestOptions);
        CompletableFuture<VerificationList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<VerificationList> listVerifications(ListVerificationsRequest request) {
        CompletableFuture<MarketSDKHttpResponse<VerificationList>> rawFuture =
                this.rawClient.listVerifications(request);
        CompletableFuture<VerificationList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<VerificationList> listVerifications(
            ListVerificationsRequest request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<VerificationList>> rawFuture =
                this.rawClient.listVerifications(request, requestOptions);
        CompletableFuture<VerificationList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<VerificationObject> getVerification(String id) {
        CompletableFuture<MarketSDKHttpResponse<VerificationObject>> rawFuture = this.rawClient.getVerification(id);
        CompletableFuture<VerificationObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<VerificationObject> getVerification(String id, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<VerificationObject>> rawFuture =
                this.rawClient.getVerification(id, requestOptions);
        CompletableFuture<VerificationObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<VerificationObject> getVerification(String id, GetVerificationRequest request) {
        CompletableFuture<MarketSDKHttpResponse<VerificationObject>> rawFuture =
                this.rawClient.getVerification(id, request);
        CompletableFuture<VerificationObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<VerificationObject> getVerification(
            String id, GetVerificationRequest request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<VerificationObject>> rawFuture =
                this.rawClient.getVerification(id, request, requestOptions);
        CompletableFuture<VerificationObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<VerificationObject> cancelVerification(String id) {
        CompletableFuture<MarketSDKHttpResponse<VerificationObject>> rawFuture = this.rawClient.cancelVerification(id);
        CompletableFuture<VerificationObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<VerificationObject> cancelVerification(String id, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<VerificationObject>> rawFuture =
                this.rawClient.cancelVerification(id, requestOptions);
        CompletableFuture<VerificationObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<VerificationObject> cancelVerification(String id, CancelVerificationRequest request) {
        CompletableFuture<MarketSDKHttpResponse<VerificationObject>> rawFuture =
                this.rawClient.cancelVerification(id, request);
        CompletableFuture<VerificationObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<VerificationObject> cancelVerification(
            String id, CancelVerificationRequest request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<VerificationObject>> rawFuture =
                this.rawClient.cancelVerification(id, request, requestOptions);
        CompletableFuture<VerificationObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Filter by <code>stage</code> for a queue.
     */
    public CompletableFuture<DisputeList> listDisputes() {
        CompletableFuture<MarketSDKHttpResponse<DisputeList>> rawFuture = this.rawClient.listDisputes();
        CompletableFuture<DisputeList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Filter by <code>stage</code> for a queue.
     */
    public CompletableFuture<DisputeList> listDisputes(RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<DisputeList>> rawFuture = this.rawClient.listDisputes(requestOptions);
        CompletableFuture<DisputeList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Filter by <code>stage</code> for a queue.
     */
    public CompletableFuture<DisputeList> listDisputes(ListDisputesRequest request) {
        CompletableFuture<MarketSDKHttpResponse<DisputeList>> rawFuture = this.rawClient.listDisputes(request);
        CompletableFuture<DisputeList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Filter by <code>stage</code> for a queue.
     */
    public CompletableFuture<DisputeList> listDisputes(ListDisputesRequest request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<DisputeList>> rawFuture =
                this.rawClient.listDisputes(request, requestOptions);
        CompletableFuture<DisputeList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<DisputeObject> getDispute(String id) {
        CompletableFuture<MarketSDKHttpResponse<DisputeObject>> rawFuture = this.rawClient.getDispute(id);
        CompletableFuture<DisputeObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<DisputeObject> getDispute(String id, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<DisputeObject>> rawFuture =
                this.rawClient.getDispute(id, requestOptions);
        CompletableFuture<DisputeObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<DisputeObject> getDispute(String id, GetDisputeRequest request) {
        CompletableFuture<MarketSDKHttpResponse<DisputeObject>> rawFuture = this.rawClient.getDispute(id, request);
        CompletableFuture<DisputeObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<DisputeObject> getDispute(
            String id, GetDisputeRequest request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<DisputeObject>> rawFuture =
                this.rawClient.getDispute(id, request, requestOptions);
        CompletableFuture<DisputeObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<DisputeEvidenceList> listDisputeEvidence(String id) {
        CompletableFuture<MarketSDKHttpResponse<DisputeEvidenceList>> rawFuture =
                this.rawClient.listDisputeEvidence(id);
        CompletableFuture<DisputeEvidenceList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<DisputeEvidenceList> listDisputeEvidence(String id, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<DisputeEvidenceList>> rawFuture =
                this.rawClient.listDisputeEvidence(id, requestOptions);
        CompletableFuture<DisputeEvidenceList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<DisputeEvidenceList> listDisputeEvidence(String id, ListDisputeEvidenceRequest request) {
        CompletableFuture<MarketSDKHttpResponse<DisputeEvidenceList>> rawFuture =
                this.rawClient.listDisputeEvidence(id, request);
        CompletableFuture<DisputeEvidenceList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<DisputeEvidenceList> listDisputeEvidence(
            String id, ListDisputeEvidenceRequest request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<DisputeEvidenceList>> rawFuture =
                this.rawClient.listDisputeEvidence(id, request, requestOptions);
        CompletableFuture<DisputeEvidenceList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Only while the dispute is in its evidence stage.
     */
    public CompletableFuture<DisputeEvidenceObject> addDisputeEvidence(String id, AddEvidenceDto request) {
        CompletableFuture<MarketSDKHttpResponse<DisputeEvidenceObject>> rawFuture =
                this.rawClient.addDisputeEvidence(id, request);
        CompletableFuture<DisputeEvidenceObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Only while the dispute is in its evidence stage.
     */
    public CompletableFuture<DisputeEvidenceObject> addDisputeEvidence(
            String id, AddEvidenceDto request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<DisputeEvidenceObject>> rawFuture =
                this.rawClient.addDisputeEvidence(id, request, requestOptions);
        CompletableFuture<DisputeEvidenceObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<DisputeObject> closeDisputeEvidence(String id) {
        CompletableFuture<MarketSDKHttpResponse<DisputeObject>> rawFuture = this.rawClient.closeDisputeEvidence(id);
        CompletableFuture<DisputeObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<DisputeObject> closeDisputeEvidence(String id, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<DisputeObject>> rawFuture =
                this.rawClient.closeDisputeEvidence(id, requestOptions);
        CompletableFuture<DisputeObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<DisputeObject> closeDisputeEvidence(String id, CloseDisputeEvidenceRequest request) {
        CompletableFuture<MarketSDKHttpResponse<DisputeObject>> rawFuture =
                this.rawClient.closeDisputeEvidence(id, request);
        CompletableFuture<DisputeObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<DisputeObject> closeDisputeEvidence(
            String id, CloseDisputeEvidenceRequest request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<DisputeObject>> rawFuture =
                this.rawClient.closeDisputeEvidence(id, request, requestOptions);
        CompletableFuture<DisputeObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Your team's decision: who it went against, in writing, and with payments on, how much goes back to the buyer. On a claimed order, deciding against the party who disputed upholds the claim and completes the order; deciding against the claimant cancels it.
     */
    public CompletableFuture<DisputeObject> decideDispute(String id, DecideDisputeDto request) {
        CompletableFuture<MarketSDKHttpResponse<DisputeObject>> rawFuture = this.rawClient.decideDispute(id, request);
        CompletableFuture<DisputeObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Your team's decision: who it went against, in writing, and with payments on, how much goes back to the buyer. On a claimed order, deciding against the party who disputed upholds the claim and completes the order; deciding against the claimant cancels it.
     */
    public CompletableFuture<DisputeObject> decideDispute(
            String id, DecideDisputeDto request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<DisputeObject>> rawFuture =
                this.rawClient.decideDispute(id, request, requestOptions);
        CompletableFuture<DisputeObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * On a claimed order, by the party who did not claim: the order becomes disputed. On a completed order, by either party inside the dispute window: the order stays completed.
     */
    public CompletableFuture<DisputeObject> openDispute(String id, OpenDisputeDto request) {
        CompletableFuture<MarketSDKHttpResponse<DisputeObject>> rawFuture = this.rawClient.openDispute(id, request);
        CompletableFuture<DisputeObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * On a claimed order, by the party who did not claim: the order becomes disputed. On a completed order, by either party inside the dispute window: the order stays completed.
     */
    public CompletableFuture<DisputeObject> openDispute(
            String id, OpenDisputeDto request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<DisputeObject>> rawFuture =
                this.rawClient.openDispute(id, request, requestOptions);
        CompletableFuture<DisputeObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }
}
