/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AttributeDefinitionObject.Builder.class)
public final class AttributeDefinitionObject {
    private final String key;

    private final Optional<String> label;

    private final AttributeDefinitionObjectType type;

    private final Optional<Boolean> required;

    private final Optional<List<String>> options;

    private final Optional<Double> min;

    private final Optional<Double> max;

    private final Optional<Double> maxLength;

    private final Map<String, Object> additionalProperties;

    private AttributeDefinitionObject(
            String key,
            Optional<String> label,
            AttributeDefinitionObjectType type,
            Optional<Boolean> required,
            Optional<List<String>> options,
            Optional<Double> min,
            Optional<Double> max,
            Optional<Double> maxLength,
            Map<String, Object> additionalProperties) {
        this.key = key;
        this.label = label;
        this.type = type;
        this.required = required;
        this.options = options;
        this.min = min;
        this.max = max;
        this.maxLength = maxLength;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("key")
    public String getKey() {
        return key;
    }

    @JsonProperty("label")
    public Optional<String> getLabel() {
        return label;
    }

    @JsonProperty("type")
    public AttributeDefinitionObjectType getType() {
        return type;
    }

    @JsonProperty("required")
    public Optional<Boolean> getRequired() {
        return required;
    }

    @JsonProperty("options")
    public Optional<List<String>> getOptions() {
        return options;
    }

    @JsonProperty("min")
    public Optional<Double> getMin() {
        return min;
    }

    @JsonProperty("max")
    public Optional<Double> getMax() {
        return max;
    }

    @JsonProperty("max_length")
    public Optional<Double> getMaxLength() {
        return maxLength;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AttributeDefinitionObject && equalTo((AttributeDefinitionObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AttributeDefinitionObject other) {
        return key.equals(other.key)
                && label.equals(other.label)
                && type.equals(other.type)
                && required.equals(other.required)
                && options.equals(other.options)
                && min.equals(other.min)
                && max.equals(other.max)
                && maxLength.equals(other.maxLength);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.key, this.label, this.type, this.required, this.options, this.min, this.max, this.maxLength);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static KeyStage builder() {
        return new Builder();
    }

    public interface KeyStage {
        TypeStage key(@NotNull String key);

        Builder from(AttributeDefinitionObject other);
    }

    public interface TypeStage {
        _FinalStage type(@NotNull AttributeDefinitionObjectType type);
    }

    public interface _FinalStage {
        AttributeDefinitionObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage label(Optional<String> label);

        _FinalStage label(String label);

        _FinalStage required(Optional<Boolean> required);

        _FinalStage required(Boolean required);

        _FinalStage options(Optional<List<String>> options);

        _FinalStage options(List<String> options);

        _FinalStage min(Optional<Double> min);

        _FinalStage min(Double min);

        _FinalStage max(Optional<Double> max);

        _FinalStage max(Double max);

        _FinalStage maxLength(Optional<Double> maxLength);

        _FinalStage maxLength(Double maxLength);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements KeyStage, TypeStage, _FinalStage {
        private String key;

        private AttributeDefinitionObjectType type;

        private Optional<Double> maxLength = Optional.empty();

        private Optional<Double> max = Optional.empty();

        private Optional<Double> min = Optional.empty();

        private Optional<List<String>> options = Optional.empty();

        private Optional<Boolean> required = Optional.empty();

        private Optional<String> label = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AttributeDefinitionObject other) {
            key(other.getKey());
            label(other.getLabel());
            type(other.getType());
            required(other.getRequired());
            options(other.getOptions());
            min(other.getMin());
            max(other.getMax());
            maxLength(other.getMaxLength());
            return this;
        }

        @java.lang.Override
        @JsonSetter("key")
        public TypeStage key(@NotNull String key) {
            this.key = Objects.requireNonNull(key, "key must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull AttributeDefinitionObjectType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage maxLength(Double maxLength) {
            this.maxLength = Optional.ofNullable(maxLength);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "max_length", nulls = Nulls.SKIP)
        public _FinalStage maxLength(Optional<Double> maxLength) {
            this.maxLength = maxLength;
            return this;
        }

        @java.lang.Override
        public _FinalStage max(Double max) {
            this.max = Optional.ofNullable(max);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "max", nulls = Nulls.SKIP)
        public _FinalStage max(Optional<Double> max) {
            this.max = max;
            return this;
        }

        @java.lang.Override
        public _FinalStage min(Double min) {
            this.min = Optional.ofNullable(min);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "min", nulls = Nulls.SKIP)
        public _FinalStage min(Optional<Double> min) {
            this.min = min;
            return this;
        }

        @java.lang.Override
        public _FinalStage options(List<String> options) {
            this.options = Optional.ofNullable(options);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "options", nulls = Nulls.SKIP)
        public _FinalStage options(Optional<List<String>> options) {
            this.options = options;
            return this;
        }

        @java.lang.Override
        public _FinalStage required(Boolean required) {
            this.required = Optional.ofNullable(required);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "required", nulls = Nulls.SKIP)
        public _FinalStage required(Optional<Boolean> required) {
            this.required = required;
            return this;
        }

        @java.lang.Override
        public _FinalStage label(String label) {
            this.label = Optional.ofNullable(label);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "label", nulls = Nulls.SKIP)
        public _FinalStage label(Optional<String> label) {
            this.label = label;
            return this;
        }

        @java.lang.Override
        public AttributeDefinitionObject build() {
            return new AttributeDefinitionObject(
                    key, label, type, required, options, min, max, maxLength, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
