/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CardDisputeObject.Builder.class)
public final class CardDisputeObject {
    private final CardDisputeObjectObject object;

    private final String id;

    private final String order;

    private final String stripeDispute;

    private final double amount;

    private final String currency;

    private final String reason;

    private final String status;

    private final OffsetDateTime createdAt;

    private final Map<String, Object> additionalProperties;

    private CardDisputeObject(
            CardDisputeObjectObject object,
            String id,
            String order,
            String stripeDispute,
            double amount,
            String currency,
            String reason,
            String status,
            OffsetDateTime createdAt,
            Map<String, Object> additionalProperties) {
        this.object = object;
        this.id = id;
        this.order = order;
        this.stripeDispute = stripeDispute;
        this.amount = amount;
        this.currency = currency;
        this.reason = reason;
        this.status = status;
        this.createdAt = createdAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("object")
    public CardDisputeObjectObject getObject() {
        return object;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("order")
    public String getOrder() {
        return order;
    }

    /**
     * @return The dispute's id on your Stripe account.
     */
    @JsonProperty("stripe_dispute")
    public String getStripeDispute() {
        return stripeDispute;
    }

    @JsonProperty("amount")
    public double getAmount() {
        return amount;
    }

    @JsonProperty("currency")
    public String getCurrency() {
        return currency;
    }

    @JsonProperty("reason")
    public String getReason() {
        return reason;
    }

    /**
     * @return Stripe's status, such as needs_response, won, or lost.
     */
    @JsonProperty("status")
    public String getStatus() {
        return status;
    }

    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CardDisputeObject && equalTo((CardDisputeObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CardDisputeObject other) {
        return object.equals(other.object)
                && id.equals(other.id)
                && order.equals(other.order)
                && stripeDispute.equals(other.stripeDispute)
                && amount == other.amount
                && currency.equals(other.currency)
                && reason.equals(other.reason)
                && status.equals(other.status)
                && createdAt.equals(other.createdAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.object,
                this.id,
                this.order,
                this.stripeDispute,
                this.amount,
                this.currency,
                this.reason,
                this.status,
                this.createdAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ObjectStage builder() {
        return new Builder();
    }

    public interface ObjectStage {
        IdStage object(@NotNull CardDisputeObjectObject object);

        Builder from(CardDisputeObject other);
    }

    public interface IdStage {
        OrderStage id(@NotNull String id);
    }

    public interface OrderStage {
        StripeDisputeStage order(@NotNull String order);
    }

    public interface StripeDisputeStage {
        /**
         * <p>The dispute's id on your Stripe account.</p>
         */
        AmountStage stripeDispute(@NotNull String stripeDispute);
    }

    public interface AmountStage {
        CurrencyStage amount(double amount);
    }

    public interface CurrencyStage {
        ReasonStage currency(@NotNull String currency);
    }

    public interface ReasonStage {
        StatusStage reason(@NotNull String reason);
    }

    public interface StatusStage {
        /**
         * <p>Stripe's status, such as needs_response, won, or lost.</p>
         */
        CreatedAtStage status(@NotNull String status);
    }

    public interface CreatedAtStage {
        _FinalStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface _FinalStage {
        CardDisputeObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ObjectStage,
                    IdStage,
                    OrderStage,
                    StripeDisputeStage,
                    AmountStage,
                    CurrencyStage,
                    ReasonStage,
                    StatusStage,
                    CreatedAtStage,
                    _FinalStage {
        private CardDisputeObjectObject object;

        private String id;

        private String order;

        private String stripeDispute;

        private double amount;

        private String currency;

        private String reason;

        private String status;

        private OffsetDateTime createdAt;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CardDisputeObject other) {
            object(other.getObject());
            id(other.getId());
            order(other.getOrder());
            stripeDispute(other.getStripeDispute());
            amount(other.getAmount());
            currency(other.getCurrency());
            reason(other.getReason());
            status(other.getStatus());
            createdAt(other.getCreatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("object")
        public IdStage object(@NotNull CardDisputeObjectObject object) {
            this.object = Objects.requireNonNull(object, "object must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public OrderStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("order")
        public StripeDisputeStage order(@NotNull String order) {
            this.order = Objects.requireNonNull(order, "order must not be null");
            return this;
        }

        /**
         * <p>The dispute's id on your Stripe account.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("stripe_dispute")
        public AmountStage stripeDispute(@NotNull String stripeDispute) {
            this.stripeDispute = Objects.requireNonNull(stripeDispute, "stripeDispute must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("amount")
        public CurrencyStage amount(double amount) {
            this.amount = amount;
            return this;
        }

        @java.lang.Override
        @JsonSetter("currency")
        public ReasonStage currency(@NotNull String currency) {
            this.currency = Objects.requireNonNull(currency, "currency must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("reason")
        public StatusStage reason(@NotNull String reason) {
            this.reason = Objects.requireNonNull(reason, "reason must not be null");
            return this;
        }

        /**
         * <p>Stripe's status, such as needs_response, won, or lost.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public CreatedAtStage status(@NotNull String status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("created_at")
        public _FinalStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        public CardDisputeObject build() {
            return new CardDisputeObject(
                    object,
                    id,
                    order,
                    stripeDispute,
                    amount,
                    currency,
                    reason,
                    status,
                    createdAt,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
