/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CheckoutUrlsDto.Builder.class)
public final class CheckoutUrlsDto {
    private final String successUrl;

    private final String cancelUrl;

    private final Map<String, Object> additionalProperties;

    private CheckoutUrlsDto(String successUrl, String cancelUrl, Map<String, Object> additionalProperties) {
        this.successUrl = successUrl;
        this.cancelUrl = cancelUrl;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Where Stripe sends the buyer after paying.
     */
    @JsonProperty("success_url")
    public String getSuccessUrl() {
        return successUrl;
    }

    /**
     * @return Where Stripe sends the buyer if they go back.
     */
    @JsonProperty("cancel_url")
    public String getCancelUrl() {
        return cancelUrl;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CheckoutUrlsDto && equalTo((CheckoutUrlsDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CheckoutUrlsDto other) {
        return successUrl.equals(other.successUrl) && cancelUrl.equals(other.cancelUrl);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.successUrl, this.cancelUrl);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SuccessUrlStage builder() {
        return new Builder();
    }

    public interface SuccessUrlStage {
        /**
         * <p>Where Stripe sends the buyer after paying.</p>
         */
        CancelUrlStage successUrl(@NotNull String successUrl);

        Builder from(CheckoutUrlsDto other);
    }

    public interface CancelUrlStage {
        /**
         * <p>Where Stripe sends the buyer if they go back.</p>
         */
        _FinalStage cancelUrl(@NotNull String cancelUrl);
    }

    public interface _FinalStage {
        CheckoutUrlsDto build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SuccessUrlStage, CancelUrlStage, _FinalStage {
        private String successUrl;

        private String cancelUrl;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CheckoutUrlsDto other) {
            successUrl(other.getSuccessUrl());
            cancelUrl(other.getCancelUrl());
            return this;
        }

        /**
         * <p>Where Stripe sends the buyer after paying.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("success_url")
        public CancelUrlStage successUrl(@NotNull String successUrl) {
            this.successUrl = Objects.requireNonNull(successUrl, "successUrl must not be null");
            return this;
        }

        /**
         * <p>Where Stripe sends the buyer if they go back.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("cancel_url")
        public _FinalStage cancelUrl(@NotNull String cancelUrl) {
            this.cancelUrl = Objects.requireNonNull(cancelUrl, "cancelUrl must not be null");
            return this;
        }

        @java.lang.Override
        public CheckoutUrlsDto build() {
            return new CheckoutUrlsDto(successUrl, cancelUrl, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
