/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.Nullable;
import com.marketsdk.core.NullableNonemptyFilter;
import com.marketsdk.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DisputeObject.Builder.class)
public final class DisputeObject {
    private final DisputeObjectObject object;

    private final String id;

    private final String order;

    private final DisputeObjectKind kind;

    private final DisputeObjectOpenedBy openedBy;

    private final String opener;

    private final Optional<String> reason;

    private final DisputeObjectStage stage;

    private final OffsetDateTime evidenceDueAt;

    private final Optional<OffsetDateTime> decisionDueAt;

    private final boolean overdue;

    private final double evidenceCount;

    private final Optional<DisputeDecisionObject> decision;

    private final List<CardDisputeObject> cardDisputes;

    private final Map<String, String> metadata;

    private final OffsetDateTime createdAt;

    private final OffsetDateTime updatedAt;

    private final Map<String, Object> additionalProperties;

    private DisputeObject(
            DisputeObjectObject object,
            String id,
            String order,
            DisputeObjectKind kind,
            DisputeObjectOpenedBy openedBy,
            String opener,
            Optional<String> reason,
            DisputeObjectStage stage,
            OffsetDateTime evidenceDueAt,
            Optional<OffsetDateTime> decisionDueAt,
            boolean overdue,
            double evidenceCount,
            Optional<DisputeDecisionObject> decision,
            List<CardDisputeObject> cardDisputes,
            Map<String, String> metadata,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt,
            Map<String, Object> additionalProperties) {
        this.object = object;
        this.id = id;
        this.order = order;
        this.kind = kind;
        this.openedBy = openedBy;
        this.opener = opener;
        this.reason = reason;
        this.stage = stage;
        this.evidenceDueAt = evidenceDueAt;
        this.decisionDueAt = decisionDueAt;
        this.overdue = overdue;
        this.evidenceCount = evidenceCount;
        this.decision = decision;
        this.cardDisputes = cardDisputes;
        this.metadata = metadata;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("object")
    public DisputeObjectObject getObject() {
        return object;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("order")
    public String getOrder() {
        return order;
    }

    @JsonProperty("kind")
    public DisputeObjectKind getKind() {
        return kind;
    }

    @JsonProperty("opened_by")
    public DisputeObjectOpenedBy getOpenedBy() {
        return openedBy;
    }

    @JsonProperty("opener")
    public String getOpener() {
        return opener;
    }

    /**
     * @return Null once the opener's data is erased.
     */
    @JsonIgnore
    public Optional<String> getReason() {
        if (reason == null) {
            return Optional.empty();
        }
        return reason;
    }

    @JsonProperty("stage")
    public DisputeObjectStage getStage() {
        return stage;
    }

    @JsonProperty("evidence_due_at")
    public OffsetDateTime getEvidenceDueAt() {
        return evidenceDueAt;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getDecisionDueAt() {
        if (decisionDueAt == null) {
            return Optional.empty();
        }
        return decisionDueAt;
    }

    /**
     * @return True once the decision time limit has passed with no decision.
     */
    @JsonProperty("overdue")
    public boolean getOverdue() {
        return overdue;
    }

    /**
     * @return Pieces of evidence given so far.
     */
    @JsonProperty("evidence_count")
    public double getEvidenceCount() {
        return evidenceCount;
    }

    @JsonIgnore
    public Optional<DisputeDecisionObject> getDecision() {
        if (decision == null) {
            return Optional.empty();
        }
        return decision;
    }

    /**
     * @return Card disputes on the same order, linked here but separate.
     */
    @JsonProperty("card_disputes")
    public List<CardDisputeObject> getCardDisputes() {
        return cardDisputes;
    }

    @JsonProperty("metadata")
    public Map<String, String> getMetadata() {
        return metadata;
    }

    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("updated_at")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("reason")
    private Optional<String> _getReason() {
        return reason;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("decision_due_at")
    private Optional<OffsetDateTime> _getDecisionDueAt() {
        return decisionDueAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("decision")
    private Optional<DisputeDecisionObject> _getDecision() {
        return decision;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DisputeObject && equalTo((DisputeObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DisputeObject other) {
        return object.equals(other.object)
                && id.equals(other.id)
                && order.equals(other.order)
                && kind.equals(other.kind)
                && openedBy.equals(other.openedBy)
                && opener.equals(other.opener)
                && reason.equals(other.reason)
                && stage.equals(other.stage)
                && evidenceDueAt.equals(other.evidenceDueAt)
                && decisionDueAt.equals(other.decisionDueAt)
                && overdue == other.overdue
                && evidenceCount == other.evidenceCount
                && decision.equals(other.decision)
                && cardDisputes.equals(other.cardDisputes)
                && metadata.equals(other.metadata)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.object,
                this.id,
                this.order,
                this.kind,
                this.openedBy,
                this.opener,
                this.reason,
                this.stage,
                this.evidenceDueAt,
                this.decisionDueAt,
                this.overdue,
                this.evidenceCount,
                this.decision,
                this.cardDisputes,
                this.metadata,
                this.createdAt,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ObjectStage builder() {
        return new Builder();
    }

    public interface ObjectStage {
        IdStage object(@NotNull DisputeObjectObject object);

        Builder from(DisputeObject other);
    }

    public interface IdStage {
        OrderStage id(@NotNull String id);
    }

    public interface OrderStage {
        KindStage order(@NotNull String order);
    }

    public interface KindStage {
        OpenedByStage kind(@NotNull DisputeObjectKind kind);
    }

    public interface OpenedByStage {
        OpenerStage openedBy(@NotNull DisputeObjectOpenedBy openedBy);
    }

    public interface OpenerStage {
        StageStage opener(@NotNull String opener);
    }

    public interface StageStage {
        EvidenceDueAtStage stage(@NotNull DisputeObjectStage stage);
    }

    public interface EvidenceDueAtStage {
        OverdueStage evidenceDueAt(@NotNull OffsetDateTime evidenceDueAt);
    }

    public interface OverdueStage {
        /**
         * <p>True once the decision time limit has passed with no decision.</p>
         */
        EvidenceCountStage overdue(boolean overdue);
    }

    public interface EvidenceCountStage {
        /**
         * <p>Pieces of evidence given so far.</p>
         */
        CreatedAtStage evidenceCount(double evidenceCount);
    }

    public interface CreatedAtStage {
        UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface UpdatedAtStage {
        _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface _FinalStage {
        DisputeObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Null once the opener's data is erased.</p>
         */
        _FinalStage reason(Optional<String> reason);

        _FinalStage reason(String reason);

        _FinalStage reason(Nullable<String> reason);

        _FinalStage decisionDueAt(Optional<OffsetDateTime> decisionDueAt);

        _FinalStage decisionDueAt(OffsetDateTime decisionDueAt);

        _FinalStage decisionDueAt(Nullable<OffsetDateTime> decisionDueAt);

        _FinalStage decision(Optional<DisputeDecisionObject> decision);

        _FinalStage decision(DisputeDecisionObject decision);

        _FinalStage decision(Nullable<DisputeDecisionObject> decision);

        /**
         * <p>Card disputes on the same order, linked here but separate.</p>
         */
        _FinalStage cardDisputes(List<CardDisputeObject> cardDisputes);

        _FinalStage addCardDisputes(CardDisputeObject cardDisputes);

        _FinalStage addAllCardDisputes(List<CardDisputeObject> cardDisputes);

        _FinalStage metadata(Map<String, String> metadata);

        _FinalStage putAllMetadata(Map<String, String> metadata);

        _FinalStage metadata(String key, String value);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ObjectStage,
                    IdStage,
                    OrderStage,
                    KindStage,
                    OpenedByStage,
                    OpenerStage,
                    StageStage,
                    EvidenceDueAtStage,
                    OverdueStage,
                    EvidenceCountStage,
                    CreatedAtStage,
                    UpdatedAtStage,
                    _FinalStage {
        private DisputeObjectObject object;

        private String id;

        private String order;

        private DisputeObjectKind kind;

        private DisputeObjectOpenedBy openedBy;

        private String opener;

        private DisputeObjectStage stage;

        private OffsetDateTime evidenceDueAt;

        private boolean overdue;

        private double evidenceCount;

        private OffsetDateTime createdAt;

        private OffsetDateTime updatedAt;

        private Map<String, String> metadata = new LinkedHashMap<>();

        private List<CardDisputeObject> cardDisputes = new ArrayList<>();

        private Optional<DisputeDecisionObject> decision = Optional.empty();

        private Optional<OffsetDateTime> decisionDueAt = Optional.empty();

        private Optional<String> reason = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DisputeObject other) {
            object(other.getObject());
            id(other.getId());
            order(other.getOrder());
            kind(other.getKind());
            openedBy(other.getOpenedBy());
            opener(other.getOpener());
            reason(other.getReason());
            stage(other.getStage());
            evidenceDueAt(other.getEvidenceDueAt());
            decisionDueAt(other.getDecisionDueAt());
            overdue(other.getOverdue());
            evidenceCount(other.getEvidenceCount());
            decision(other.getDecision());
            cardDisputes(other.getCardDisputes());
            metadata(other.getMetadata());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("object")
        public IdStage object(@NotNull DisputeObjectObject object) {
            this.object = Objects.requireNonNull(object, "object must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public OrderStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("order")
        public KindStage order(@NotNull String order) {
            this.order = Objects.requireNonNull(order, "order must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("kind")
        public OpenedByStage kind(@NotNull DisputeObjectKind kind) {
            this.kind = Objects.requireNonNull(kind, "kind must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("opened_by")
        public OpenerStage openedBy(@NotNull DisputeObjectOpenedBy openedBy) {
            this.openedBy = Objects.requireNonNull(openedBy, "openedBy must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("opener")
        public StageStage opener(@NotNull String opener) {
            this.opener = Objects.requireNonNull(opener, "opener must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("stage")
        public EvidenceDueAtStage stage(@NotNull DisputeObjectStage stage) {
            this.stage = Objects.requireNonNull(stage, "stage must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("evidence_due_at")
        public OverdueStage evidenceDueAt(@NotNull OffsetDateTime evidenceDueAt) {
            this.evidenceDueAt = Objects.requireNonNull(evidenceDueAt, "evidenceDueAt must not be null");
            return this;
        }

        /**
         * <p>True once the decision time limit has passed with no decision.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("overdue")
        public EvidenceCountStage overdue(boolean overdue) {
            this.overdue = overdue;
            return this;
        }

        /**
         * <p>Pieces of evidence given so far.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("evidence_count")
        public CreatedAtStage evidenceCount(double evidenceCount) {
            this.evidenceCount = evidenceCount;
            return this;
        }

        @java.lang.Override
        @JsonSetter("created_at")
        public UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updated_at")
        public _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage metadata(String key, String value) {
            this.metadata.put(key, value);
            return this;
        }

        @java.lang.Override
        public _FinalStage putAllMetadata(Map<String, String> metadata) {
            if (metadata != null) {
                this.metadata.putAll(metadata);
            }
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public _FinalStage metadata(Map<String, String> metadata) {
            this.metadata.clear();
            if (metadata != null) {
                this.metadata.putAll(metadata);
            }
            return this;
        }

        /**
         * <p>Card disputes on the same order, linked here but separate.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllCardDisputes(List<CardDisputeObject> cardDisputes) {
            if (cardDisputes != null) {
                this.cardDisputes.addAll(cardDisputes);
            }
            return this;
        }

        /**
         * <p>Card disputes on the same order, linked here but separate.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addCardDisputes(CardDisputeObject cardDisputes) {
            this.cardDisputes.add(cardDisputes);
            return this;
        }

        /**
         * <p>Card disputes on the same order, linked here but separate.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "card_disputes", nulls = Nulls.SKIP)
        public _FinalStage cardDisputes(List<CardDisputeObject> cardDisputes) {
            this.cardDisputes.clear();
            if (cardDisputes != null) {
                this.cardDisputes.addAll(cardDisputes);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage decision(Nullable<DisputeDecisionObject> decision) {
            if (decision.isNull()) {
                this.decision = null;
            } else if (decision.isEmpty()) {
                this.decision = Optional.empty();
            } else {
                this.decision = Optional.of(decision.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage decision(DisputeDecisionObject decision) {
            this.decision = Optional.ofNullable(decision);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "decision", nulls = Nulls.SKIP)
        public _FinalStage decision(Optional<DisputeDecisionObject> decision) {
            this.decision = decision;
            return this;
        }

        @java.lang.Override
        public _FinalStage decisionDueAt(Nullable<OffsetDateTime> decisionDueAt) {
            if (decisionDueAt.isNull()) {
                this.decisionDueAt = null;
            } else if (decisionDueAt.isEmpty()) {
                this.decisionDueAt = Optional.empty();
            } else {
                this.decisionDueAt = Optional.of(decisionDueAt.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage decisionDueAt(OffsetDateTime decisionDueAt) {
            this.decisionDueAt = Optional.ofNullable(decisionDueAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "decision_due_at", nulls = Nulls.SKIP)
        public _FinalStage decisionDueAt(Optional<OffsetDateTime> decisionDueAt) {
            this.decisionDueAt = decisionDueAt;
            return this;
        }

        /**
         * <p>Null once the opener's data is erased.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage reason(Nullable<String> reason) {
            if (reason.isNull()) {
                this.reason = null;
            } else if (reason.isEmpty()) {
                this.reason = Optional.empty();
            } else {
                this.reason = Optional.of(reason.get());
            }
            return this;
        }

        /**
         * <p>Null once the opener's data is erased.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage reason(String reason) {
            this.reason = Optional.ofNullable(reason);
            return this;
        }

        /**
         * <p>Null once the opener's data is erased.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "reason", nulls = Nulls.SKIP)
        public _FinalStage reason(Optional<String> reason) {
            this.reason = reason;
            return this;
        }

        @java.lang.Override
        public DisputeObject build() {
            return new DisputeObject(
                    object,
                    id,
                    order,
                    kind,
                    openedBy,
                    opener,
                    reason,
                    stage,
                    evidenceDueAt,
                    decisionDueAt,
                    overdue,
                    evidenceCount,
                    decision,
                    cardDisputes,
                    metadata,
                    createdAt,
                    updatedAt,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
