/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ErrorBody.Builder.class)
public final class ErrorBody {
    private final String code;

    private final String message;

    private final Optional<String> param;

    private final String requestId;

    private final Map<String, Object> additionalProperties;

    private ErrorBody(
            String code,
            String message,
            Optional<String> param,
            String requestId,
            Map<String, Object> additionalProperties) {
        this.code = code;
        this.message = message;
        this.param = param;
        this.requestId = requestId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Machine-readable. Never changes once published.
     */
    @JsonProperty("code")
    public String getCode() {
        return code;
    }

    /**
     * @return For people.
     */
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    /**
     * @return The request field at fault.
     */
    @JsonProperty("param")
    public Optional<String> getParam() {
        return param;
    }

    @JsonProperty("request_id")
    public String getRequestId() {
        return requestId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ErrorBody && equalTo((ErrorBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ErrorBody other) {
        return code.equals(other.code)
                && message.equals(other.message)
                && param.equals(other.param)
                && requestId.equals(other.requestId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.code, this.message, this.param, this.requestId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CodeStage builder() {
        return new Builder();
    }

    public interface CodeStage {
        /**
         * <p>Machine-readable. Never changes once published.</p>
         */
        MessageStage code(@NotNull String code);

        Builder from(ErrorBody other);
    }

    public interface MessageStage {
        /**
         * <p>For people.</p>
         */
        RequestIdStage message(@NotNull String message);
    }

    public interface RequestIdStage {
        _FinalStage requestId(@NotNull String requestId);
    }

    public interface _FinalStage {
        ErrorBody build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The request field at fault.</p>
         */
        _FinalStage param(Optional<String> param);

        _FinalStage param(String param);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CodeStage, MessageStage, RequestIdStage, _FinalStage {
        private String code;

        private String message;

        private String requestId;

        private Optional<String> param = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ErrorBody other) {
            code(other.getCode());
            message(other.getMessage());
            param(other.getParam());
            requestId(other.getRequestId());
            return this;
        }

        /**
         * <p>Machine-readable. Never changes once published.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("code")
        public MessageStage code(@NotNull String code) {
            this.code = Objects.requireNonNull(code, "code must not be null");
            return this;
        }

        /**
         * <p>For people.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("message")
        public RequestIdStage message(@NotNull String message) {
            this.message = Objects.requireNonNull(message, "message must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("request_id")
        public _FinalStage requestId(@NotNull String requestId) {
            this.requestId = Objects.requireNonNull(requestId, "requestId must not be null");
            return this;
        }

        /**
         * <p>The request field at fault.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage param(String param) {
            this.param = Optional.ofNullable(param);
            return this;
        }

        /**
         * <p>The request field at fault.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "param", nulls = Nulls.SKIP)
        public _FinalStage param(Optional<String> param) {
            this.param = param;
            return this;
        }

        @java.lang.Override
        public ErrorBody build() {
            return new ErrorBody(code, message, param, requestId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
