/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EventObjectType {
    public static final EventObjectType SELLER_CREATED = new EventObjectType(Value.SELLER_CREATED, "seller.created");

    public static final EventObjectType ORDER_COMPLETED = new EventObjectType(Value.ORDER_COMPLETED, "order.completed");

    public static final EventObjectType REVIEW_CREATED = new EventObjectType(Value.REVIEW_CREATED, "review.created");

    public static final EventObjectType CATEGORY_UPDATED =
            new EventObjectType(Value.CATEGORY_UPDATED, "category.updated");

    public static final EventObjectType LISTING_SOLD = new EventObjectType(Value.LISTING_SOLD, "listing.sold");

    public static final EventObjectType PAYMENT_RELEASED =
            new EventObjectType(Value.PAYMENT_RELEASED, "payment.released");

    public static final EventObjectType FLAG_RESOLVED = new EventObjectType(Value.FLAG_RESOLVED, "flag.resolved");

    public static final EventObjectType LISTING_UPDATED = new EventObjectType(Value.LISTING_UPDATED, "listing.updated");

    public static final EventObjectType MEDIA_DELETED = new EventObjectType(Value.MEDIA_DELETED, "media.deleted");

    public static final EventObjectType LISTING_UNPUBLISHED =
            new EventObjectType(Value.LISTING_UNPUBLISHED, "listing.unpublished");

    public static final EventObjectType ORDER_CANCELLATION_PROPOSED =
            new EventObjectType(Value.ORDER_CANCELLATION_PROPOSED, "order.cancellation_proposed");

    public static final EventObjectType CARD_DISPUTE_CREATED =
            new EventObjectType(Value.CARD_DISPUTE_CREATED, "card_dispute.created");

    public static final EventObjectType LISTING_PUBLISHED =
            new EventObjectType(Value.LISTING_PUBLISHED, "listing.published");

    public static final EventObjectType ORDER_DISPUTED = new EventObjectType(Value.ORDER_DISPUTED, "order.disputed");

    public static final EventObjectType DISPUTE_DECIDED = new EventObjectType(Value.DISPUTE_DECIDED, "dispute.decided");

    public static final EventObjectType SELLER_UPDATED = new EventObjectType(Value.SELLER_UPDATED, "seller.updated");

    public static final EventObjectType CATEGORY_CREATED =
            new EventObjectType(Value.CATEGORY_CREATED, "category.created");

    public static final EventObjectType SELLER_VERIFICATION_UPDATED =
            new EventObjectType(Value.SELLER_VERIFICATION_UPDATED, "seller.verification_updated");

    public static final EventObjectType LISTING_CREATED = new EventObjectType(Value.LISTING_CREATED, "listing.created");

    public static final EventObjectType BUYER_UPDATED = new EventObjectType(Value.BUYER_UPDATED, "buyer.updated");

    public static final EventObjectType LISTING_EXPIRED = new EventObjectType(Value.LISTING_EXPIRED, "listing.expired");

    public static final EventObjectType PAYMENT_RELEASE_FAILED =
            new EventObjectType(Value.PAYMENT_RELEASE_FAILED, "payment.release_failed");

    public static final EventObjectType ORDER_EXPIRED = new EventObjectType(Value.ORDER_EXPIRED, "order.expired");

    public static final EventObjectType CARD_DISPUTE_UPDATED =
            new EventObjectType(Value.CARD_DISPUTE_UPDATED, "card_dispute.updated");

    public static final EventObjectType ORDER_CREATED = new EventObjectType(Value.ORDER_CREATED, "order.created");

    public static final EventObjectType PAYMENT_FAILED = new EventObjectType(Value.PAYMENT_FAILED, "payment.failed");

    public static final EventObjectType BUYER_ERASED = new EventObjectType(Value.BUYER_ERASED, "buyer.erased");

    public static final EventObjectType MEDIA_READY = new EventObjectType(Value.MEDIA_READY, "media.ready");

    public static final EventObjectType ORDER_CLAIMED = new EventObjectType(Value.ORDER_CLAIMED, "order.claimed");

    public static final EventObjectType REVIEW_VISIBLE = new EventObjectType(Value.REVIEW_VISIBLE, "review.visible");

    public static final EventObjectType REFUND_UPDATED = new EventObjectType(Value.REFUND_UPDATED, "refund.updated");

    public static final EventObjectType DISPUTE_UPDATED = new EventObjectType(Value.DISPUTE_UPDATED, "dispute.updated");

    public static final EventObjectType PAYMENT_REFUNDED =
            new EventObjectType(Value.PAYMENT_REFUNDED, "payment.refunded");

    public static final EventObjectType SELLER_UNSUSPENDED =
            new EventObjectType(Value.SELLER_UNSUSPENDED, "seller.unsuspended");

    public static final EventObjectType DISPUTE_EVIDENCE_ADDED =
            new EventObjectType(Value.DISPUTE_EVIDENCE_ADDED, "dispute.evidence_added");

    public static final EventObjectType REVIEW_REMOVED = new EventObjectType(Value.REVIEW_REMOVED, "review.removed");

    public static final EventObjectType ORDER_COMMITTED = new EventObjectType(Value.ORDER_COMMITTED, "order.committed");

    public static final EventObjectType VERIFICATION_UPDATED =
            new EventObjectType(Value.VERIFICATION_UPDATED, "verification.updated");

    public static final EventObjectType MODERATION_ACTION_CREATED =
            new EventObjectType(Value.MODERATION_ACTION_CREATED, "moderation_action.created");

    public static final EventObjectType REFUND_CREATED = new EventObjectType(Value.REFUND_CREATED, "refund.created");

    public static final EventObjectType PAYMENT_CREATED = new EventObjectType(Value.PAYMENT_CREATED, "payment.created");

    public static final EventObjectType BUYER_CREATED = new EventObjectType(Value.BUYER_CREATED, "buyer.created");

    public static final EventObjectType LISTING_REMOVED = new EventObjectType(Value.LISTING_REMOVED, "listing.removed");

    public static final EventObjectType ORDER_CANCELLATION_DECLINED =
            new EventObjectType(Value.ORDER_CANCELLATION_DECLINED, "order.cancellation_declined");

    public static final EventObjectType REPUTATION_EVENT_VOIDED =
            new EventObjectType(Value.REPUTATION_EVENT_VOIDED, "reputation_event.voided");

    public static final EventObjectType FLAG_CREATED = new EventObjectType(Value.FLAG_CREATED, "flag.created");

    public static final EventObjectType ORDER_CANCELLED = new EventObjectType(Value.ORDER_CANCELLED, "order.cancelled");

    public static final EventObjectType PAYMENT_SUCCEEDED =
            new EventObjectType(Value.PAYMENT_SUCCEEDED, "payment.succeeded");

    public static final EventObjectType SELLER_ERASED = new EventObjectType(Value.SELLER_ERASED, "seller.erased");

    public static final EventObjectType DISPUTE_CREATED = new EventObjectType(Value.DISPUTE_CREATED, "dispute.created");

    public static final EventObjectType PAYMENT_CANCELED =
            new EventObjectType(Value.PAYMENT_CANCELED, "payment.canceled");

    public static final EventObjectType DISPUTE_DECISION_OVERDUE =
            new EventObjectType(Value.DISPUTE_DECISION_OVERDUE, "dispute.decision_overdue");

    public static final EventObjectType SELLER_SUSPENDED =
            new EventObjectType(Value.SELLER_SUSPENDED, "seller.suspended");

    public static final EventObjectType REPUTATION_EVENT_CREATED =
            new EventObjectType(Value.REPUTATION_EVENT_CREATED, "reputation_event.created");

    public static final EventObjectType VERIFICATION_CREATED =
            new EventObjectType(Value.VERIFICATION_CREATED, "verification.created");

    public static final EventObjectType SELLER_PAYOUTS_UPDATED =
            new EventObjectType(Value.SELLER_PAYOUTS_UPDATED, "seller.payouts_updated");

    private final Value value;

    private final String string;

    EventObjectType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof EventObjectType && this.string.equals(((EventObjectType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SELLER_CREATED:
                return visitor.visitSellerCreated();
            case ORDER_COMPLETED:
                return visitor.visitOrderCompleted();
            case REVIEW_CREATED:
                return visitor.visitReviewCreated();
            case CATEGORY_UPDATED:
                return visitor.visitCategoryUpdated();
            case LISTING_SOLD:
                return visitor.visitListingSold();
            case PAYMENT_RELEASED:
                return visitor.visitPaymentReleased();
            case FLAG_RESOLVED:
                return visitor.visitFlagResolved();
            case LISTING_UPDATED:
                return visitor.visitListingUpdated();
            case MEDIA_DELETED:
                return visitor.visitMediaDeleted();
            case LISTING_UNPUBLISHED:
                return visitor.visitListingUnpublished();
            case ORDER_CANCELLATION_PROPOSED:
                return visitor.visitOrderCancellationProposed();
            case CARD_DISPUTE_CREATED:
                return visitor.visitCardDisputeCreated();
            case LISTING_PUBLISHED:
                return visitor.visitListingPublished();
            case ORDER_DISPUTED:
                return visitor.visitOrderDisputed();
            case DISPUTE_DECIDED:
                return visitor.visitDisputeDecided();
            case SELLER_UPDATED:
                return visitor.visitSellerUpdated();
            case CATEGORY_CREATED:
                return visitor.visitCategoryCreated();
            case SELLER_VERIFICATION_UPDATED:
                return visitor.visitSellerVerificationUpdated();
            case LISTING_CREATED:
                return visitor.visitListingCreated();
            case BUYER_UPDATED:
                return visitor.visitBuyerUpdated();
            case LISTING_EXPIRED:
                return visitor.visitListingExpired();
            case PAYMENT_RELEASE_FAILED:
                return visitor.visitPaymentReleaseFailed();
            case ORDER_EXPIRED:
                return visitor.visitOrderExpired();
            case CARD_DISPUTE_UPDATED:
                return visitor.visitCardDisputeUpdated();
            case ORDER_CREATED:
                return visitor.visitOrderCreated();
            case PAYMENT_FAILED:
                return visitor.visitPaymentFailed();
            case BUYER_ERASED:
                return visitor.visitBuyerErased();
            case MEDIA_READY:
                return visitor.visitMediaReady();
            case ORDER_CLAIMED:
                return visitor.visitOrderClaimed();
            case REVIEW_VISIBLE:
                return visitor.visitReviewVisible();
            case REFUND_UPDATED:
                return visitor.visitRefundUpdated();
            case DISPUTE_UPDATED:
                return visitor.visitDisputeUpdated();
            case PAYMENT_REFUNDED:
                return visitor.visitPaymentRefunded();
            case SELLER_UNSUSPENDED:
                return visitor.visitSellerUnsuspended();
            case DISPUTE_EVIDENCE_ADDED:
                return visitor.visitDisputeEvidenceAdded();
            case REVIEW_REMOVED:
                return visitor.visitReviewRemoved();
            case ORDER_COMMITTED:
                return visitor.visitOrderCommitted();
            case VERIFICATION_UPDATED:
                return visitor.visitVerificationUpdated();
            case MODERATION_ACTION_CREATED:
                return visitor.visitModerationActionCreated();
            case REFUND_CREATED:
                return visitor.visitRefundCreated();
            case PAYMENT_CREATED:
                return visitor.visitPaymentCreated();
            case BUYER_CREATED:
                return visitor.visitBuyerCreated();
            case LISTING_REMOVED:
                return visitor.visitListingRemoved();
            case ORDER_CANCELLATION_DECLINED:
                return visitor.visitOrderCancellationDeclined();
            case REPUTATION_EVENT_VOIDED:
                return visitor.visitReputationEventVoided();
            case FLAG_CREATED:
                return visitor.visitFlagCreated();
            case ORDER_CANCELLED:
                return visitor.visitOrderCancelled();
            case PAYMENT_SUCCEEDED:
                return visitor.visitPaymentSucceeded();
            case SELLER_ERASED:
                return visitor.visitSellerErased();
            case DISPUTE_CREATED:
                return visitor.visitDisputeCreated();
            case PAYMENT_CANCELED:
                return visitor.visitPaymentCanceled();
            case DISPUTE_DECISION_OVERDUE:
                return visitor.visitDisputeDecisionOverdue();
            case SELLER_SUSPENDED:
                return visitor.visitSellerSuspended();
            case REPUTATION_EVENT_CREATED:
                return visitor.visitReputationEventCreated();
            case VERIFICATION_CREATED:
                return visitor.visitVerificationCreated();
            case SELLER_PAYOUTS_UPDATED:
                return visitor.visitSellerPayoutsUpdated();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EventObjectType valueOf(String value) {
        switch (value) {
            case "seller.created":
                return SELLER_CREATED;
            case "order.completed":
                return ORDER_COMPLETED;
            case "review.created":
                return REVIEW_CREATED;
            case "category.updated":
                return CATEGORY_UPDATED;
            case "listing.sold":
                return LISTING_SOLD;
            case "payment.released":
                return PAYMENT_RELEASED;
            case "flag.resolved":
                return FLAG_RESOLVED;
            case "listing.updated":
                return LISTING_UPDATED;
            case "media.deleted":
                return MEDIA_DELETED;
            case "listing.unpublished":
                return LISTING_UNPUBLISHED;
            case "order.cancellation_proposed":
                return ORDER_CANCELLATION_PROPOSED;
            case "card_dispute.created":
                return CARD_DISPUTE_CREATED;
            case "listing.published":
                return LISTING_PUBLISHED;
            case "order.disputed":
                return ORDER_DISPUTED;
            case "dispute.decided":
                return DISPUTE_DECIDED;
            case "seller.updated":
                return SELLER_UPDATED;
            case "category.created":
                return CATEGORY_CREATED;
            case "seller.verification_updated":
                return SELLER_VERIFICATION_UPDATED;
            case "listing.created":
                return LISTING_CREATED;
            case "buyer.updated":
                return BUYER_UPDATED;
            case "listing.expired":
                return LISTING_EXPIRED;
            case "payment.release_failed":
                return PAYMENT_RELEASE_FAILED;
            case "order.expired":
                return ORDER_EXPIRED;
            case "card_dispute.updated":
                return CARD_DISPUTE_UPDATED;
            case "order.created":
                return ORDER_CREATED;
            case "payment.failed":
                return PAYMENT_FAILED;
            case "buyer.erased":
                return BUYER_ERASED;
            case "media.ready":
                return MEDIA_READY;
            case "order.claimed":
                return ORDER_CLAIMED;
            case "review.visible":
                return REVIEW_VISIBLE;
            case "refund.updated":
                return REFUND_UPDATED;
            case "dispute.updated":
                return DISPUTE_UPDATED;
            case "payment.refunded":
                return PAYMENT_REFUNDED;
            case "seller.unsuspended":
                return SELLER_UNSUSPENDED;
            case "dispute.evidence_added":
                return DISPUTE_EVIDENCE_ADDED;
            case "review.removed":
                return REVIEW_REMOVED;
            case "order.committed":
                return ORDER_COMMITTED;
            case "verification.updated":
                return VERIFICATION_UPDATED;
            case "moderation_action.created":
                return MODERATION_ACTION_CREATED;
            case "refund.created":
                return REFUND_CREATED;
            case "payment.created":
                return PAYMENT_CREATED;
            case "buyer.created":
                return BUYER_CREATED;
            case "listing.removed":
                return LISTING_REMOVED;
            case "order.cancellation_declined":
                return ORDER_CANCELLATION_DECLINED;
            case "reputation_event.voided":
                return REPUTATION_EVENT_VOIDED;
            case "flag.created":
                return FLAG_CREATED;
            case "order.cancelled":
                return ORDER_CANCELLED;
            case "payment.succeeded":
                return PAYMENT_SUCCEEDED;
            case "seller.erased":
                return SELLER_ERASED;
            case "dispute.created":
                return DISPUTE_CREATED;
            case "payment.canceled":
                return PAYMENT_CANCELED;
            case "dispute.decision_overdue":
                return DISPUTE_DECISION_OVERDUE;
            case "seller.suspended":
                return SELLER_SUSPENDED;
            case "reputation_event.created":
                return REPUTATION_EVENT_CREATED;
            case "verification.created":
                return VERIFICATION_CREATED;
            case "seller.payouts_updated":
                return SELLER_PAYOUTS_UPDATED;
            default:
                return new EventObjectType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SELLER_CREATED,

        SELLER_UPDATED,

        SELLER_ERASED,

        SELLER_SUSPENDED,

        SELLER_UNSUSPENDED,

        SELLER_VERIFICATION_UPDATED,

        SELLER_PAYOUTS_UPDATED,

        BUYER_CREATED,

        BUYER_UPDATED,

        BUYER_ERASED,

        CATEGORY_CREATED,

        CATEGORY_UPDATED,

        LISTING_CREATED,

        LISTING_UPDATED,

        LISTING_PUBLISHED,

        LISTING_UNPUBLISHED,

        LISTING_SOLD,

        LISTING_EXPIRED,

        LISTING_REMOVED,

        MEDIA_READY,

        MEDIA_DELETED,

        ORDER_CREATED,

        ORDER_COMMITTED,

        ORDER_CLAIMED,

        ORDER_CANCELLATION_PROPOSED,

        ORDER_CANCELLATION_DECLINED,

        ORDER_CANCELLED,

        ORDER_EXPIRED,

        ORDER_COMPLETED,

        ORDER_DISPUTED,

        PAYMENT_CREATED,

        PAYMENT_SUCCEEDED,

        PAYMENT_FAILED,

        PAYMENT_CANCELED,

        PAYMENT_REFUNDED,

        PAYMENT_RELEASED,

        PAYMENT_RELEASE_FAILED,

        REFUND_CREATED,

        REFUND_UPDATED,

        VERIFICATION_CREATED,

        VERIFICATION_UPDATED,

        REVIEW_CREATED,

        REVIEW_VISIBLE,

        REVIEW_REMOVED,

        REPUTATION_EVENT_CREATED,

        REPUTATION_EVENT_VOIDED,

        DISPUTE_CREATED,

        DISPUTE_EVIDENCE_ADDED,

        DISPUTE_UPDATED,

        DISPUTE_DECISION_OVERDUE,

        DISPUTE_DECIDED,

        CARD_DISPUTE_CREATED,

        CARD_DISPUTE_UPDATED,

        FLAG_CREATED,

        FLAG_RESOLVED,

        MODERATION_ACTION_CREATED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSellerCreated();

        T visitSellerUpdated();

        T visitSellerErased();

        T visitSellerSuspended();

        T visitSellerUnsuspended();

        T visitSellerVerificationUpdated();

        T visitSellerPayoutsUpdated();

        T visitBuyerCreated();

        T visitBuyerUpdated();

        T visitBuyerErased();

        T visitCategoryCreated();

        T visitCategoryUpdated();

        T visitListingCreated();

        T visitListingUpdated();

        T visitListingPublished();

        T visitListingUnpublished();

        T visitListingSold();

        T visitListingExpired();

        T visitListingRemoved();

        T visitMediaReady();

        T visitMediaDeleted();

        T visitOrderCreated();

        T visitOrderCommitted();

        T visitOrderClaimed();

        T visitOrderCancellationProposed();

        T visitOrderCancellationDeclined();

        T visitOrderCancelled();

        T visitOrderExpired();

        T visitOrderCompleted();

        T visitOrderDisputed();

        T visitPaymentCreated();

        T visitPaymentSucceeded();

        T visitPaymentFailed();

        T visitPaymentCanceled();

        T visitPaymentRefunded();

        T visitPaymentReleased();

        T visitPaymentReleaseFailed();

        T visitRefundCreated();

        T visitRefundUpdated();

        T visitVerificationCreated();

        T visitVerificationUpdated();

        T visitReviewCreated();

        T visitReviewVisible();

        T visitReviewRemoved();

        T visitReputationEventCreated();

        T visitReputationEventVoided();

        T visitDisputeCreated();

        T visitDisputeEvidenceAdded();

        T visitDisputeUpdated();

        T visitDisputeDecisionOverdue();

        T visitDisputeDecided();

        T visitCardDisputeCreated();

        T visitCardDisputeUpdated();

        T visitFlagCreated();

        T visitFlagResolved();

        T visitModerationActionCreated();

        T visitUnknown(String unknownType);
    }
}
