/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class FlagObjectReason {
    public static final FlagObjectReason OFFENSIVE = new FlagObjectReason(Value.OFFENSIVE, "offensive");

    public static final FlagObjectReason OTHER = new FlagObjectReason(Value.OTHER, "other");

    public static final FlagObjectReason PROHIBITED_ITEM =
            new FlagObjectReason(Value.PROHIBITED_ITEM, "prohibited_item");

    public static final FlagObjectReason SCAM = new FlagObjectReason(Value.SCAM, "scam");

    public static final FlagObjectReason SPAM = new FlagObjectReason(Value.SPAM, "spam");

    public static final FlagObjectReason COUNTERFEIT = new FlagObjectReason(Value.COUNTERFEIT, "counterfeit");

    private final Value value;

    private final String string;

    FlagObjectReason(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof FlagObjectReason && this.string.equals(((FlagObjectReason) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case OFFENSIVE:
                return visitor.visitOffensive();
            case OTHER:
                return visitor.visitOther();
            case PROHIBITED_ITEM:
                return visitor.visitProhibitedItem();
            case SCAM:
                return visitor.visitScam();
            case SPAM:
                return visitor.visitSpam();
            case COUNTERFEIT:
                return visitor.visitCounterfeit();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static FlagObjectReason valueOf(String value) {
        switch (value) {
            case "offensive":
                return OFFENSIVE;
            case "other":
                return OTHER;
            case "prohibited_item":
                return PROHIBITED_ITEM;
            case "scam":
                return SCAM;
            case "spam":
                return SPAM;
            case "counterfeit":
                return COUNTERFEIT;
            default:
                return new FlagObjectReason(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PROHIBITED_ITEM,

        COUNTERFEIT,

        SCAM,

        OFFENSIVE,

        SPAM,

        OTHER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitProhibitedItem();

        T visitCounterfeit();

        T visitScam();

        T visitOffensive();

        T visitSpam();

        T visitOther();

        T visitUnknown(String unknownType);
    }
}
