/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.Nullable;
import com.marketsdk.core.NullableNonemptyFilter;
import com.marketsdk.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MarketplaceObject.Builder.class)
public final class MarketplaceObject {
    private final MarketplaceObjectObject object;

    private final String id;

    private final MarketplaceObjectMode mode;

    private final Optional<String> description;

    private final String currency;

    private final boolean payments;

    private final boolean sellerVerification;

    private final boolean holdFundsUntilCompletion;

    private final FeeSettingsDto fee;

    private final TimerSettingsDto timers;

    private final ReputationSettingsDto reputation;

    private final DisputeSettingsDto disputes;

    private final ModerationSettingsDto moderation;

    private final List<String> allowedOrigins;

    private final Optional<ReadOnlyObject> readOnly;

    private final Map<String, Object> additionalProperties;

    private MarketplaceObject(
            MarketplaceObjectObject object,
            String id,
            MarketplaceObjectMode mode,
            Optional<String> description,
            String currency,
            boolean payments,
            boolean sellerVerification,
            boolean holdFundsUntilCompletion,
            FeeSettingsDto fee,
            TimerSettingsDto timers,
            ReputationSettingsDto reputation,
            DisputeSettingsDto disputes,
            ModerationSettingsDto moderation,
            List<String> allowedOrigins,
            Optional<ReadOnlyObject> readOnly,
            Map<String, Object> additionalProperties) {
        this.object = object;
        this.id = id;
        this.mode = mode;
        this.description = description;
        this.currency = currency;
        this.payments = payments;
        this.sellerVerification = sellerVerification;
        this.holdFundsUntilCompletion = holdFundsUntilCompletion;
        this.fee = fee;
        this.timers = timers;
        this.reputation = reputation;
        this.disputes = disputes;
        this.moderation = moderation;
        this.allowedOrigins = allowedOrigins;
        this.readOnly = readOnly;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("object")
    public MarketplaceObjectObject getObject() {
        return object;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("mode")
    public MarketplaceObjectMode getMode() {
        return mode;
    }

    @JsonIgnore
    public Optional<String> getDescription() {
        if (description == null) {
            return Optional.empty();
        }
        return description;
    }

    @JsonProperty("currency")
    public String getCurrency() {
        return currency;
    }

    @JsonProperty("payments")
    public boolean getPayments() {
        return payments;
    }

    @JsonProperty("seller_verification")
    public boolean getSellerVerification() {
        return sellerVerification;
    }

    @JsonProperty("hold_funds_until_completion")
    public boolean getHoldFundsUntilCompletion() {
        return holdFundsUntilCompletion;
    }

    @JsonProperty("fee")
    public FeeSettingsDto getFee() {
        return fee;
    }

    @JsonProperty("timers")
    public TimerSettingsDto getTimers() {
        return timers;
    }

    @JsonProperty("reputation")
    public ReputationSettingsDto getReputation() {
        return reputation;
    }

    @JsonProperty("disputes")
    public DisputeSettingsDto getDisputes() {
        return disputes;
    }

    @JsonProperty("moderation")
    public ModerationSettingsDto getModeration() {
        return moderation;
    }

    @JsonProperty("allowed_origins")
    public List<String> getAllowedOrigins() {
        return allowedOrigins;
    }

    /**
     * @return Set while the marketplace answers reads only, for example after a missed payment. Changes are refused with 403 <code>marketplace_read_only</code>. Null when open.
     */
    @JsonIgnore
    public Optional<ReadOnlyObject> getReadOnly() {
        if (readOnly == null) {
            return Optional.empty();
        }
        return readOnly;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("description")
    private Optional<String> _getDescription() {
        return description;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("read_only")
    private Optional<ReadOnlyObject> _getReadOnly() {
        return readOnly;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MarketplaceObject && equalTo((MarketplaceObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MarketplaceObject other) {
        return object.equals(other.object)
                && id.equals(other.id)
                && mode.equals(other.mode)
                && description.equals(other.description)
                && currency.equals(other.currency)
                && payments == other.payments
                && sellerVerification == other.sellerVerification
                && holdFundsUntilCompletion == other.holdFundsUntilCompletion
                && fee.equals(other.fee)
                && timers.equals(other.timers)
                && reputation.equals(other.reputation)
                && disputes.equals(other.disputes)
                && moderation.equals(other.moderation)
                && allowedOrigins.equals(other.allowedOrigins)
                && readOnly.equals(other.readOnly);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.object,
                this.id,
                this.mode,
                this.description,
                this.currency,
                this.payments,
                this.sellerVerification,
                this.holdFundsUntilCompletion,
                this.fee,
                this.timers,
                this.reputation,
                this.disputes,
                this.moderation,
                this.allowedOrigins,
                this.readOnly);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ObjectStage builder() {
        return new Builder();
    }

    public interface ObjectStage {
        IdStage object(@NotNull MarketplaceObjectObject object);

        Builder from(MarketplaceObject other);
    }

    public interface IdStage {
        ModeStage id(@NotNull String id);
    }

    public interface ModeStage {
        CurrencyStage mode(@NotNull MarketplaceObjectMode mode);
    }

    public interface CurrencyStage {
        PaymentsStage currency(@NotNull String currency);
    }

    public interface PaymentsStage {
        SellerVerificationStage payments(boolean payments);
    }

    public interface SellerVerificationStage {
        HoldFundsUntilCompletionStage sellerVerification(boolean sellerVerification);
    }

    public interface HoldFundsUntilCompletionStage {
        FeeStage holdFundsUntilCompletion(boolean holdFundsUntilCompletion);
    }

    public interface FeeStage {
        TimersStage fee(@NotNull FeeSettingsDto fee);
    }

    public interface TimersStage {
        ReputationStage timers(@NotNull TimerSettingsDto timers);
    }

    public interface ReputationStage {
        DisputesStage reputation(@NotNull ReputationSettingsDto reputation);
    }

    public interface DisputesStage {
        ModerationStage disputes(@NotNull DisputeSettingsDto disputes);
    }

    public interface ModerationStage {
        _FinalStage moderation(@NotNull ModerationSettingsDto moderation);
    }

    public interface _FinalStage {
        MarketplaceObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        _FinalStage description(Nullable<String> description);

        _FinalStage allowedOrigins(List<String> allowedOrigins);

        _FinalStage addAllowedOrigins(String allowedOrigins);

        _FinalStage addAllAllowedOrigins(List<String> allowedOrigins);

        /**
         * <p>Set while the marketplace answers reads only, for example after a missed payment. Changes are refused with 403 <code>marketplace_read_only</code>. Null when open.</p>
         */
        _FinalStage readOnly(Optional<ReadOnlyObject> readOnly);

        _FinalStage readOnly(ReadOnlyObject readOnly);

        _FinalStage readOnly(Nullable<ReadOnlyObject> readOnly);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ObjectStage,
                    IdStage,
                    ModeStage,
                    CurrencyStage,
                    PaymentsStage,
                    SellerVerificationStage,
                    HoldFundsUntilCompletionStage,
                    FeeStage,
                    TimersStage,
                    ReputationStage,
                    DisputesStage,
                    ModerationStage,
                    _FinalStage {
        private MarketplaceObjectObject object;

        private String id;

        private MarketplaceObjectMode mode;

        private String currency;

        private boolean payments;

        private boolean sellerVerification;

        private boolean holdFundsUntilCompletion;

        private FeeSettingsDto fee;

        private TimerSettingsDto timers;

        private ReputationSettingsDto reputation;

        private DisputeSettingsDto disputes;

        private ModerationSettingsDto moderation;

        private Optional<ReadOnlyObject> readOnly = Optional.empty();

        private List<String> allowedOrigins = new ArrayList<>();

        private Optional<String> description = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MarketplaceObject other) {
            object(other.getObject());
            id(other.getId());
            mode(other.getMode());
            description(other.getDescription());
            currency(other.getCurrency());
            payments(other.getPayments());
            sellerVerification(other.getSellerVerification());
            holdFundsUntilCompletion(other.getHoldFundsUntilCompletion());
            fee(other.getFee());
            timers(other.getTimers());
            reputation(other.getReputation());
            disputes(other.getDisputes());
            moderation(other.getModeration());
            allowedOrigins(other.getAllowedOrigins());
            readOnly(other.getReadOnly());
            return this;
        }

        @java.lang.Override
        @JsonSetter("object")
        public IdStage object(@NotNull MarketplaceObjectObject object) {
            this.object = Objects.requireNonNull(object, "object must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public ModeStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("mode")
        public CurrencyStage mode(@NotNull MarketplaceObjectMode mode) {
            this.mode = Objects.requireNonNull(mode, "mode must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("currency")
        public PaymentsStage currency(@NotNull String currency) {
            this.currency = Objects.requireNonNull(currency, "currency must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("payments")
        public SellerVerificationStage payments(boolean payments) {
            this.payments = payments;
            return this;
        }

        @java.lang.Override
        @JsonSetter("seller_verification")
        public HoldFundsUntilCompletionStage sellerVerification(boolean sellerVerification) {
            this.sellerVerification = sellerVerification;
            return this;
        }

        @java.lang.Override
        @JsonSetter("hold_funds_until_completion")
        public FeeStage holdFundsUntilCompletion(boolean holdFundsUntilCompletion) {
            this.holdFundsUntilCompletion = holdFundsUntilCompletion;
            return this;
        }

        @java.lang.Override
        @JsonSetter("fee")
        public TimersStage fee(@NotNull FeeSettingsDto fee) {
            this.fee = Objects.requireNonNull(fee, "fee must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("timers")
        public ReputationStage timers(@NotNull TimerSettingsDto timers) {
            this.timers = Objects.requireNonNull(timers, "timers must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("reputation")
        public DisputesStage reputation(@NotNull ReputationSettingsDto reputation) {
            this.reputation = Objects.requireNonNull(reputation, "reputation must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("disputes")
        public ModerationStage disputes(@NotNull DisputeSettingsDto disputes) {
            this.disputes = Objects.requireNonNull(disputes, "disputes must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("moderation")
        public _FinalStage moderation(@NotNull ModerationSettingsDto moderation) {
            this.moderation = Objects.requireNonNull(moderation, "moderation must not be null");
            return this;
        }

        /**
         * <p>Set while the marketplace answers reads only, for example after a missed payment. Changes are refused with 403 <code>marketplace_read_only</code>. Null when open.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage readOnly(Nullable<ReadOnlyObject> readOnly) {
            if (readOnly.isNull()) {
                this.readOnly = null;
            } else if (readOnly.isEmpty()) {
                this.readOnly = Optional.empty();
            } else {
                this.readOnly = Optional.of(readOnly.get());
            }
            return this;
        }

        /**
         * <p>Set while the marketplace answers reads only, for example after a missed payment. Changes are refused with 403 <code>marketplace_read_only</code>. Null when open.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage readOnly(ReadOnlyObject readOnly) {
            this.readOnly = Optional.ofNullable(readOnly);
            return this;
        }

        /**
         * <p>Set while the marketplace answers reads only, for example after a missed payment. Changes are refused with 403 <code>marketplace_read_only</code>. Null when open.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "read_only", nulls = Nulls.SKIP)
        public _FinalStage readOnly(Optional<ReadOnlyObject> readOnly) {
            this.readOnly = readOnly;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllAllowedOrigins(List<String> allowedOrigins) {
            if (allowedOrigins != null) {
                this.allowedOrigins.addAll(allowedOrigins);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllowedOrigins(String allowedOrigins) {
            this.allowedOrigins.add(allowedOrigins);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "allowed_origins", nulls = Nulls.SKIP)
        public _FinalStage allowedOrigins(List<String> allowedOrigins) {
            this.allowedOrigins.clear();
            if (allowedOrigins != null) {
                this.allowedOrigins.addAll(allowedOrigins);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage description(Nullable<String> description) {
            if (description.isNull()) {
                this.description = null;
            } else if (description.isEmpty()) {
                this.description = Optional.empty();
            } else {
                this.description = Optional.of(description.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        @java.lang.Override
        public MarketplaceObject build() {
            return new MarketplaceObject(
                    object,
                    id,
                    mode,
                    description,
                    currency,
                    payments,
                    sellerVerification,
                    holdFundsUntilCompletion,
                    fee,
                    timers,
                    reputation,
                    disputes,
                    moderation,
                    allowedOrigins,
                    readOnly,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
