/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MediaUploadObject.Builder.class)
public final class MediaUploadObject {
    private final MediaObject media;

    private final String uploadUrl;

    private final OffsetDateTime uploadExpiresAt;

    private final Map<String, Object> additionalProperties;

    private MediaUploadObject(
            MediaObject media,
            String uploadUrl,
            OffsetDateTime uploadExpiresAt,
            Map<String, Object> additionalProperties) {
        this.media = media;
        this.uploadUrl = uploadUrl;
        this.uploadExpiresAt = uploadExpiresAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("media")
    public MediaObject getMedia() {
        return media;
    }

    /**
     * @return PUT the file here, with the same Content-Type, within 10 minutes. Then complete the upload.
     */
    @JsonProperty("upload_url")
    public String getUploadUrl() {
        return uploadUrl;
    }

    @JsonProperty("upload_expires_at")
    public OffsetDateTime getUploadExpiresAt() {
        return uploadExpiresAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MediaUploadObject && equalTo((MediaUploadObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MediaUploadObject other) {
        return media.equals(other.media)
                && uploadUrl.equals(other.uploadUrl)
                && uploadExpiresAt.equals(other.uploadExpiresAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.media, this.uploadUrl, this.uploadExpiresAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MediaStage builder() {
        return new Builder();
    }

    public interface MediaStage {
        UploadUrlStage media(@NotNull MediaObject media);

        Builder from(MediaUploadObject other);
    }

    public interface UploadUrlStage {
        /**
         * <p>PUT the file here, with the same Content-Type, within 10 minutes. Then complete the upload.</p>
         */
        UploadExpiresAtStage uploadUrl(@NotNull String uploadUrl);
    }

    public interface UploadExpiresAtStage {
        _FinalStage uploadExpiresAt(@NotNull OffsetDateTime uploadExpiresAt);
    }

    public interface _FinalStage {
        MediaUploadObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MediaStage, UploadUrlStage, UploadExpiresAtStage, _FinalStage {
        private MediaObject media;

        private String uploadUrl;

        private OffsetDateTime uploadExpiresAt;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MediaUploadObject other) {
            media(other.getMedia());
            uploadUrl(other.getUploadUrl());
            uploadExpiresAt(other.getUploadExpiresAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("media")
        public UploadUrlStage media(@NotNull MediaObject media) {
            this.media = Objects.requireNonNull(media, "media must not be null");
            return this;
        }

        /**
         * <p>PUT the file here, with the same Content-Type, within 10 minutes. Then complete the upload.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("upload_url")
        public UploadExpiresAtStage uploadUrl(@NotNull String uploadUrl) {
            this.uploadUrl = Objects.requireNonNull(uploadUrl, "uploadUrl must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("upload_expires_at")
        public _FinalStage uploadExpiresAt(@NotNull OffsetDateTime uploadExpiresAt) {
            this.uploadExpiresAt = Objects.requireNonNull(uploadExpiresAt, "uploadExpiresAt must not be null");
            return this;
        }

        @java.lang.Override
        public MediaUploadObject build() {
            return new MediaUploadObject(media, uploadUrl, uploadExpiresAt, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
