/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.Nullable;
import com.marketsdk.core.NullableNonemptyFilter;
import com.marketsdk.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MediaObject.Builder.class)
public final class MediaObject {
    private final MediaObjectObject object;

    private final String id;

    private final String listing;

    private final MediaObjectStatus status;

    private final String contentType;

    private final double sizeBytes;

    private final double position;

    private final Optional<String> url;

    private final Optional<OffsetDateTime> urlExpiresAt;

    private final OffsetDateTime createdAt;

    private final Map<String, Object> additionalProperties;

    private MediaObject(
            MediaObjectObject object,
            String id,
            String listing,
            MediaObjectStatus status,
            String contentType,
            double sizeBytes,
            double position,
            Optional<String> url,
            Optional<OffsetDateTime> urlExpiresAt,
            OffsetDateTime createdAt,
            Map<String, Object> additionalProperties) {
        this.object = object;
        this.id = id;
        this.listing = listing;
        this.status = status;
        this.contentType = contentType;
        this.sizeBytes = sizeBytes;
        this.position = position;
        this.url = url;
        this.urlExpiresAt = urlExpiresAt;
        this.createdAt = createdAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("object")
    public MediaObjectObject getObject() {
        return object;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("listing")
    public String getListing() {
        return listing;
    }

    @JsonProperty("status")
    public MediaObjectStatus getStatus() {
        return status;
    }

    @JsonProperty("content_type")
    public String getContentType() {
        return contentType;
    }

    @JsonProperty("size_bytes")
    public double getSizeBytes() {
        return sizeBytes;
    }

    @JsonProperty("position")
    public double getPosition() {
        return position;
    }

    /**
     * @return A signed link to the file, valid for an hour. Null until the upload completes.
     */
    @JsonIgnore
    public Optional<String> getUrl() {
        if (url == null) {
            return Optional.empty();
        }
        return url;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getUrlExpiresAt() {
        if (urlExpiresAt == null) {
            return Optional.empty();
        }
        return urlExpiresAt;
    }

    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("url")
    private Optional<String> _getUrl() {
        return url;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("url_expires_at")
    private Optional<OffsetDateTime> _getUrlExpiresAt() {
        return urlExpiresAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MediaObject && equalTo((MediaObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MediaObject other) {
        return object.equals(other.object)
                && id.equals(other.id)
                && listing.equals(other.listing)
                && status.equals(other.status)
                && contentType.equals(other.contentType)
                && sizeBytes == other.sizeBytes
                && position == other.position
                && url.equals(other.url)
                && urlExpiresAt.equals(other.urlExpiresAt)
                && createdAt.equals(other.createdAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.object,
                this.id,
                this.listing,
                this.status,
                this.contentType,
                this.sizeBytes,
                this.position,
                this.url,
                this.urlExpiresAt,
                this.createdAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ObjectStage builder() {
        return new Builder();
    }

    public interface ObjectStage {
        IdStage object(@NotNull MediaObjectObject object);

        Builder from(MediaObject other);
    }

    public interface IdStage {
        ListingStage id(@NotNull String id);
    }

    public interface ListingStage {
        StatusStage listing(@NotNull String listing);
    }

    public interface StatusStage {
        ContentTypeStage status(@NotNull MediaObjectStatus status);
    }

    public interface ContentTypeStage {
        SizeBytesStage contentType(@NotNull String contentType);
    }

    public interface SizeBytesStage {
        PositionStage sizeBytes(double sizeBytes);
    }

    public interface PositionStage {
        CreatedAtStage position(double position);
    }

    public interface CreatedAtStage {
        _FinalStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface _FinalStage {
        MediaObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>A signed link to the file, valid for an hour. Null until the upload completes.</p>
         */
        _FinalStage url(Optional<String> url);

        _FinalStage url(String url);

        _FinalStage url(Nullable<String> url);

        _FinalStage urlExpiresAt(Optional<OffsetDateTime> urlExpiresAt);

        _FinalStage urlExpiresAt(OffsetDateTime urlExpiresAt);

        _FinalStage urlExpiresAt(Nullable<OffsetDateTime> urlExpiresAt);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ObjectStage,
                    IdStage,
                    ListingStage,
                    StatusStage,
                    ContentTypeStage,
                    SizeBytesStage,
                    PositionStage,
                    CreatedAtStage,
                    _FinalStage {
        private MediaObjectObject object;

        private String id;

        private String listing;

        private MediaObjectStatus status;

        private String contentType;

        private double sizeBytes;

        private double position;

        private OffsetDateTime createdAt;

        private Optional<OffsetDateTime> urlExpiresAt = Optional.empty();

        private Optional<String> url = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MediaObject other) {
            object(other.getObject());
            id(other.getId());
            listing(other.getListing());
            status(other.getStatus());
            contentType(other.getContentType());
            sizeBytes(other.getSizeBytes());
            position(other.getPosition());
            url(other.getUrl());
            urlExpiresAt(other.getUrlExpiresAt());
            createdAt(other.getCreatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("object")
        public IdStage object(@NotNull MediaObjectObject object) {
            this.object = Objects.requireNonNull(object, "object must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public ListingStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("listing")
        public StatusStage listing(@NotNull String listing) {
            this.listing = Objects.requireNonNull(listing, "listing must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public ContentTypeStage status(@NotNull MediaObjectStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("content_type")
        public SizeBytesStage contentType(@NotNull String contentType) {
            this.contentType = Objects.requireNonNull(contentType, "contentType must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("size_bytes")
        public PositionStage sizeBytes(double sizeBytes) {
            this.sizeBytes = sizeBytes;
            return this;
        }

        @java.lang.Override
        @JsonSetter("position")
        public CreatedAtStage position(double position) {
            this.position = position;
            return this;
        }

        @java.lang.Override
        @JsonSetter("created_at")
        public _FinalStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage urlExpiresAt(Nullable<OffsetDateTime> urlExpiresAt) {
            if (urlExpiresAt.isNull()) {
                this.urlExpiresAt = null;
            } else if (urlExpiresAt.isEmpty()) {
                this.urlExpiresAt = Optional.empty();
            } else {
                this.urlExpiresAt = Optional.of(urlExpiresAt.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage urlExpiresAt(OffsetDateTime urlExpiresAt) {
            this.urlExpiresAt = Optional.ofNullable(urlExpiresAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "url_expires_at", nulls = Nulls.SKIP)
        public _FinalStage urlExpiresAt(Optional<OffsetDateTime> urlExpiresAt) {
            this.urlExpiresAt = urlExpiresAt;
            return this;
        }

        /**
         * <p>A signed link to the file, valid for an hour. Null until the upload completes.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage url(Nullable<String> url) {
            if (url.isNull()) {
                this.url = null;
            } else if (url.isEmpty()) {
                this.url = Optional.empty();
            } else {
                this.url = Optional.of(url.get());
            }
            return this;
        }

        /**
         * <p>A signed link to the file, valid for an hour. Null until the upload completes.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage url(String url) {
            this.url = Optional.ofNullable(url);
            return this;
        }

        /**
         * <p>A signed link to the file, valid for an hour. Null until the upload completes.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "url", nulls = Nulls.SKIP)
        public _FinalStage url(Optional<String> url) {
            this.url = url;
            return this;
        }

        @java.lang.Override
        public MediaObject build() {
            return new MediaObject(
                    object,
                    id,
                    listing,
                    status,
                    contentType,
                    sizeBytes,
                    position,
                    url,
                    urlExpiresAt,
                    createdAt,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
