/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class OrderPaymentObjectReleaseStatus {
    public static final OrderPaymentObjectReleaseStatus FAILED =
            new OrderPaymentObjectReleaseStatus(Value.FAILED, "failed");

    public static final OrderPaymentObjectReleaseStatus HELD = new OrderPaymentObjectReleaseStatus(Value.HELD, "held");

    public static final OrderPaymentObjectReleaseStatus NOTHING_TO_RELEASE =
            new OrderPaymentObjectReleaseStatus(Value.NOTHING_TO_RELEASE, "nothing_to_release");

    public static final OrderPaymentObjectReleaseStatus RELEASED =
            new OrderPaymentObjectReleaseStatus(Value.RELEASED, "released");

    public static final OrderPaymentObjectReleaseStatus RELEASING =
            new OrderPaymentObjectReleaseStatus(Value.RELEASING, "releasing");

    private final Value value;

    private final String string;

    OrderPaymentObjectReleaseStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof OrderPaymentObjectReleaseStatus
                        && this.string.equals(((OrderPaymentObjectReleaseStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case FAILED:
                return visitor.visitFailed();
            case HELD:
                return visitor.visitHeld();
            case NOTHING_TO_RELEASE:
                return visitor.visitNothingToRelease();
            case RELEASED:
                return visitor.visitReleased();
            case RELEASING:
                return visitor.visitReleasing();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static OrderPaymentObjectReleaseStatus valueOf(String value) {
        switch (value) {
            case "failed":
                return FAILED;
            case "held":
                return HELD;
            case "nothing_to_release":
                return NOTHING_TO_RELEASE;
            case "released":
                return RELEASED;
            case "releasing":
                return RELEASING;
            default:
                return new OrderPaymentObjectReleaseStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        HELD,

        RELEASING,

        RELEASED,

        FAILED,

        NOTHING_TO_RELEASE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitHeld();

        T visitReleasing();

        T visitReleased();

        T visitFailed();

        T visitNothingToRelease();

        T visitUnknown(String unknownType);
    }
}
