/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrderPriceObject.Builder.class)
public final class OrderPriceObject {
    private final double unitAmount;

    private final double amount;

    private final String currency;

    private final Map<String, Object> additionalProperties;

    private OrderPriceObject(
            double unitAmount, double amount, String currency, Map<String, Object> additionalProperties) {
        this.unitAmount = unitAmount;
        this.amount = amount;
        this.currency = currency;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Per unit, fixed when the order was created. Minor units.
     */
    @JsonProperty("unit_amount")
    public double getUnitAmount() {
        return unitAmount;
    }

    /**
     * @return unit_amount times quantity. Minor units.
     */
    @JsonProperty("amount")
    public double getAmount() {
        return amount;
    }

    @JsonProperty("currency")
    public String getCurrency() {
        return currency;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrderPriceObject && equalTo((OrderPriceObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrderPriceObject other) {
        return unitAmount == other.unitAmount && amount == other.amount && currency.equals(other.currency);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.unitAmount, this.amount, this.currency);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static UnitAmountStage builder() {
        return new Builder();
    }

    public interface UnitAmountStage {
        /**
         * <p>Per unit, fixed when the order was created. Minor units.</p>
         */
        AmountStage unitAmount(double unitAmount);

        Builder from(OrderPriceObject other);
    }

    public interface AmountStage {
        /**
         * <p>unit_amount times quantity. Minor units.</p>
         */
        CurrencyStage amount(double amount);
    }

    public interface CurrencyStage {
        _FinalStage currency(@NotNull String currency);
    }

    public interface _FinalStage {
        OrderPriceObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements UnitAmountStage, AmountStage, CurrencyStage, _FinalStage {
        private double unitAmount;

        private double amount;

        private String currency;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(OrderPriceObject other) {
            unitAmount(other.getUnitAmount());
            amount(other.getAmount());
            currency(other.getCurrency());
            return this;
        }

        /**
         * <p>Per unit, fixed when the order was created. Minor units.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("unit_amount")
        public AmountStage unitAmount(double unitAmount) {
            this.unitAmount = unitAmount;
            return this;
        }

        /**
         * <p>unit_amount times quantity. Minor units.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("amount")
        public CurrencyStage amount(double amount) {
            this.amount = amount;
            return this;
        }

        @java.lang.Override
        @JsonSetter("currency")
        public _FinalStage currency(@NotNull String currency) {
            this.currency = Objects.requireNonNull(currency, "currency must not be null");
            return this;
        }

        @java.lang.Override
        public OrderPriceObject build() {
            return new OrderPriceObject(unitAmount, amount, currency, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
