/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class OrderObjectState {
    public static final OrderObjectState COMMITTED = new OrderObjectState(Value.COMMITTED, "committed");

    public static final OrderObjectState COMPLETED = new OrderObjectState(Value.COMPLETED, "completed");

    public static final OrderObjectState AWAITING_PAYMENT =
            new OrderObjectState(Value.AWAITING_PAYMENT, "awaiting_payment");

    public static final OrderObjectState EXPIRED = new OrderObjectState(Value.EXPIRED, "expired");

    public static final OrderObjectState CANCELLED = new OrderObjectState(Value.CANCELLED, "cancelled");

    public static final OrderObjectState CLAIMED = new OrderObjectState(Value.CLAIMED, "claimed");

    public static final OrderObjectState DISPUTED = new OrderObjectState(Value.DISPUTED, "disputed");

    private final Value value;

    private final String string;

    OrderObjectState(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof OrderObjectState && this.string.equals(((OrderObjectState) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case COMMITTED:
                return visitor.visitCommitted();
            case COMPLETED:
                return visitor.visitCompleted();
            case AWAITING_PAYMENT:
                return visitor.visitAwaitingPayment();
            case EXPIRED:
                return visitor.visitExpired();
            case CANCELLED:
                return visitor.visitCancelled();
            case CLAIMED:
                return visitor.visitClaimed();
            case DISPUTED:
                return visitor.visitDisputed();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static OrderObjectState valueOf(String value) {
        switch (value) {
            case "committed":
                return COMMITTED;
            case "completed":
                return COMPLETED;
            case "awaiting_payment":
                return AWAITING_PAYMENT;
            case "expired":
                return EXPIRED;
            case "cancelled":
                return CANCELLED;
            case "claimed":
                return CLAIMED;
            case "disputed":
                return DISPUTED;
            default:
                return new OrderObjectState(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        AWAITING_PAYMENT,

        COMMITTED,

        CLAIMED,

        DISPUTED,

        COMPLETED,

        CANCELLED,

        EXPIRED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAwaitingPayment();

        T visitCommitted();

        T visitClaimed();

        T visitDisputed();

        T visitCompleted();

        T visitCancelled();

        T visitExpired();

        T visitUnknown(String unknownType);
    }
}
