/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PaymentObjectMethod {
    public static final PaymentObjectMethod PAYMENT_INTENT =
            new PaymentObjectMethod(Value.PAYMENT_INTENT, "payment_intent");

    public static final PaymentObjectMethod CHECKOUT_SESSION =
            new PaymentObjectMethod(Value.CHECKOUT_SESSION, "checkout_session");

    private final Value value;

    private final String string;

    PaymentObjectMethod(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PaymentObjectMethod && this.string.equals(((PaymentObjectMethod) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PAYMENT_INTENT:
                return visitor.visitPaymentIntent();
            case CHECKOUT_SESSION:
                return visitor.visitCheckoutSession();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PaymentObjectMethod valueOf(String value) {
        switch (value) {
            case "payment_intent":
                return PAYMENT_INTENT;
            case "checkout_session":
                return CHECKOUT_SESSION;
            default:
                return new PaymentObjectMethod(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CHECKOUT_SESSION,

        PAYMENT_INTENT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCheckoutSession();

        T visitPaymentIntent();

        T visitUnknown(String unknownType);
    }
}
