/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.Nullable;
import com.marketsdk.core.NullableNonemptyFilter;
import com.marketsdk.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PaymentObject.Builder.class)
public final class PaymentObject {
    private final PaymentObjectObject object;

    private final String id;

    private final String order;

    private final PaymentObjectMethod method;

    private final PaymentObjectStatus status;

    private final double amount;

    private final double feeAmount;

    private final String currency;

    private final Optional<String> checkoutUrl;

    private final Optional<String> clientSecret;

    private final Optional<String> lastFailure;

    private final double amountRefunded;

    private final PaymentReleaseObject release;

    private final PaymentStripeObject stripe;

    private final Map<String, String> metadata;

    private final Optional<OffsetDateTime> paidAt;

    private final Optional<OffsetDateTime> canceledAt;

    private final OffsetDateTime createdAt;

    private final OffsetDateTime updatedAt;

    private final Map<String, Object> additionalProperties;

    private PaymentObject(
            PaymentObjectObject object,
            String id,
            String order,
            PaymentObjectMethod method,
            PaymentObjectStatus status,
            double amount,
            double feeAmount,
            String currency,
            Optional<String> checkoutUrl,
            Optional<String> clientSecret,
            Optional<String> lastFailure,
            double amountRefunded,
            PaymentReleaseObject release,
            PaymentStripeObject stripe,
            Map<String, String> metadata,
            Optional<OffsetDateTime> paidAt,
            Optional<OffsetDateTime> canceledAt,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt,
            Map<String, Object> additionalProperties) {
        this.object = object;
        this.id = id;
        this.order = order;
        this.method = method;
        this.status = status;
        this.amount = amount;
        this.feeAmount = feeAmount;
        this.currency = currency;
        this.checkoutUrl = checkoutUrl;
        this.clientSecret = clientSecret;
        this.lastFailure = lastFailure;
        this.amountRefunded = amountRefunded;
        this.release = release;
        this.stripe = stripe;
        this.metadata = metadata;
        this.paidAt = paidAt;
        this.canceledAt = canceledAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("object")
    public PaymentObjectObject getObject() {
        return object;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("order")
    public String getOrder() {
        return order;
    }

    @JsonProperty("method")
    public PaymentObjectMethod getMethod() {
        return method;
    }

    @JsonProperty("status")
    public PaymentObjectStatus getStatus() {
        return status;
    }

    /**
     * @return Minor units.
     */
    @JsonProperty("amount")
    public double getAmount() {
        return amount;
    }

    /**
     * @return The customer's platform fee. Minor units.
     */
    @JsonProperty("fee_amount")
    public double getFeeAmount() {
        return feeAmount;
    }

    @JsonProperty("currency")
    public String getCurrency() {
        return currency;
    }

    /**
     * @return Stripe-hosted checkout. Shown only while payment is due.
     */
    @JsonIgnore
    public Optional<String> getCheckoutUrl() {
        if (checkoutUrl == null) {
            return Optional.empty();
        }
        return checkoutUrl;
    }

    /**
     * @return For Stripe Elements on your own page. Shown only while payment is due.
     */
    @JsonIgnore
    public Optional<String> getClientSecret() {
        if (clientSecret == null) {
            return Optional.empty();
        }
        return clientSecret;
    }

    /**
     * @return Stripe's message for the last failed attempt to pay.
     */
    @JsonIgnore
    public Optional<String> getLastFailure() {
        if (lastFailure == null) {
            return Optional.empty();
        }
        return lastFailure;
    }

    /**
     * @return Refunded or being refunded. Minor units.
     */
    @JsonProperty("amount_refunded")
    public double getAmountRefunded() {
        return amountRefunded;
    }

    @JsonProperty("release")
    public PaymentReleaseObject getRelease() {
        return release;
    }

    /**
     * @return Ids of the objects on your Stripe account.
     */
    @JsonProperty("stripe")
    public PaymentStripeObject getStripe() {
        return stripe;
    }

    @JsonProperty("metadata")
    public Map<String, String> getMetadata() {
        return metadata;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getPaidAt() {
        if (paidAt == null) {
            return Optional.empty();
        }
        return paidAt;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getCanceledAt() {
        if (canceledAt == null) {
            return Optional.empty();
        }
        return canceledAt;
    }

    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("updated_at")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("checkout_url")
    private Optional<String> _getCheckoutUrl() {
        return checkoutUrl;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("client_secret")
    private Optional<String> _getClientSecret() {
        return clientSecret;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("last_failure")
    private Optional<String> _getLastFailure() {
        return lastFailure;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("paid_at")
    private Optional<OffsetDateTime> _getPaidAt() {
        return paidAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("canceled_at")
    private Optional<OffsetDateTime> _getCanceledAt() {
        return canceledAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PaymentObject && equalTo((PaymentObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PaymentObject other) {
        return object.equals(other.object)
                && id.equals(other.id)
                && order.equals(other.order)
                && method.equals(other.method)
                && status.equals(other.status)
                && amount == other.amount
                && feeAmount == other.feeAmount
                && currency.equals(other.currency)
                && checkoutUrl.equals(other.checkoutUrl)
                && clientSecret.equals(other.clientSecret)
                && lastFailure.equals(other.lastFailure)
                && amountRefunded == other.amountRefunded
                && release.equals(other.release)
                && stripe.equals(other.stripe)
                && metadata.equals(other.metadata)
                && paidAt.equals(other.paidAt)
                && canceledAt.equals(other.canceledAt)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.object,
                this.id,
                this.order,
                this.method,
                this.status,
                this.amount,
                this.feeAmount,
                this.currency,
                this.checkoutUrl,
                this.clientSecret,
                this.lastFailure,
                this.amountRefunded,
                this.release,
                this.stripe,
                this.metadata,
                this.paidAt,
                this.canceledAt,
                this.createdAt,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ObjectStage builder() {
        return new Builder();
    }

    public interface ObjectStage {
        IdStage object(@NotNull PaymentObjectObject object);

        Builder from(PaymentObject other);
    }

    public interface IdStage {
        OrderStage id(@NotNull String id);
    }

    public interface OrderStage {
        MethodStage order(@NotNull String order);
    }

    public interface MethodStage {
        StatusStage method(@NotNull PaymentObjectMethod method);
    }

    public interface StatusStage {
        AmountStage status(@NotNull PaymentObjectStatus status);
    }

    public interface AmountStage {
        /**
         * <p>Minor units.</p>
         */
        FeeAmountStage amount(double amount);
    }

    public interface FeeAmountStage {
        /**
         * <p>The customer's platform fee. Minor units.</p>
         */
        CurrencyStage feeAmount(double feeAmount);
    }

    public interface CurrencyStage {
        AmountRefundedStage currency(@NotNull String currency);
    }

    public interface AmountRefundedStage {
        /**
         * <p>Refunded or being refunded. Minor units.</p>
         */
        ReleaseStage amountRefunded(double amountRefunded);
    }

    public interface ReleaseStage {
        StripeStage release(@NotNull PaymentReleaseObject release);
    }

    public interface StripeStage {
        /**
         * <p>Ids of the objects on your Stripe account.</p>
         */
        CreatedAtStage stripe(@NotNull PaymentStripeObject stripe);
    }

    public interface CreatedAtStage {
        UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface UpdatedAtStage {
        _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface _FinalStage {
        PaymentObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Stripe-hosted checkout. Shown only while payment is due.</p>
         */
        _FinalStage checkoutUrl(Optional<String> checkoutUrl);

        _FinalStage checkoutUrl(String checkoutUrl);

        _FinalStage checkoutUrl(Nullable<String> checkoutUrl);

        /**
         * <p>For Stripe Elements on your own page. Shown only while payment is due.</p>
         */
        _FinalStage clientSecret(Optional<String> clientSecret);

        _FinalStage clientSecret(String clientSecret);

        _FinalStage clientSecret(Nullable<String> clientSecret);

        /**
         * <p>Stripe's message for the last failed attempt to pay.</p>
         */
        _FinalStage lastFailure(Optional<String> lastFailure);

        _FinalStage lastFailure(String lastFailure);

        _FinalStage lastFailure(Nullable<String> lastFailure);

        _FinalStage metadata(Map<String, String> metadata);

        _FinalStage putAllMetadata(Map<String, String> metadata);

        _FinalStage metadata(String key, String value);

        _FinalStage paidAt(Optional<OffsetDateTime> paidAt);

        _FinalStage paidAt(OffsetDateTime paidAt);

        _FinalStage paidAt(Nullable<OffsetDateTime> paidAt);

        _FinalStage canceledAt(Optional<OffsetDateTime> canceledAt);

        _FinalStage canceledAt(OffsetDateTime canceledAt);

        _FinalStage canceledAt(Nullable<OffsetDateTime> canceledAt);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ObjectStage,
                    IdStage,
                    OrderStage,
                    MethodStage,
                    StatusStage,
                    AmountStage,
                    FeeAmountStage,
                    CurrencyStage,
                    AmountRefundedStage,
                    ReleaseStage,
                    StripeStage,
                    CreatedAtStage,
                    UpdatedAtStage,
                    _FinalStage {
        private PaymentObjectObject object;

        private String id;

        private String order;

        private PaymentObjectMethod method;

        private PaymentObjectStatus status;

        private double amount;

        private double feeAmount;

        private String currency;

        private double amountRefunded;

        private PaymentReleaseObject release;

        private PaymentStripeObject stripe;

        private OffsetDateTime createdAt;

        private OffsetDateTime updatedAt;

        private Optional<OffsetDateTime> canceledAt = Optional.empty();

        private Optional<OffsetDateTime> paidAt = Optional.empty();

        private Map<String, String> metadata = new LinkedHashMap<>();

        private Optional<String> lastFailure = Optional.empty();

        private Optional<String> clientSecret = Optional.empty();

        private Optional<String> checkoutUrl = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PaymentObject other) {
            object(other.getObject());
            id(other.getId());
            order(other.getOrder());
            method(other.getMethod());
            status(other.getStatus());
            amount(other.getAmount());
            feeAmount(other.getFeeAmount());
            currency(other.getCurrency());
            checkoutUrl(other.getCheckoutUrl());
            clientSecret(other.getClientSecret());
            lastFailure(other.getLastFailure());
            amountRefunded(other.getAmountRefunded());
            release(other.getRelease());
            stripe(other.getStripe());
            metadata(other.getMetadata());
            paidAt(other.getPaidAt());
            canceledAt(other.getCanceledAt());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("object")
        public IdStage object(@NotNull PaymentObjectObject object) {
            this.object = Objects.requireNonNull(object, "object must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public OrderStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("order")
        public MethodStage order(@NotNull String order) {
            this.order = Objects.requireNonNull(order, "order must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("method")
        public StatusStage method(@NotNull PaymentObjectMethod method) {
            this.method = Objects.requireNonNull(method, "method must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public AmountStage status(@NotNull PaymentObjectStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>Minor units.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("amount")
        public FeeAmountStage amount(double amount) {
            this.amount = amount;
            return this;
        }

        /**
         * <p>The customer's platform fee. Minor units.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("fee_amount")
        public CurrencyStage feeAmount(double feeAmount) {
            this.feeAmount = feeAmount;
            return this;
        }

        @java.lang.Override
        @JsonSetter("currency")
        public AmountRefundedStage currency(@NotNull String currency) {
            this.currency = Objects.requireNonNull(currency, "currency must not be null");
            return this;
        }

        /**
         * <p>Refunded or being refunded. Minor units.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("amount_refunded")
        public ReleaseStage amountRefunded(double amountRefunded) {
            this.amountRefunded = amountRefunded;
            return this;
        }

        @java.lang.Override
        @JsonSetter("release")
        public StripeStage release(@NotNull PaymentReleaseObject release) {
            this.release = Objects.requireNonNull(release, "release must not be null");
            return this;
        }

        /**
         * <p>Ids of the objects on your Stripe account.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("stripe")
        public CreatedAtStage stripe(@NotNull PaymentStripeObject stripe) {
            this.stripe = Objects.requireNonNull(stripe, "stripe must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("created_at")
        public UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updated_at")
        public _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage canceledAt(Nullable<OffsetDateTime> canceledAt) {
            if (canceledAt.isNull()) {
                this.canceledAt = null;
            } else if (canceledAt.isEmpty()) {
                this.canceledAt = Optional.empty();
            } else {
                this.canceledAt = Optional.of(canceledAt.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage canceledAt(OffsetDateTime canceledAt) {
            this.canceledAt = Optional.ofNullable(canceledAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "canceled_at", nulls = Nulls.SKIP)
        public _FinalStage canceledAt(Optional<OffsetDateTime> canceledAt) {
            this.canceledAt = canceledAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage paidAt(Nullable<OffsetDateTime> paidAt) {
            if (paidAt.isNull()) {
                this.paidAt = null;
            } else if (paidAt.isEmpty()) {
                this.paidAt = Optional.empty();
            } else {
                this.paidAt = Optional.of(paidAt.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage paidAt(OffsetDateTime paidAt) {
            this.paidAt = Optional.ofNullable(paidAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "paid_at", nulls = Nulls.SKIP)
        public _FinalStage paidAt(Optional<OffsetDateTime> paidAt) {
            this.paidAt = paidAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage metadata(String key, String value) {
            this.metadata.put(key, value);
            return this;
        }

        @java.lang.Override
        public _FinalStage putAllMetadata(Map<String, String> metadata) {
            if (metadata != null) {
                this.metadata.putAll(metadata);
            }
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public _FinalStage metadata(Map<String, String> metadata) {
            this.metadata.clear();
            if (metadata != null) {
                this.metadata.putAll(metadata);
            }
            return this;
        }

        /**
         * <p>Stripe's message for the last failed attempt to pay.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage lastFailure(Nullable<String> lastFailure) {
            if (lastFailure.isNull()) {
                this.lastFailure = null;
            } else if (lastFailure.isEmpty()) {
                this.lastFailure = Optional.empty();
            } else {
                this.lastFailure = Optional.of(lastFailure.get());
            }
            return this;
        }

        /**
         * <p>Stripe's message for the last failed attempt to pay.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage lastFailure(String lastFailure) {
            this.lastFailure = Optional.ofNullable(lastFailure);
            return this;
        }

        /**
         * <p>Stripe's message for the last failed attempt to pay.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "last_failure", nulls = Nulls.SKIP)
        public _FinalStage lastFailure(Optional<String> lastFailure) {
            this.lastFailure = lastFailure;
            return this;
        }

        /**
         * <p>For Stripe Elements on your own page. Shown only while payment is due.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage clientSecret(Nullable<String> clientSecret) {
            if (clientSecret.isNull()) {
                this.clientSecret = null;
            } else if (clientSecret.isEmpty()) {
                this.clientSecret = Optional.empty();
            } else {
                this.clientSecret = Optional.of(clientSecret.get());
            }
            return this;
        }

        /**
         * <p>For Stripe Elements on your own page. Shown only while payment is due.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage clientSecret(String clientSecret) {
            this.clientSecret = Optional.ofNullable(clientSecret);
            return this;
        }

        /**
         * <p>For Stripe Elements on your own page. Shown only while payment is due.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "client_secret", nulls = Nulls.SKIP)
        public _FinalStage clientSecret(Optional<String> clientSecret) {
            this.clientSecret = clientSecret;
            return this;
        }

        /**
         * <p>Stripe-hosted checkout. Shown only while payment is due.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage checkoutUrl(Nullable<String> checkoutUrl) {
            if (checkoutUrl.isNull()) {
                this.checkoutUrl = null;
            } else if (checkoutUrl.isEmpty()) {
                this.checkoutUrl = Optional.empty();
            } else {
                this.checkoutUrl = Optional.of(checkoutUrl.get());
            }
            return this;
        }

        /**
         * <p>Stripe-hosted checkout. Shown only while payment is due.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage checkoutUrl(String checkoutUrl) {
            this.checkoutUrl = Optional.ofNullable(checkoutUrl);
            return this;
        }

        /**
         * <p>Stripe-hosted checkout. Shown only while payment is due.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "checkout_url", nulls = Nulls.SKIP)
        public _FinalStage checkoutUrl(Optional<String> checkoutUrl) {
            this.checkoutUrl = checkoutUrl;
            return this;
        }

        @java.lang.Override
        public PaymentObject build() {
            return new PaymentObject(
                    object,
                    id,
                    order,
                    method,
                    status,
                    amount,
                    feeAmount,
                    currency,
                    checkoutUrl,
                    clientSecret,
                    lastFailure,
                    amountRefunded,
                    release,
                    stripe,
                    metadata,
                    paidAt,
                    canceledAt,
                    createdAt,
                    updatedAt,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
