/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ReadOnlyObject.Builder.class)
public final class ReadOnlyObject {
    private final ReadOnlyObjectReason reason;

    private final OffsetDateTime since;

    private final Map<String, Object> additionalProperties;

    private ReadOnlyObject(
            ReadOnlyObjectReason reason, OffsetDateTime since, Map<String, Object> additionalProperties) {
        this.reason = reason;
        this.since = since;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("reason")
    public ReadOnlyObjectReason getReason() {
        return reason;
    }

    @JsonProperty("since")
    public OffsetDateTime getSince() {
        return since;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ReadOnlyObject && equalTo((ReadOnlyObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ReadOnlyObject other) {
        return reason.equals(other.reason) && since.equals(other.since);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.reason, this.since);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ReasonStage builder() {
        return new Builder();
    }

    public interface ReasonStage {
        SinceStage reason(@NotNull ReadOnlyObjectReason reason);

        Builder from(ReadOnlyObject other);
    }

    public interface SinceStage {
        _FinalStage since(@NotNull OffsetDateTime since);
    }

    public interface _FinalStage {
        ReadOnlyObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ReasonStage, SinceStage, _FinalStage {
        private ReadOnlyObjectReason reason;

        private OffsetDateTime since;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ReadOnlyObject other) {
            reason(other.getReason());
            since(other.getSince());
            return this;
        }

        @java.lang.Override
        @JsonSetter("reason")
        public SinceStage reason(@NotNull ReadOnlyObjectReason reason) {
            this.reason = Objects.requireNonNull(reason, "reason must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("since")
        public _FinalStage since(@NotNull OffsetDateTime since) {
            this.since = Objects.requireNonNull(since, "since must not be null");
            return this;
        }

        @java.lang.Override
        public ReadOnlyObject build() {
            return new ReadOnlyObject(reason, since, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
