/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ReputationEventObjectKind {
    public static final ReputationEventObjectKind LAPSED = new ReputationEventObjectKind(Value.LAPSED, "lapsed");

    public static final ReputationEventObjectKind BACKED_OUT =
            new ReputationEventObjectKind(Value.BACKED_OUT, "backed_out");

    public static final ReputationEventObjectKind DISPUTE_WON =
            new ReputationEventObjectKind(Value.DISPUTE_WON, "dispute_won");

    public static final ReputationEventObjectKind ORDER_COMPLETED =
            new ReputationEventObjectKind(Value.ORDER_COMPLETED, "order_completed");

    public static final ReputationEventObjectKind VOIDED = new ReputationEventObjectKind(Value.VOIDED, "voided");

    public static final ReputationEventObjectKind REVIEW_RECEIVED =
            new ReputationEventObjectKind(Value.REVIEW_RECEIVED, "review_received");

    public static final ReputationEventObjectKind DISPUTE_LOST =
            new ReputationEventObjectKind(Value.DISPUTE_LOST, "dispute_lost");

    private final Value value;

    private final String string;

    ReputationEventObjectKind(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ReputationEventObjectKind
                        && this.string.equals(((ReputationEventObjectKind) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case LAPSED:
                return visitor.visitLapsed();
            case BACKED_OUT:
                return visitor.visitBackedOut();
            case DISPUTE_WON:
                return visitor.visitDisputeWon();
            case ORDER_COMPLETED:
                return visitor.visitOrderCompleted();
            case VOIDED:
                return visitor.visitVoided();
            case REVIEW_RECEIVED:
                return visitor.visitReviewReceived();
            case DISPUTE_LOST:
                return visitor.visitDisputeLost();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ReputationEventObjectKind valueOf(String value) {
        switch (value) {
            case "lapsed":
                return LAPSED;
            case "backed_out":
                return BACKED_OUT;
            case "dispute_won":
                return DISPUTE_WON;
            case "order_completed":
                return ORDER_COMPLETED;
            case "voided":
                return VOIDED;
            case "review_received":
                return REVIEW_RECEIVED;
            case "dispute_lost":
                return DISPUTE_LOST;
            default:
                return new ReputationEventObjectKind(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ORDER_COMPLETED,

        BACKED_OUT,

        DISPUTE_LOST,

        DISPUTE_WON,

        LAPSED,

        REVIEW_RECEIVED,

        VOIDED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitOrderCompleted();

        T visitBackedOut();

        T visitDisputeLost();

        T visitDisputeWon();

        T visitLapsed();

        T visitReviewReceived();

        T visitVoided();

        T visitUnknown(String unknownType);
    }
}
