/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SellerVerificationSummaryStatus {
    public static final SellerVerificationSummaryStatus UNVERIFIED =
            new SellerVerificationSummaryStatus(Value.UNVERIFIED, "unverified");

    public static final SellerVerificationSummaryStatus PENDING =
            new SellerVerificationSummaryStatus(Value.PENDING, "pending");

    public static final SellerVerificationSummaryStatus CANCELED =
            new SellerVerificationSummaryStatus(Value.CANCELED, "canceled");

    public static final SellerVerificationSummaryStatus REQUIRES_INPUT =
            new SellerVerificationSummaryStatus(Value.REQUIRES_INPUT, "requires_input");

    public static final SellerVerificationSummaryStatus VERIFIED =
            new SellerVerificationSummaryStatus(Value.VERIFIED, "verified");

    private final Value value;

    private final String string;

    SellerVerificationSummaryStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SellerVerificationSummaryStatus
                        && this.string.equals(((SellerVerificationSummaryStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case UNVERIFIED:
                return visitor.visitUnverified();
            case PENDING:
                return visitor.visitPending();
            case CANCELED:
                return visitor.visitCanceled();
            case REQUIRES_INPUT:
                return visitor.visitRequiresInput();
            case VERIFIED:
                return visitor.visitVerified();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SellerVerificationSummaryStatus valueOf(String value) {
        switch (value) {
            case "unverified":
                return UNVERIFIED;
            case "pending":
                return PENDING;
            case "canceled":
                return CANCELED;
            case "requires_input":
                return REQUIRES_INPUT;
            case "verified":
                return VERIFIED;
            default:
                return new SellerVerificationSummaryStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        UNVERIFIED,

        PENDING,

        VERIFIED,

        REQUIRES_INPUT,

        CANCELED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitUnverified();

        T visitPending();

        T visitVerified();

        T visitRequiresInput();

        T visitCanceled();

        T visitUnknown(String unknownType);
    }
}
