/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SellerObjectStatus {
    public static final SellerObjectStatus SUSPENDED = new SellerObjectStatus(Value.SUSPENDED, "suspended");

    public static final SellerObjectStatus ACTIVE = new SellerObjectStatus(Value.ACTIVE, "active");

    private final Value value;

    private final String string;

    SellerObjectStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SellerObjectStatus && this.string.equals(((SellerObjectStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SUSPENDED:
                return visitor.visitSuspended();
            case ACTIVE:
                return visitor.visitActive();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SellerObjectStatus valueOf(String value) {
        switch (value) {
            case "suspended":
                return SUSPENDED;
            case "active":
                return ACTIVE;
            default:
                return new SellerObjectStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ACTIVE,

        SUSPENDED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitActive();

        T visitSuspended();

        T visitUnknown(String unknownType);
    }
}
