/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SellerProfileObjectObject {
    public static final SellerProfileObjectObject SELLER_PROFILE =
            new SellerProfileObjectObject(Value.SELLER_PROFILE, "seller_profile");

    private final Value value;

    private final String string;

    SellerProfileObjectObject(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SellerProfileObjectObject
                        && this.string.equals(((SellerProfileObjectObject) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SELLER_PROFILE:
                return visitor.visitSellerProfile();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SellerProfileObjectObject valueOf(String value) {
        switch (value) {
            case "seller_profile":
                return SELLER_PROFILE;
            default:
                return new SellerProfileObjectObject(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SELLER_PROFILE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSellerProfile();

        T visitUnknown(String unknownType);
    }
}
