/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.Nullable;
import com.marketsdk.core.NullableNonemptyFilter;
import com.marketsdk.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SellerProfileObject.Builder.class)
public final class SellerProfileObject {
    private final SellerProfileObjectObject object;

    private final String id;

    private final Optional<String> displayName;

    private final SellerProfileObjectVerificationStatus verificationStatus;

    private final Optional<StorefrontObject> storefront;

    private final ReputationObject reputation;

    private final Map<String, Object> additionalProperties;

    private SellerProfileObject(
            SellerProfileObjectObject object,
            String id,
            Optional<String> displayName,
            SellerProfileObjectVerificationStatus verificationStatus,
            Optional<StorefrontObject> storefront,
            ReputationObject reputation,
            Map<String, Object> additionalProperties) {
        this.object = object;
        this.id = id;
        this.displayName = displayName;
        this.verificationStatus = verificationStatus;
        this.storefront = storefront;
        this.reputation = reputation;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("object")
    public SellerProfileObjectObject getObject() {
        return object;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonIgnore
    public Optional<String> getDisplayName() {
        if (displayName == null) {
            return Optional.empty();
        }
        return displayName;
    }

    @JsonProperty("verification_status")
    public SellerProfileObjectVerificationStatus getVerificationStatus() {
        return verificationStatus;
    }

    @JsonIgnore
    public Optional<StorefrontObject> getStorefront() {
        if (storefront == null) {
            return Optional.empty();
        }
        return storefront;
    }

    @JsonProperty("reputation")
    public ReputationObject getReputation() {
        return reputation;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("display_name")
    private Optional<String> _getDisplayName() {
        return displayName;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("storefront")
    private Optional<StorefrontObject> _getStorefront() {
        return storefront;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SellerProfileObject && equalTo((SellerProfileObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SellerProfileObject other) {
        return object.equals(other.object)
                && id.equals(other.id)
                && displayName.equals(other.displayName)
                && verificationStatus.equals(other.verificationStatus)
                && storefront.equals(other.storefront)
                && reputation.equals(other.reputation);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.object, this.id, this.displayName, this.verificationStatus, this.storefront, this.reputation);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ObjectStage builder() {
        return new Builder();
    }

    public interface ObjectStage {
        IdStage object(@NotNull SellerProfileObjectObject object);

        Builder from(SellerProfileObject other);
    }

    public interface IdStage {
        VerificationStatusStage id(@NotNull String id);
    }

    public interface VerificationStatusStage {
        ReputationStage verificationStatus(@NotNull SellerProfileObjectVerificationStatus verificationStatus);
    }

    public interface ReputationStage {
        _FinalStage reputation(@NotNull ReputationObject reputation);
    }

    public interface _FinalStage {
        SellerProfileObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage displayName(Optional<String> displayName);

        _FinalStage displayName(String displayName);

        _FinalStage displayName(Nullable<String> displayName);

        _FinalStage storefront(Optional<StorefrontObject> storefront);

        _FinalStage storefront(StorefrontObject storefront);

        _FinalStage storefront(Nullable<StorefrontObject> storefront);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ObjectStage, IdStage, VerificationStatusStage, ReputationStage, _FinalStage {
        private SellerProfileObjectObject object;

        private String id;

        private SellerProfileObjectVerificationStatus verificationStatus;

        private ReputationObject reputation;

        private Optional<StorefrontObject> storefront = Optional.empty();

        private Optional<String> displayName = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SellerProfileObject other) {
            object(other.getObject());
            id(other.getId());
            displayName(other.getDisplayName());
            verificationStatus(other.getVerificationStatus());
            storefront(other.getStorefront());
            reputation(other.getReputation());
            return this;
        }

        @java.lang.Override
        @JsonSetter("object")
        public IdStage object(@NotNull SellerProfileObjectObject object) {
            this.object = Objects.requireNonNull(object, "object must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public VerificationStatusStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("verification_status")
        public ReputationStage verificationStatus(@NotNull SellerProfileObjectVerificationStatus verificationStatus) {
            this.verificationStatus = Objects.requireNonNull(verificationStatus, "verificationStatus must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("reputation")
        public _FinalStage reputation(@NotNull ReputationObject reputation) {
            this.reputation = Objects.requireNonNull(reputation, "reputation must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage storefront(Nullable<StorefrontObject> storefront) {
            if (storefront.isNull()) {
                this.storefront = null;
            } else if (storefront.isEmpty()) {
                this.storefront = Optional.empty();
            } else {
                this.storefront = Optional.of(storefront.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage storefront(StorefrontObject storefront) {
            this.storefront = Optional.ofNullable(storefront);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "storefront", nulls = Nulls.SKIP)
        public _FinalStage storefront(Optional<StorefrontObject> storefront) {
            this.storefront = storefront;
            return this;
        }

        @java.lang.Override
        public _FinalStage displayName(Nullable<String> displayName) {
            if (displayName.isNull()) {
                this.displayName = null;
            } else if (displayName.isEmpty()) {
                this.displayName = Optional.empty();
            } else {
                this.displayName = Optional.of(displayName.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage displayName(String displayName) {
            this.displayName = Optional.ofNullable(displayName);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "display_name", nulls = Nulls.SKIP)
        public _FinalStage displayName(Optional<String> displayName) {
            this.displayName = displayName;
            return this;
        }

        @java.lang.Override
        public SellerProfileObject build() {
            return new SellerProfileObject(
                    object, id, displayName, verificationStatus, storefront, reputation, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
