/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class WebhookEndpointObjectObject {
    public static final WebhookEndpointObjectObject WEBHOOK_ENDPOINT =
            new WebhookEndpointObjectObject(Value.WEBHOOK_ENDPOINT, "webhook_endpoint");

    private final Value value;

    private final String string;

    WebhookEndpointObjectObject(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof WebhookEndpointObjectObject
                        && this.string.equals(((WebhookEndpointObjectObject) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case WEBHOOK_ENDPOINT:
                return visitor.visitWebhookEndpoint();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static WebhookEndpointObjectObject valueOf(String value) {
        switch (value) {
            case "webhook_endpoint":
                return WEBHOOK_ENDPOINT;
            default:
                return new WebhookEndpointObjectObject(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        WEBHOOK_ENDPOINT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitWebhookEndpoint();

        T visitUnknown(String unknownType);
    }
}
