/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.Nullable;
import com.marketsdk.core.NullableNonemptyFilter;
import com.marketsdk.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = WebhookEndpointObject.Builder.class)
public final class WebhookEndpointObject {
    private final WebhookEndpointObjectObject object;

    private final String id;

    private final String url;

    private final Optional<String> description;

    private final List<String> enabledEvents;

    private final WebhookEndpointObjectStatus status;

    private final Optional<String> disabledReason;

    private final Optional<OffsetDateTime> failingSince;

    private final Optional<OffsetDateTime> lastSuccessAt;

    private final Optional<String> secret;

    private final Map<String, String> metadata;

    private final OffsetDateTime createdAt;

    private final Map<String, Object> additionalProperties;

    private WebhookEndpointObject(
            WebhookEndpointObjectObject object,
            String id,
            String url,
            Optional<String> description,
            List<String> enabledEvents,
            WebhookEndpointObjectStatus status,
            Optional<String> disabledReason,
            Optional<OffsetDateTime> failingSince,
            Optional<OffsetDateTime> lastSuccessAt,
            Optional<String> secret,
            Map<String, String> metadata,
            OffsetDateTime createdAt,
            Map<String, Object> additionalProperties) {
        this.object = object;
        this.id = id;
        this.url = url;
        this.description = description;
        this.enabledEvents = enabledEvents;
        this.status = status;
        this.disabledReason = disabledReason;
        this.failingSince = failingSince;
        this.lastSuccessAt = lastSuccessAt;
        this.secret = secret;
        this.metadata = metadata;
        this.createdAt = createdAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("object")
    public WebhookEndpointObjectObject getObject() {
        return object;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("url")
    public String getUrl() {
        return url;
    }

    @JsonIgnore
    public Optional<String> getDescription() {
        if (description == null) {
            return Optional.empty();
        }
        return description;
    }

    @JsonProperty("enabled_events")
    public List<String> getEnabledEvents() {
        return enabledEvents;
    }

    @JsonProperty("status")
    public WebhookEndpointObjectStatus getStatus() {
        return status;
    }

    /**
     * @return Why it was turned off, when MarketSDK turned it off.
     */
    @JsonIgnore
    public Optional<String> getDisabledReason() {
        if (disabledReason == null) {
            return Optional.empty();
        }
        return disabledReason;
    }

    /**
     * @return Every delivery has failed since this time.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getFailingSince() {
        if (failingSince == null) {
            return Optional.empty();
        }
        return failingSince;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getLastSuccessAt() {
        if (lastSuccessAt == null) {
            return Optional.empty();
        }
        return lastSuccessAt;
    }

    /**
     * @return The signing secret. Returned only when the endpoint is created or its secret rotated.
     */
    @JsonProperty("secret")
    public Optional<String> getSecret() {
        return secret;
    }

    @JsonProperty("metadata")
    public Map<String, String> getMetadata() {
        return metadata;
    }

    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("description")
    private Optional<String> _getDescription() {
        return description;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("disabled_reason")
    private Optional<String> _getDisabledReason() {
        return disabledReason;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("failing_since")
    private Optional<OffsetDateTime> _getFailingSince() {
        return failingSince;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("last_success_at")
    private Optional<OffsetDateTime> _getLastSuccessAt() {
        return lastSuccessAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof WebhookEndpointObject && equalTo((WebhookEndpointObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(WebhookEndpointObject other) {
        return object.equals(other.object)
                && id.equals(other.id)
                && url.equals(other.url)
                && description.equals(other.description)
                && enabledEvents.equals(other.enabledEvents)
                && status.equals(other.status)
                && disabledReason.equals(other.disabledReason)
                && failingSince.equals(other.failingSince)
                && lastSuccessAt.equals(other.lastSuccessAt)
                && secret.equals(other.secret)
                && metadata.equals(other.metadata)
                && createdAt.equals(other.createdAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.object,
                this.id,
                this.url,
                this.description,
                this.enabledEvents,
                this.status,
                this.disabledReason,
                this.failingSince,
                this.lastSuccessAt,
                this.secret,
                this.metadata,
                this.createdAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ObjectStage builder() {
        return new Builder();
    }

    public interface ObjectStage {
        IdStage object(@NotNull WebhookEndpointObjectObject object);

        Builder from(WebhookEndpointObject other);
    }

    public interface IdStage {
        UrlStage id(@NotNull String id);
    }

    public interface UrlStage {
        StatusStage url(@NotNull String url);
    }

    public interface StatusStage {
        CreatedAtStage status(@NotNull WebhookEndpointObjectStatus status);
    }

    public interface CreatedAtStage {
        _FinalStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface _FinalStage {
        WebhookEndpointObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        _FinalStage description(Nullable<String> description);

        _FinalStage enabledEvents(List<String> enabledEvents);

        _FinalStage addEnabledEvents(String enabledEvents);

        _FinalStage addAllEnabledEvents(List<String> enabledEvents);

        /**
         * <p>Why it was turned off, when MarketSDK turned it off.</p>
         */
        _FinalStage disabledReason(Optional<String> disabledReason);

        _FinalStage disabledReason(String disabledReason);

        _FinalStage disabledReason(Nullable<String> disabledReason);

        /**
         * <p>Every delivery has failed since this time.</p>
         */
        _FinalStage failingSince(Optional<OffsetDateTime> failingSince);

        _FinalStage failingSince(OffsetDateTime failingSince);

        _FinalStage failingSince(Nullable<OffsetDateTime> failingSince);

        _FinalStage lastSuccessAt(Optional<OffsetDateTime> lastSuccessAt);

        _FinalStage lastSuccessAt(OffsetDateTime lastSuccessAt);

        _FinalStage lastSuccessAt(Nullable<OffsetDateTime> lastSuccessAt);

        /**
         * <p>The signing secret. Returned only when the endpoint is created or its secret rotated.</p>
         */
        _FinalStage secret(Optional<String> secret);

        _FinalStage secret(String secret);

        _FinalStage metadata(Map<String, String> metadata);

        _FinalStage putAllMetadata(Map<String, String> metadata);

        _FinalStage metadata(String key, String value);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ObjectStage, IdStage, UrlStage, StatusStage, CreatedAtStage, _FinalStage {
        private WebhookEndpointObjectObject object;

        private String id;

        private String url;

        private WebhookEndpointObjectStatus status;

        private OffsetDateTime createdAt;

        private Map<String, String> metadata = new LinkedHashMap<>();

        private Optional<String> secret = Optional.empty();

        private Optional<OffsetDateTime> lastSuccessAt = Optional.empty();

        private Optional<OffsetDateTime> failingSince = Optional.empty();

        private Optional<String> disabledReason = Optional.empty();

        private List<String> enabledEvents = new ArrayList<>();

        private Optional<String> description = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(WebhookEndpointObject other) {
            object(other.getObject());
            id(other.getId());
            url(other.getUrl());
            description(other.getDescription());
            enabledEvents(other.getEnabledEvents());
            status(other.getStatus());
            disabledReason(other.getDisabledReason());
            failingSince(other.getFailingSince());
            lastSuccessAt(other.getLastSuccessAt());
            secret(other.getSecret());
            metadata(other.getMetadata());
            createdAt(other.getCreatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("object")
        public IdStage object(@NotNull WebhookEndpointObjectObject object) {
            this.object = Objects.requireNonNull(object, "object must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public UrlStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("url")
        public StatusStage url(@NotNull String url) {
            this.url = Objects.requireNonNull(url, "url must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public CreatedAtStage status(@NotNull WebhookEndpointObjectStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("created_at")
        public _FinalStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage metadata(String key, String value) {
            this.metadata.put(key, value);
            return this;
        }

        @java.lang.Override
        public _FinalStage putAllMetadata(Map<String, String> metadata) {
            if (metadata != null) {
                this.metadata.putAll(metadata);
            }
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public _FinalStage metadata(Map<String, String> metadata) {
            this.metadata.clear();
            if (metadata != null) {
                this.metadata.putAll(metadata);
            }
            return this;
        }

        /**
         * <p>The signing secret. Returned only when the endpoint is created or its secret rotated.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage secret(String secret) {
            this.secret = Optional.ofNullable(secret);
            return this;
        }

        /**
         * <p>The signing secret. Returned only when the endpoint is created or its secret rotated.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "secret", nulls = Nulls.SKIP)
        public _FinalStage secret(Optional<String> secret) {
            this.secret = secret;
            return this;
        }

        @java.lang.Override
        public _FinalStage lastSuccessAt(Nullable<OffsetDateTime> lastSuccessAt) {
            if (lastSuccessAt.isNull()) {
                this.lastSuccessAt = null;
            } else if (lastSuccessAt.isEmpty()) {
                this.lastSuccessAt = Optional.empty();
            } else {
                this.lastSuccessAt = Optional.of(lastSuccessAt.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage lastSuccessAt(OffsetDateTime lastSuccessAt) {
            this.lastSuccessAt = Optional.ofNullable(lastSuccessAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "last_success_at", nulls = Nulls.SKIP)
        public _FinalStage lastSuccessAt(Optional<OffsetDateTime> lastSuccessAt) {
            this.lastSuccessAt = lastSuccessAt;
            return this;
        }

        /**
         * <p>Every delivery has failed since this time.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage failingSince(Nullable<OffsetDateTime> failingSince) {
            if (failingSince.isNull()) {
                this.failingSince = null;
            } else if (failingSince.isEmpty()) {
                this.failingSince = Optional.empty();
            } else {
                this.failingSince = Optional.of(failingSince.get());
            }
            return this;
        }

        /**
         * <p>Every delivery has failed since this time.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage failingSince(OffsetDateTime failingSince) {
            this.failingSince = Optional.ofNullable(failingSince);
            return this;
        }

        /**
         * <p>Every delivery has failed since this time.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "failing_since", nulls = Nulls.SKIP)
        public _FinalStage failingSince(Optional<OffsetDateTime> failingSince) {
            this.failingSince = failingSince;
            return this;
        }

        /**
         * <p>Why it was turned off, when MarketSDK turned it off.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage disabledReason(Nullable<String> disabledReason) {
            if (disabledReason.isNull()) {
                this.disabledReason = null;
            } else if (disabledReason.isEmpty()) {
                this.disabledReason = Optional.empty();
            } else {
                this.disabledReason = Optional.of(disabledReason.get());
            }
            return this;
        }

        /**
         * <p>Why it was turned off, when MarketSDK turned it off.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage disabledReason(String disabledReason) {
            this.disabledReason = Optional.ofNullable(disabledReason);
            return this;
        }

        /**
         * <p>Why it was turned off, when MarketSDK turned it off.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "disabled_reason", nulls = Nulls.SKIP)
        public _FinalStage disabledReason(Optional<String> disabledReason) {
            this.disabledReason = disabledReason;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllEnabledEvents(List<String> enabledEvents) {
            if (enabledEvents != null) {
                this.enabledEvents.addAll(enabledEvents);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addEnabledEvents(String enabledEvents) {
            this.enabledEvents.add(enabledEvents);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "enabled_events", nulls = Nulls.SKIP)
        public _FinalStage enabledEvents(List<String> enabledEvents) {
            this.enabledEvents.clear();
            if (enabledEvents != null) {
                this.enabledEvents.addAll(enabledEvents);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage description(Nullable<String> description) {
            if (description.isNull()) {
                this.description = null;
            } else if (description.isEmpty()) {
                this.description = Optional.empty();
            } else {
                this.description = Optional.of(description.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        @java.lang.Override
        public WebhookEndpointObject build() {
            return new WebhookEndpointObject(
                    object,
                    id,
                    url,
                    description,
                    enabledEvents,
                    status,
                    disabledReason,
                    failingSince,
                    lastSuccessAt,
                    secret,
                    metadata,
                    createdAt,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
