/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.Nullable;
import com.marketsdk.core.NullableNonemptyFilter;
import com.marketsdk.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = WebhookDeliveryObject.Builder.class)
public final class WebhookDeliveryObject {
    private final WebhookDeliveryObjectObject object;

    private final String id;

    private final String endpoint;

    private final String event;

    private final String eventType;

    private final Optional<String> replayOf;

    private final WebhookDeliveryObjectStatus status;

    private final double attempts;

    private final List<DeliveryAttemptObject> attemptLog;

    private final Optional<OffsetDateTime> nextAttemptAt;

    private final WebhookDeliveryRequestObject request;

    private final WebhookDeliveryResponseObject response;

    private final Optional<String> error;

    private final OffsetDateTime createdAt;

    private final Optional<OffsetDateTime> completedAt;

    private final Map<String, Object> additionalProperties;

    private WebhookDeliveryObject(
            WebhookDeliveryObjectObject object,
            String id,
            String endpoint,
            String event,
            String eventType,
            Optional<String> replayOf,
            WebhookDeliveryObjectStatus status,
            double attempts,
            List<DeliveryAttemptObject> attemptLog,
            Optional<OffsetDateTime> nextAttemptAt,
            WebhookDeliveryRequestObject request,
            WebhookDeliveryResponseObject response,
            Optional<String> error,
            OffsetDateTime createdAt,
            Optional<OffsetDateTime> completedAt,
            Map<String, Object> additionalProperties) {
        this.object = object;
        this.id = id;
        this.endpoint = endpoint;
        this.event = event;
        this.eventType = eventType;
        this.replayOf = replayOf;
        this.status = status;
        this.attempts = attempts;
        this.attemptLog = attemptLog;
        this.nextAttemptAt = nextAttemptAt;
        this.request = request;
        this.response = response;
        this.error = error;
        this.createdAt = createdAt;
        this.completedAt = completedAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("object")
    public WebhookDeliveryObjectObject getObject() {
        return object;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("endpoint")
    public String getEndpoint() {
        return endpoint;
    }

    @JsonProperty("event")
    public String getEvent() {
        return event;
    }

    @JsonProperty("event_type")
    public String getEventType() {
        return eventType;
    }

    /**
     * @return The delivery this one replays.
     */
    @JsonIgnore
    public Optional<String> getReplayOf() {
        if (replayOf == null) {
            return Optional.empty();
        }
        return replayOf;
    }

    @JsonProperty("status")
    public WebhookDeliveryObjectStatus getStatus() {
        return status;
    }

    @JsonProperty("attempts")
    public double getAttempts() {
        return attempts;
    }

    @JsonProperty("attempt_log")
    public List<DeliveryAttemptObject> getAttemptLog() {
        return attemptLog;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getNextAttemptAt() {
        if (nextAttemptAt == null) {
            return Optional.empty();
        }
        return nextAttemptAt;
    }

    @JsonProperty("request")
    public WebhookDeliveryRequestObject getRequest() {
        return request;
    }

    @JsonProperty("response")
    public WebhookDeliveryResponseObject getResponse() {
        return response;
    }

    /**
     * @return Why the last attempt failed.
     */
    @JsonIgnore
    public Optional<String> getError() {
        if (error == null) {
            return Optional.empty();
        }
        return error;
    }

    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getCompletedAt() {
        if (completedAt == null) {
            return Optional.empty();
        }
        return completedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("replay_of")
    private Optional<String> _getReplayOf() {
        return replayOf;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("next_attempt_at")
    private Optional<OffsetDateTime> _getNextAttemptAt() {
        return nextAttemptAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("error")
    private Optional<String> _getError() {
        return error;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("completed_at")
    private Optional<OffsetDateTime> _getCompletedAt() {
        return completedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof WebhookDeliveryObject && equalTo((WebhookDeliveryObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(WebhookDeliveryObject other) {
        return object.equals(other.object)
                && id.equals(other.id)
                && endpoint.equals(other.endpoint)
                && event.equals(other.event)
                && eventType.equals(other.eventType)
                && replayOf.equals(other.replayOf)
                && status.equals(other.status)
                && attempts == other.attempts
                && attemptLog.equals(other.attemptLog)
                && nextAttemptAt.equals(other.nextAttemptAt)
                && request.equals(other.request)
                && response.equals(other.response)
                && error.equals(other.error)
                && createdAt.equals(other.createdAt)
                && completedAt.equals(other.completedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.object,
                this.id,
                this.endpoint,
                this.event,
                this.eventType,
                this.replayOf,
                this.status,
                this.attempts,
                this.attemptLog,
                this.nextAttemptAt,
                this.request,
                this.response,
                this.error,
                this.createdAt,
                this.completedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ObjectStage builder() {
        return new Builder();
    }

    public interface ObjectStage {
        IdStage object(@NotNull WebhookDeliveryObjectObject object);

        Builder from(WebhookDeliveryObject other);
    }

    public interface IdStage {
        EndpointStage id(@NotNull String id);
    }

    public interface EndpointStage {
        EventStage endpoint(@NotNull String endpoint);
    }

    public interface EventStage {
        EventTypeStage event(@NotNull String event);
    }

    public interface EventTypeStage {
        StatusStage eventType(@NotNull String eventType);
    }

    public interface StatusStage {
        AttemptsStage status(@NotNull WebhookDeliveryObjectStatus status);
    }

    public interface AttemptsStage {
        RequestStage attempts(double attempts);
    }

    public interface RequestStage {
        ResponseStage request(@NotNull WebhookDeliveryRequestObject request);
    }

    public interface ResponseStage {
        CreatedAtStage response(@NotNull WebhookDeliveryResponseObject response);
    }

    public interface CreatedAtStage {
        _FinalStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface _FinalStage {
        WebhookDeliveryObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The delivery this one replays.</p>
         */
        _FinalStage replayOf(Optional<String> replayOf);

        _FinalStage replayOf(String replayOf);

        _FinalStage replayOf(Nullable<String> replayOf);

        _FinalStage attemptLog(List<DeliveryAttemptObject> attemptLog);

        _FinalStage addAttemptLog(DeliveryAttemptObject attemptLog);

        _FinalStage addAllAttemptLog(List<DeliveryAttemptObject> attemptLog);

        _FinalStage nextAttemptAt(Optional<OffsetDateTime> nextAttemptAt);

        _FinalStage nextAttemptAt(OffsetDateTime nextAttemptAt);

        _FinalStage nextAttemptAt(Nullable<OffsetDateTime> nextAttemptAt);

        /**
         * <p>Why the last attempt failed.</p>
         */
        _FinalStage error(Optional<String> error);

        _FinalStage error(String error);

        _FinalStage error(Nullable<String> error);

        _FinalStage completedAt(Optional<OffsetDateTime> completedAt);

        _FinalStage completedAt(OffsetDateTime completedAt);

        _FinalStage completedAt(Nullable<OffsetDateTime> completedAt);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ObjectStage,
                    IdStage,
                    EndpointStage,
                    EventStage,
                    EventTypeStage,
                    StatusStage,
                    AttemptsStage,
                    RequestStage,
                    ResponseStage,
                    CreatedAtStage,
                    _FinalStage {
        private WebhookDeliveryObjectObject object;

        private String id;

        private String endpoint;

        private String event;

        private String eventType;

        private WebhookDeliveryObjectStatus status;

        private double attempts;

        private WebhookDeliveryRequestObject request;

        private WebhookDeliveryResponseObject response;

        private OffsetDateTime createdAt;

        private Optional<OffsetDateTime> completedAt = Optional.empty();

        private Optional<String> error = Optional.empty();

        private Optional<OffsetDateTime> nextAttemptAt = Optional.empty();

        private List<DeliveryAttemptObject> attemptLog = new ArrayList<>();

        private Optional<String> replayOf = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(WebhookDeliveryObject other) {
            object(other.getObject());
            id(other.getId());
            endpoint(other.getEndpoint());
            event(other.getEvent());
            eventType(other.getEventType());
            replayOf(other.getReplayOf());
            status(other.getStatus());
            attempts(other.getAttempts());
            attemptLog(other.getAttemptLog());
            nextAttemptAt(other.getNextAttemptAt());
            request(other.getRequest());
            response(other.getResponse());
            error(other.getError());
            createdAt(other.getCreatedAt());
            completedAt(other.getCompletedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("object")
        public IdStage object(@NotNull WebhookDeliveryObjectObject object) {
            this.object = Objects.requireNonNull(object, "object must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public EndpointStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("endpoint")
        public EventStage endpoint(@NotNull String endpoint) {
            this.endpoint = Objects.requireNonNull(endpoint, "endpoint must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("event")
        public EventTypeStage event(@NotNull String event) {
            this.event = Objects.requireNonNull(event, "event must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("event_type")
        public StatusStage eventType(@NotNull String eventType) {
            this.eventType = Objects.requireNonNull(eventType, "eventType must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public AttemptsStage status(@NotNull WebhookDeliveryObjectStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("attempts")
        public RequestStage attempts(double attempts) {
            this.attempts = attempts;
            return this;
        }

        @java.lang.Override
        @JsonSetter("request")
        public ResponseStage request(@NotNull WebhookDeliveryRequestObject request) {
            this.request = Objects.requireNonNull(request, "request must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("response")
        public CreatedAtStage response(@NotNull WebhookDeliveryResponseObject response) {
            this.response = Objects.requireNonNull(response, "response must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("created_at")
        public _FinalStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage completedAt(Nullable<OffsetDateTime> completedAt) {
            if (completedAt.isNull()) {
                this.completedAt = null;
            } else if (completedAt.isEmpty()) {
                this.completedAt = Optional.empty();
            } else {
                this.completedAt = Optional.of(completedAt.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage completedAt(OffsetDateTime completedAt) {
            this.completedAt = Optional.ofNullable(completedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "completed_at", nulls = Nulls.SKIP)
        public _FinalStage completedAt(Optional<OffsetDateTime> completedAt) {
            this.completedAt = completedAt;
            return this;
        }

        /**
         * <p>Why the last attempt failed.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage error(Nullable<String> error) {
            if (error.isNull()) {
                this.error = null;
            } else if (error.isEmpty()) {
                this.error = Optional.empty();
            } else {
                this.error = Optional.of(error.get());
            }
            return this;
        }

        /**
         * <p>Why the last attempt failed.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage error(String error) {
            this.error = Optional.ofNullable(error);
            return this;
        }

        /**
         * <p>Why the last attempt failed.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "error", nulls = Nulls.SKIP)
        public _FinalStage error(Optional<String> error) {
            this.error = error;
            return this;
        }

        @java.lang.Override
        public _FinalStage nextAttemptAt(Nullable<OffsetDateTime> nextAttemptAt) {
            if (nextAttemptAt.isNull()) {
                this.nextAttemptAt = null;
            } else if (nextAttemptAt.isEmpty()) {
                this.nextAttemptAt = Optional.empty();
            } else {
                this.nextAttemptAt = Optional.of(nextAttemptAt.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage nextAttemptAt(OffsetDateTime nextAttemptAt) {
            this.nextAttemptAt = Optional.ofNullable(nextAttemptAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "next_attempt_at", nulls = Nulls.SKIP)
        public _FinalStage nextAttemptAt(Optional<OffsetDateTime> nextAttemptAt) {
            this.nextAttemptAt = nextAttemptAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllAttemptLog(List<DeliveryAttemptObject> attemptLog) {
            if (attemptLog != null) {
                this.attemptLog.addAll(attemptLog);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addAttemptLog(DeliveryAttemptObject attemptLog) {
            this.attemptLog.add(attemptLog);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "attempt_log", nulls = Nulls.SKIP)
        public _FinalStage attemptLog(List<DeliveryAttemptObject> attemptLog) {
            this.attemptLog.clear();
            if (attemptLog != null) {
                this.attemptLog.addAll(attemptLog);
            }
            return this;
        }

        /**
         * <p>The delivery this one replays.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage replayOf(Nullable<String> replayOf) {
            if (replayOf.isNull()) {
                this.replayOf = null;
            } else if (replayOf.isEmpty()) {
                this.replayOf = Optional.empty();
            } else {
                this.replayOf = Optional.of(replayOf.get());
            }
            return this;
        }

        /**
         * <p>The delivery this one replays.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage replayOf(String replayOf) {
            this.replayOf = Optional.ofNullable(replayOf);
            return this;
        }

        /**
         * <p>The delivery this one replays.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "replay_of", nulls = Nulls.SKIP)
        public _FinalStage replayOf(Optional<String> replayOf) {
            this.replayOf = replayOf;
            return this;
        }

        @java.lang.Override
        public WebhookDeliveryObject build() {
            return new WebhookDeliveryObject(
                    object,
                    id,
                    endpoint,
                    event,
                    eventType,
                    replayOf,
                    status,
                    attempts,
                    attemptLog,
                    nextAttemptAt,
                    request,
                    response,
                    error,
                    createdAt,
                    completedAt,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
