/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.Nullable;
import com.marketsdk.core.NullableNonemptyFilter;
import com.marketsdk.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = WebhookDeliveryList.Builder.class)
public final class WebhookDeliveryList {
    private final WebhookDeliveryListObject object;

    private final List<WebhookDeliveryObject> data;

    private final boolean hasMore;

    private final Optional<String> nextCursor;

    private final Map<String, Object> additionalProperties;

    private WebhookDeliveryList(
            WebhookDeliveryListObject object,
            List<WebhookDeliveryObject> data,
            boolean hasMore,
            Optional<String> nextCursor,
            Map<String, Object> additionalProperties) {
        this.object = object;
        this.data = data;
        this.hasMore = hasMore;
        this.nextCursor = nextCursor;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("object")
    public WebhookDeliveryListObject getObject() {
        return object;
    }

    @JsonProperty("data")
    public List<WebhookDeliveryObject> getData() {
        return data;
    }

    /**
     * @return Whether another page follows.
     */
    @JsonProperty("has_more")
    public boolean getHasMore() {
        return hasMore;
    }

    /**
     * @return Pass as <code>starting_after</code> (or <code>cursor</code> for search) to get the next page.
     */
    @JsonIgnore
    public Optional<String> getNextCursor() {
        if (nextCursor == null) {
            return Optional.empty();
        }
        return nextCursor;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("next_cursor")
    private Optional<String> _getNextCursor() {
        return nextCursor;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof WebhookDeliveryList && equalTo((WebhookDeliveryList) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(WebhookDeliveryList other) {
        return object.equals(other.object)
                && data.equals(other.data)
                && hasMore == other.hasMore
                && nextCursor.equals(other.nextCursor);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.object, this.data, this.hasMore, this.nextCursor);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ObjectStage builder() {
        return new Builder();
    }

    public interface ObjectStage {
        HasMoreStage object(@NotNull WebhookDeliveryListObject object);

        Builder from(WebhookDeliveryList other);
    }

    public interface HasMoreStage {
        /**
         * <p>Whether another page follows.</p>
         */
        _FinalStage hasMore(boolean hasMore);
    }

    public interface _FinalStage {
        WebhookDeliveryList build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage data(List<WebhookDeliveryObject> data);

        _FinalStage addData(WebhookDeliveryObject data);

        _FinalStage addAllData(List<WebhookDeliveryObject> data);

        /**
         * <p>Pass as <code>starting_after</code> (or <code>cursor</code> for search) to get the next page.</p>
         */
        _FinalStage nextCursor(Optional<String> nextCursor);

        _FinalStage nextCursor(String nextCursor);

        _FinalStage nextCursor(Nullable<String> nextCursor);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ObjectStage, HasMoreStage, _FinalStage {
        private WebhookDeliveryListObject object;

        private boolean hasMore;

        private Optional<String> nextCursor = Optional.empty();

        private List<WebhookDeliveryObject> data = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(WebhookDeliveryList other) {
            object(other.getObject());
            data(other.getData());
            hasMore(other.getHasMore());
            nextCursor(other.getNextCursor());
            return this;
        }

        @java.lang.Override
        @JsonSetter("object")
        public HasMoreStage object(@NotNull WebhookDeliveryListObject object) {
            this.object = Objects.requireNonNull(object, "object must not be null");
            return this;
        }

        /**
         * <p>Whether another page follows.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("has_more")
        public _FinalStage hasMore(boolean hasMore) {
            this.hasMore = hasMore;
            return this;
        }

        /**
         * <p>Pass as <code>starting_after</code> (or <code>cursor</code> for search) to get the next page.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage nextCursor(Nullable<String> nextCursor) {
            if (nextCursor.isNull()) {
                this.nextCursor = null;
            } else if (nextCursor.isEmpty()) {
                this.nextCursor = Optional.empty();
            } else {
                this.nextCursor = Optional.of(nextCursor.get());
            }
            return this;
        }

        /**
         * <p>Pass as <code>starting_after</code> (or <code>cursor</code> for search) to get the next page.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage nextCursor(String nextCursor) {
            this.nextCursor = Optional.ofNullable(nextCursor);
            return this;
        }

        /**
         * <p>Pass as <code>starting_after</code> (or <code>cursor</code> for search) to get the next page.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "next_cursor", nulls = Nulls.SKIP)
        public _FinalStage nextCursor(Optional<String> nextCursor) {
            this.nextCursor = nextCursor;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllData(List<WebhookDeliveryObject> data) {
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addData(WebhookDeliveryObject data) {
            this.data.add(data);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public _FinalStage data(List<WebhookDeliveryObject> data) {
            this.data.clear();
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @java.lang.Override
        public WebhookDeliveryList build() {
            return new WebhookDeliveryList(object, data, hasMore, nextCursor, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
