/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk;

import com.marketsdk.core.ClientOptions;
import com.marketsdk.core.Suppliers;
import com.marketsdk.resources.buyers.AsyncBuyersClient;
import com.marketsdk.resources.categories.AsyncCategoriesClient;
import com.marketsdk.resources.listings.AsyncListingsClient;
import com.marketsdk.resources.marketplace.AsyncMarketplaceClient;
import com.marketsdk.resources.moderation.AsyncModerationClient;
import com.marketsdk.resources.orders.AsyncOrdersClient;
import com.marketsdk.resources.payments.AsyncPaymentsClient;
import com.marketsdk.resources.reputation.AsyncReputationClient;
import com.marketsdk.resources.reviews.AsyncReviewsClient;
import com.marketsdk.resources.search.AsyncSearchClient;
import com.marketsdk.resources.sellers.AsyncSellersClient;
import com.marketsdk.resources.trust.AsyncTrustClient;
import com.marketsdk.resources.webhooks.AsyncWebhooksClient;
import java.util.function.Supplier;

public class AsyncMarketSDK implements AutoCloseable {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncMarketplaceClient> marketplaceClient;

    protected final Supplier<AsyncSellersClient> sellersClient;

    protected final Supplier<AsyncBuyersClient> buyersClient;

    protected final Supplier<AsyncCategoriesClient> categoriesClient;

    protected final Supplier<AsyncListingsClient> listingsClient;

    protected final Supplier<AsyncSearchClient> searchClient;

    protected final Supplier<AsyncOrdersClient> ordersClient;

    protected final Supplier<AsyncReviewsClient> reviewsClient;

    protected final Supplier<AsyncReputationClient> reputationClient;

    protected final Supplier<AsyncPaymentsClient> paymentsClient;

    protected final Supplier<AsyncTrustClient> trustClient;

    protected final Supplier<AsyncModerationClient> moderationClient;

    protected final Supplier<AsyncWebhooksClient> webhooksClient;

    public AsyncMarketSDK(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.marketplaceClient = Suppliers.memoize(() -> new AsyncMarketplaceClient(clientOptions));
        this.sellersClient = Suppliers.memoize(() -> new AsyncSellersClient(clientOptions));
        this.buyersClient = Suppliers.memoize(() -> new AsyncBuyersClient(clientOptions));
        this.categoriesClient = Suppliers.memoize(() -> new AsyncCategoriesClient(clientOptions));
        this.listingsClient = Suppliers.memoize(() -> new AsyncListingsClient(clientOptions));
        this.searchClient = Suppliers.memoize(() -> new AsyncSearchClient(clientOptions));
        this.ordersClient = Suppliers.memoize(() -> new AsyncOrdersClient(clientOptions));
        this.reviewsClient = Suppliers.memoize(() -> new AsyncReviewsClient(clientOptions));
        this.reputationClient = Suppliers.memoize(() -> new AsyncReputationClient(clientOptions));
        this.paymentsClient = Suppliers.memoize(() -> new AsyncPaymentsClient(clientOptions));
        this.trustClient = Suppliers.memoize(() -> new AsyncTrustClient(clientOptions));
        this.moderationClient = Suppliers.memoize(() -> new AsyncModerationClient(clientOptions));
        this.webhooksClient = Suppliers.memoize(() -> new AsyncWebhooksClient(clientOptions));
    }

    public AsyncMarketplaceClient marketplace() {
        return this.marketplaceClient.get();
    }

    public AsyncSellersClient sellers() {
        return this.sellersClient.get();
    }

    public AsyncBuyersClient buyers() {
        return this.buyersClient.get();
    }

    public AsyncCategoriesClient categories() {
        return this.categoriesClient.get();
    }

    public AsyncListingsClient listings() {
        return this.listingsClient.get();
    }

    public AsyncSearchClient search() {
        return this.searchClient.get();
    }

    public AsyncOrdersClient orders() {
        return this.ordersClient.get();
    }

    public AsyncReviewsClient reviews() {
        return this.reviewsClient.get();
    }

    public AsyncReputationClient reputation() {
        return this.reputationClient.get();
    }

    public AsyncPaymentsClient payments() {
        return this.paymentsClient.get();
    }

    public AsyncTrustClient trust() {
        return this.trustClient.get();
    }

    public AsyncModerationClient moderation() {
        return this.moderationClient.get();
    }

    public AsyncWebhooksClient webhooks() {
        return this.webhooksClient.get();
    }

    /**
     * Releases resources owned by this client: any WebSocket clients still connected through
     * it are disconnected first, then the SDK-owned HTTP client is shut down. See
     * {@code ClientOptions.close()} for what is and is not released.
     */
    @Override
    public void close() {
        this.clientOptions.close();
    }

    public static AsyncMarketSDKBuilder builder() {
        return new AsyncMarketSDKBuilder();
    }
}
