/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.resources.search;

import com.marketsdk.core.ClientOptions;
import com.marketsdk.core.RequestOptions;
import com.marketsdk.resources.search.requests.SearchListingsRequest;
import com.marketsdk.types.ListingList;

public class SearchClient {
    protected final ClientOptions clientOptions;

    private final RawSearchClient rawClient;

    public SearchClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawSearchClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawSearchClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Full text over title and description, with filters and sorting. Only published listings with something available are returned. Callable with a publishable key.
     */
    public ListingList searchListings() {
        return this.rawClient.searchListings().body();
    }

    /**
     * Full text over title and description, with filters and sorting. Only published listings with something available are returned. Callable with a publishable key.
     */
    public ListingList searchListings(RequestOptions requestOptions) {
        return this.rawClient.searchListings(requestOptions).body();
    }

    /**
     * Full text over title and description, with filters and sorting. Only published listings with something available are returned. Callable with a publishable key.
     */
    public ListingList searchListings(SearchListingsRequest request) {
        return this.rawClient.searchListings(request).body();
    }

    /**
     * Full text over title and description, with filters and sorting. Only published listings with something available are returned. Callable with a publishable key.
     */
    public ListingList searchListings(SearchListingsRequest request, RequestOptions requestOptions) {
        return this.rawClient.searchListings(request, requestOptions).body();
    }
}
