/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.resources.trust.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AddEvidenceDto.Builder.class)
public final class AddEvidenceDto {
    private final String actor;

    private final String body;

    private final Optional<List<String>> links;

    private final Map<String, Object> additionalProperties;

    private AddEvidenceDto(
            String actor, String body, Optional<List<String>> links, Map<String, Object> additionalProperties) {
        this.actor = actor;
        this.body = body;
        this.links = links;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The buyer or seller giving evidence.
     */
    @JsonProperty("actor")
    public String getActor() {
        return actor;
    }

    @JsonProperty("body")
    public String getBody() {
        return body;
    }

    /**
     * @return Links to files the party provided, such as photos you store. HTTPS only.
     */
    @JsonProperty("links")
    public Optional<List<String>> getLinks() {
        return links;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AddEvidenceDto && equalTo((AddEvidenceDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AddEvidenceDto other) {
        return actor.equals(other.actor) && body.equals(other.body) && links.equals(other.links);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.actor, this.body, this.links);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ActorStage builder() {
        return new Builder();
    }

    public interface ActorStage {
        /**
         * <p>The buyer or seller giving evidence.</p>
         */
        BodyStage actor(@NotNull String actor);

        Builder from(AddEvidenceDto other);
    }

    public interface BodyStage {
        _FinalStage body(@NotNull String body);
    }

    public interface _FinalStage {
        AddEvidenceDto build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Links to files the party provided, such as photos you store. HTTPS only.</p>
         */
        _FinalStage links(Optional<List<String>> links);

        _FinalStage links(List<String> links);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ActorStage, BodyStage, _FinalStage {
        private String actor;

        private String body;

        private Optional<List<String>> links = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AddEvidenceDto other) {
            actor(other.getActor());
            body(other.getBody());
            links(other.getLinks());
            return this;
        }

        /**
         * <p>The buyer or seller giving evidence.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("actor")
        public BodyStage actor(@NotNull String actor) {
            this.actor = Objects.requireNonNull(actor, "actor must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("body")
        public _FinalStage body(@NotNull String body) {
            this.body = Objects.requireNonNull(body, "body must not be null");
            return this;
        }

        /**
         * <p>Links to files the party provided, such as photos you store. HTTPS only.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage links(List<String> links) {
            this.links = Optional.ofNullable(links);
            return this;
        }

        /**
         * <p>Links to files the party provided, such as photos you store. HTTPS only.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "links", nulls = Nulls.SKIP)
        public _FinalStage links(Optional<List<String>> links) {
            this.links = links;
            return this;
        }

        @java.lang.Override
        public AddEvidenceDto build() {
            return new AddEvidenceDto(actor, body, links, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
