/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.resources.trust.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.ObjectMappers;
import com.marketsdk.resources.trust.types.DecideDisputeDtoAgainst;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DecideDisputeDto.Builder.class)
public final class DecideDisputeDto {
    private final DecideDisputeDtoAgainst against;

    private final String note;

    private final Optional<Double> refundAmount;

    private final Optional<String> decidedBy;

    private final Map<String, Object> additionalProperties;

    private DecideDisputeDto(
            DecideDisputeDtoAgainst against,
            String note,
            Optional<Double> refundAmount,
            Optional<String> decidedBy,
            Map<String, Object> additionalProperties) {
        this.against = against;
        this.note = note;
        this.refundAmount = refundAmount;
        this.decidedBy = decidedBy;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Who the decision went against. They get a dispute_lost reputation event; the other party gets dispute_won.
     */
    @JsonProperty("against")
    public DecideDisputeDtoAgainst getAgainst() {
        return against;
    }

    /**
     * @return The written decision, kept with the dispute.
     */
    @JsonProperty("note")
    public String getNote() {
        return note;
    }

    /**
     * @return Payments on only. Minor units to refund to the buyer; the rest goes to the seller. Defaults: a claimed order whose claim is upheld refunds nothing; one whose claim is rejected refunds everything; a dispute on a completed order refunds nothing.
     */
    @JsonProperty("refund_amount")
    public Optional<Double> getRefundAmount() {
        return refundAmount;
    }

    /**
     * @return Who on your team decided, for the record. Up to 200 characters.
     */
    @JsonProperty("decided_by")
    public Optional<String> getDecidedBy() {
        return decidedBy;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DecideDisputeDto && equalTo((DecideDisputeDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DecideDisputeDto other) {
        return against.equals(other.against)
                && note.equals(other.note)
                && refundAmount.equals(other.refundAmount)
                && decidedBy.equals(other.decidedBy);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.against, this.note, this.refundAmount, this.decidedBy);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AgainstStage builder() {
        return new Builder();
    }

    public interface AgainstStage {
        /**
         * <p>Who the decision went against. They get a dispute_lost reputation event; the other party gets dispute_won.</p>
         */
        NoteStage against(@NotNull DecideDisputeDtoAgainst against);

        Builder from(DecideDisputeDto other);
    }

    public interface NoteStage {
        /**
         * <p>The written decision, kept with the dispute.</p>
         */
        _FinalStage note(@NotNull String note);
    }

    public interface _FinalStage {
        DecideDisputeDto build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Payments on only. Minor units to refund to the buyer; the rest goes to the seller. Defaults: a claimed order whose claim is upheld refunds nothing; one whose claim is rejected refunds everything; a dispute on a completed order refunds nothing.</p>
         */
        _FinalStage refundAmount(Optional<Double> refundAmount);

        _FinalStage refundAmount(Double refundAmount);

        /**
         * <p>Who on your team decided, for the record. Up to 200 characters.</p>
         */
        _FinalStage decidedBy(Optional<String> decidedBy);

        _FinalStage decidedBy(String decidedBy);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AgainstStage, NoteStage, _FinalStage {
        private DecideDisputeDtoAgainst against;

        private String note;

        private Optional<String> decidedBy = Optional.empty();

        private Optional<Double> refundAmount = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DecideDisputeDto other) {
            against(other.getAgainst());
            note(other.getNote());
            refundAmount(other.getRefundAmount());
            decidedBy(other.getDecidedBy());
            return this;
        }

        /**
         * <p>Who the decision went against. They get a dispute_lost reputation event; the other party gets dispute_won.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("against")
        public NoteStage against(@NotNull DecideDisputeDtoAgainst against) {
            this.against = Objects.requireNonNull(against, "against must not be null");
            return this;
        }

        /**
         * <p>The written decision, kept with the dispute.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("note")
        public _FinalStage note(@NotNull String note) {
            this.note = Objects.requireNonNull(note, "note must not be null");
            return this;
        }

        /**
         * <p>Who on your team decided, for the record. Up to 200 characters.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage decidedBy(String decidedBy) {
            this.decidedBy = Optional.ofNullable(decidedBy);
            return this;
        }

        /**
         * <p>Who on your team decided, for the record. Up to 200 characters.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "decided_by", nulls = Nulls.SKIP)
        public _FinalStage decidedBy(Optional<String> decidedBy) {
            this.decidedBy = decidedBy;
            return this;
        }

        /**
         * <p>Payments on only. Minor units to refund to the buyer; the rest goes to the seller. Defaults: a claimed order whose claim is upheld refunds nothing; one whose claim is rejected refunds everything; a dispute on a completed order refunds nothing.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage refundAmount(Double refundAmount) {
            this.refundAmount = Optional.ofNullable(refundAmount);
            return this;
        }

        /**
         * <p>Payments on only. Minor units to refund to the buyer; the rest goes to the seller. Defaults: a claimed order whose claim is upheld refunds nothing; one whose claim is rejected refunds everything; a dispute on a completed order refunds nothing.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "refund_amount", nulls = Nulls.SKIP)
        public _FinalStage refundAmount(Optional<Double> refundAmount) {
            this.refundAmount = refundAmount;
            return this;
        }

        @java.lang.Override
        public DecideDisputeDto build() {
            return new DecideDisputeDto(against, note, refundAmount, decidedBy, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
