/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.resources.moderation.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreateModerationActionDtoAction {
    public static final CreateModerationActionDtoAction SUSPEND_SELLER =
            new CreateModerationActionDtoAction(Value.SUSPEND_SELLER, "suspend_seller");

    public static final CreateModerationActionDtoAction DISMISS =
            new CreateModerationActionDtoAction(Value.DISMISS, "dismiss");

    public static final CreateModerationActionDtoAction REMOVE_CONTENT =
            new CreateModerationActionDtoAction(Value.REMOVE_CONTENT, "remove_content");

    public static final CreateModerationActionDtoAction REINSTATE_SELLER =
            new CreateModerationActionDtoAction(Value.REINSTATE_SELLER, "reinstate_seller");

    private final Value value;

    private final String string;

    CreateModerationActionDtoAction(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CreateModerationActionDtoAction
                        && this.string.equals(((CreateModerationActionDtoAction) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SUSPEND_SELLER:
                return visitor.visitSuspendSeller();
            case DISMISS:
                return visitor.visitDismiss();
            case REMOVE_CONTENT:
                return visitor.visitRemoveContent();
            case REINSTATE_SELLER:
                return visitor.visitReinstateSeller();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreateModerationActionDtoAction valueOf(String value) {
        switch (value) {
            case "suspend_seller":
                return SUSPEND_SELLER;
            case "dismiss":
                return DISMISS;
            case "remove_content":
                return REMOVE_CONTENT;
            case "reinstate_seller":
                return REINSTATE_SELLER;
            default:
                return new CreateModerationActionDtoAction(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DISMISS,

        REMOVE_CONTENT,

        SUSPEND_SELLER,

        REINSTATE_SELLER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDismiss();

        T visitRemoveContent();

        T visitSuspendSeller();

        T visitReinstateSeller();

        T visitUnknown(String unknownType);
    }
}
