/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.resources.payments;

import com.marketsdk.core.ClientOptions;
import com.marketsdk.core.RequestOptions;
import com.marketsdk.resources.payments.requests.CreateRefundDto;
import com.marketsdk.resources.payments.requests.GetPaymentRequest;
import com.marketsdk.resources.payments.requests.GetRefundRequest;
import com.marketsdk.resources.payments.requests.ListPaymentsRequest;
import com.marketsdk.resources.payments.requests.ListRefundsRequest;
import com.marketsdk.resources.payments.requests.RetryPaymentReleaseRequest;
import com.marketsdk.resources.payments.requests.UpdatePaymentRequest;
import com.marketsdk.resources.payments.requests.UpdateRefundRequest;
import com.marketsdk.types.PaymentList;
import com.marketsdk.types.PaymentObject;
import com.marketsdk.types.RefundList;
import com.marketsdk.types.RefundObject;

public class PaymentsClient {
    protected final ClientOptions clientOptions;

    private final RawPaymentsClient rawClient;

    public PaymentsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawPaymentsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawPaymentsClient withRawResponse() {
        return this.rawClient;
    }

    public PaymentList listPayments() {
        return this.rawClient.listPayments().body();
    }

    public PaymentList listPayments(RequestOptions requestOptions) {
        return this.rawClient.listPayments(requestOptions).body();
    }

    public PaymentList listPayments(ListPaymentsRequest request) {
        return this.rawClient.listPayments(request).body();
    }

    public PaymentList listPayments(ListPaymentsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listPayments(request, requestOptions).body();
    }

    public PaymentObject getPayment(String id) {
        return this.rawClient.getPayment(id).body();
    }

    public PaymentObject getPayment(String id, RequestOptions requestOptions) {
        return this.rawClient.getPayment(id, requestOptions).body();
    }

    public PaymentObject getPayment(String id, GetPaymentRequest request) {
        return this.rawClient.getPayment(id, request).body();
    }

    public PaymentObject getPayment(String id, GetPaymentRequest request, RequestOptions requestOptions) {
        return this.rawClient.getPayment(id, request, requestOptions).body();
    }

    public PaymentObject updatePayment(String id, UpdatePaymentRequest request) {
        return this.rawClient.updatePayment(id, request).body();
    }

    public PaymentObject updatePayment(String id, UpdatePaymentRequest request, RequestOptions requestOptions) {
        return this.rawClient.updatePayment(id, request, requestOptions).body();
    }

    /**
     * For a release that failed, for example because the seller could not yet receive transfers. A release is also tried again by itself when the seller becomes able to receive payouts.
     */
    public PaymentObject retryPaymentRelease(String id) {
        return this.rawClient.retryPaymentRelease(id).body();
    }

    /**
     * For a release that failed, for example because the seller could not yet receive transfers. A release is also tried again by itself when the seller becomes able to receive payouts.
     */
    public PaymentObject retryPaymentRelease(String id, RequestOptions requestOptions) {
        return this.rawClient.retryPaymentRelease(id, requestOptions).body();
    }

    /**
     * For a release that failed, for example because the seller could not yet receive transfers. A release is also tried again by itself when the seller becomes able to receive payouts.
     */
    public PaymentObject retryPaymentRelease(String id, RetryPaymentReleaseRequest request) {
        return this.rawClient.retryPaymentRelease(id, request).body();
    }

    /**
     * For a release that failed, for example because the seller could not yet receive transfers. A release is also tried again by itself when the seller becomes able to receive payouts.
     */
    public PaymentObject retryPaymentRelease(
            String id, RetryPaymentReleaseRequest request, RequestOptions requestOptions) {
        return this.rawClient.retryPaymentRelease(id, request, requestOptions).body();
    }

    public RefundList listRefunds() {
        return this.rawClient.listRefunds().body();
    }

    public RefundList listRefunds(RequestOptions requestOptions) {
        return this.rawClient.listRefunds(requestOptions).body();
    }

    public RefundList listRefunds(ListRefundsRequest request) {
        return this.rawClient.listRefunds(request).body();
    }

    public RefundList listRefunds(ListRefundsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listRefunds(request, requestOptions).body();
    }

    /**
     * Recorded at once with status <code>pending</code>, then made at Stripe. If the seller's share was already released, the transfer is reversed in the same proportion, so your fee is given back in proportion too.
     */
    public RefundObject createRefund() {
        return this.rawClient.createRefund().body();
    }

    /**
     * Recorded at once with status <code>pending</code>, then made at Stripe. If the seller's share was already released, the transfer is reversed in the same proportion, so your fee is given back in proportion too.
     */
    public RefundObject createRefund(RequestOptions requestOptions) {
        return this.rawClient.createRefund(requestOptions).body();
    }

    /**
     * Recorded at once with status <code>pending</code>, then made at Stripe. If the seller's share was already released, the transfer is reversed in the same proportion, so your fee is given back in proportion too.
     */
    public RefundObject createRefund(CreateRefundDto request) {
        return this.rawClient.createRefund(request).body();
    }

    /**
     * Recorded at once with status <code>pending</code>, then made at Stripe. If the seller's share was already released, the transfer is reversed in the same proportion, so your fee is given back in proportion too.
     */
    public RefundObject createRefund(CreateRefundDto request, RequestOptions requestOptions) {
        return this.rawClient.createRefund(request, requestOptions).body();
    }

    public RefundObject getRefund(String id) {
        return this.rawClient.getRefund(id).body();
    }

    public RefundObject getRefund(String id, RequestOptions requestOptions) {
        return this.rawClient.getRefund(id, requestOptions).body();
    }

    public RefundObject getRefund(String id, GetRefundRequest request) {
        return this.rawClient.getRefund(id, request).body();
    }

    public RefundObject getRefund(String id, GetRefundRequest request, RequestOptions requestOptions) {
        return this.rawClient.getRefund(id, request, requestOptions).body();
    }

    public RefundObject updateRefund(String id, UpdateRefundRequest request) {
        return this.rawClient.updateRefund(id, request).body();
    }

    public RefundObject updateRefund(String id, UpdateRefundRequest request, RequestOptions requestOptions) {
        return this.rawClient.updateRefund(id, request, requestOptions).body();
    }
}
