/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.resources.payments;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.marketsdk.core.BodyProperties;
import com.marketsdk.core.ClientOptions;
import com.marketsdk.core.MarketSDKApiException;
import com.marketsdk.core.MarketSDKException;
import com.marketsdk.core.MarketSDKHttpResponse;
import com.marketsdk.core.MediaTypes;
import com.marketsdk.core.ObjectMappers;
import com.marketsdk.core.QueryStringMapper;
import com.marketsdk.core.RequestOptions;
import com.marketsdk.core.RetryInterceptor;
import com.marketsdk.errors.BadRequestError;
import com.marketsdk.errors.ConflictError;
import com.marketsdk.errors.NotFoundError;
import com.marketsdk.errors.TooManyRequestsError;
import com.marketsdk.errors.UnauthorizedError;
import com.marketsdk.resources.payments.requests.CreateRefundDto;
import com.marketsdk.resources.payments.requests.GetPaymentRequest;
import com.marketsdk.resources.payments.requests.GetRefundRequest;
import com.marketsdk.resources.payments.requests.ListPaymentsRequest;
import com.marketsdk.resources.payments.requests.ListRefundsRequest;
import com.marketsdk.resources.payments.requests.RetryPaymentReleaseRequest;
import com.marketsdk.resources.payments.requests.UpdatePaymentRequest;
import com.marketsdk.resources.payments.requests.UpdateRefundRequest;
import com.marketsdk.types.ErrorEnvelope;
import com.marketsdk.types.PaymentList;
import com.marketsdk.types.PaymentObject;
import com.marketsdk.types.RefundList;
import com.marketsdk.types.RefundObject;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawPaymentsClient {
    protected final ClientOptions clientOptions;

    public RawPaymentsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public MarketSDKHttpResponse<PaymentList> listPayments() {
        return listPayments(ListPaymentsRequest.builder().build());
    }

    public MarketSDKHttpResponse<PaymentList> listPayments(RequestOptions requestOptions) {
        return listPayments(ListPaymentsRequest.builder().build(), requestOptions);
    }

    public MarketSDKHttpResponse<PaymentList> listPayments(ListPaymentsRequest request) {
        return listPayments(request, null);
    }

    public MarketSDKHttpResponse<PaymentList> listPayments(ListPaymentsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/payments");
        if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limit", request.getLimit().get(), false);
        }
        if (request.getStartingAfter().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "starting_after", request.getStartingAfter().get(), false);
        }
        if (request.getOrder().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "order", request.getOrder().get(), false);
        }
        if (request.getStatus().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "status", request.getStatus().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MarketSDKHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaymentList.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MarketSDKApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MarketSDKException("Network error executing HTTP request", e);
        }
    }

    public MarketSDKHttpResponse<PaymentObject> getPayment(String id) {
        return getPayment(id, GetPaymentRequest.builder().build());
    }

    public MarketSDKHttpResponse<PaymentObject> getPayment(String id, RequestOptions requestOptions) {
        return getPayment(id, GetPaymentRequest.builder().build(), requestOptions);
    }

    public MarketSDKHttpResponse<PaymentObject> getPayment(String id, GetPaymentRequest request) {
        return getPayment(id, request, null);
    }

    public MarketSDKHttpResponse<PaymentObject> getPayment(
            String id, GetPaymentRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/payments")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MarketSDKHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaymentObject.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MarketSDKApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MarketSDKException("Network error executing HTTP request", e);
        }
    }

    public MarketSDKHttpResponse<PaymentObject> updatePayment(String id, UpdatePaymentRequest request) {
        return updatePayment(id, request, null);
    }

    public MarketSDKHttpResponse<PaymentObject> updatePayment(
            String id, UpdatePaymentRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/payments")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(BodyProperties.merge(
                            request.getBody(), requestOptions != null ? requestOptions.getBodyProperties() : null)),
                    MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MarketSDKHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaymentObject.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MarketSDKApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MarketSDKException("Network error executing HTTP request", e);
        }
    }

    /**
     * For a release that failed, for example because the seller could not yet receive transfers. A release is also tried again by itself when the seller becomes able to receive payouts.
     */
    public MarketSDKHttpResponse<PaymentObject> retryPaymentRelease(String id) {
        return retryPaymentRelease(id, RetryPaymentReleaseRequest.builder().build());
    }

    /**
     * For a release that failed, for example because the seller could not yet receive transfers. A release is also tried again by itself when the seller becomes able to receive payouts.
     */
    public MarketSDKHttpResponse<PaymentObject> retryPaymentRelease(String id, RequestOptions requestOptions) {
        return retryPaymentRelease(id, RetryPaymentReleaseRequest.builder().build(), requestOptions);
    }

    /**
     * For a release that failed, for example because the seller could not yet receive transfers. A release is also tried again by itself when the seller becomes able to receive payouts.
     */
    public MarketSDKHttpResponse<PaymentObject> retryPaymentRelease(String id, RetryPaymentReleaseRequest request) {
        return retryPaymentRelease(id, request, null);
    }

    /**
     * For a release that failed, for example because the seller could not yet receive transfers. A release is also tried again by itself when the seller becomes able to receive payouts.
     */
    public MarketSDKHttpResponse<PaymentObject> retryPaymentRelease(
            String id, RetryPaymentReleaseRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/payments")
                .addPathSegment(id)
                .addPathSegments("retry_release");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method(
                        "POST",
                        BodyProperties.toRequestBody(
                                requestOptions != null ? requestOptions.getBodyProperties() : null,
                                RequestBody.create("", null)))
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MarketSDKHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaymentObject.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 409:
                        throw new ConflictError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MarketSDKApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MarketSDKException("Network error executing HTTP request", e);
        }
    }

    public MarketSDKHttpResponse<RefundList> listRefunds() {
        return listRefunds(ListRefundsRequest.builder().build());
    }

    public MarketSDKHttpResponse<RefundList> listRefunds(RequestOptions requestOptions) {
        return listRefunds(ListRefundsRequest.builder().build(), requestOptions);
    }

    public MarketSDKHttpResponse<RefundList> listRefunds(ListRefundsRequest request) {
        return listRefunds(request, null);
    }

    public MarketSDKHttpResponse<RefundList> listRefunds(ListRefundsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/refunds");
        if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limit", request.getLimit().get(), false);
        }
        if (request.getStartingAfter().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "starting_after", request.getStartingAfter().get(), false);
        }
        if (request.getPayment().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "payment", request.getPayment().get(), false);
        }
        if (request.getOrder().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "order", request.getOrder().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MarketSDKHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RefundList.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MarketSDKApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MarketSDKException("Network error executing HTTP request", e);
        }
    }

    /**
     * Recorded at once with status <code>pending</code>, then made at Stripe. If the seller's share was already released, the transfer is reversed in the same proportion, so your fee is given back in proportion too.
     */
    public MarketSDKHttpResponse<RefundObject> createRefund() {
        return createRefund(CreateRefundDto.builder().build());
    }

    /**
     * Recorded at once with status <code>pending</code>, then made at Stripe. If the seller's share was already released, the transfer is reversed in the same proportion, so your fee is given back in proportion too.
     */
    public MarketSDKHttpResponse<RefundObject> createRefund(RequestOptions requestOptions) {
        return createRefund(CreateRefundDto.builder().build(), requestOptions);
    }

    /**
     * Recorded at once with status <code>pending</code>, then made at Stripe. If the seller's share was already released, the transfer is reversed in the same proportion, so your fee is given back in proportion too.
     */
    public MarketSDKHttpResponse<RefundObject> createRefund(CreateRefundDto request) {
        return createRefund(request, null);
    }

    /**
     * Recorded at once with status <code>pending</code>, then made at Stripe. If the seller's share was already released, the transfer is reversed in the same proportion, so your fee is given back in proportion too.
     */
    public MarketSDKHttpResponse<RefundObject> createRefund(CreateRefundDto request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/refunds");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(BodyProperties.merge(
                            request, requestOptions != null ? requestOptions.getBodyProperties() : null)),
                    MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MarketSDKHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RefundObject.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 409:
                        throw new ConflictError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MarketSDKApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MarketSDKException("Network error executing HTTP request", e);
        }
    }

    public MarketSDKHttpResponse<RefundObject> getRefund(String id) {
        return getRefund(id, GetRefundRequest.builder().build());
    }

    public MarketSDKHttpResponse<RefundObject> getRefund(String id, RequestOptions requestOptions) {
        return getRefund(id, GetRefundRequest.builder().build(), requestOptions);
    }

    public MarketSDKHttpResponse<RefundObject> getRefund(String id, GetRefundRequest request) {
        return getRefund(id, request, null);
    }

    public MarketSDKHttpResponse<RefundObject> getRefund(
            String id, GetRefundRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/refunds")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MarketSDKHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RefundObject.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MarketSDKApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MarketSDKException("Network error executing HTTP request", e);
        }
    }

    public MarketSDKHttpResponse<RefundObject> updateRefund(String id, UpdateRefundRequest request) {
        return updateRefund(id, request, null);
    }

    public MarketSDKHttpResponse<RefundObject> updateRefund(
            String id, UpdateRefundRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/refunds")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(BodyProperties.merge(
                            request.getBody(), requestOptions != null ? requestOptions.getBodyProperties() : null)),
                    MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MarketSDKHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RefundObject.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MarketSDKApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MarketSDKException("Network error executing HTTP request", e);
        }
    }
}
