/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.resources.moderation.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.ObjectMappers;
import com.marketsdk.resources.moderation.types.ListFlagsRequestStatus;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListFlagsRequest.Builder.class)
public final class ListFlagsRequest {
    private final Optional<Double> limit;

    private final Optional<String> startingAfter;

    private final Optional<ListFlagsRequestStatus> status;

    private final Optional<String> target;

    private final Map<String, Object> additionalProperties;

    private ListFlagsRequest(
            Optional<Double> limit,
            Optional<String> startingAfter,
            Optional<ListFlagsRequestStatus> status,
            Optional<String> target,
            Map<String, Object> additionalProperties) {
        this.limit = limit;
        this.startingAfter = startingAfter;
        this.status = status;
        this.target = target;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("limit")
    public Optional<Double> getLimit() {
        return limit;
    }

    /**
     * @return The <code>next_cursor</code> of the previous page.
     */
    @JsonProperty("starting_after")
    public Optional<String> getStartingAfter() {
        return startingAfter;
    }

    @JsonProperty("status")
    public Optional<ListFlagsRequestStatus> getStatus() {
        return status;
    }

    /**
     * @return Only flags on this listing, seller, or review.
     */
    @JsonProperty("target")
    public Optional<String> getTarget() {
        return target;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListFlagsRequest && equalTo((ListFlagsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListFlagsRequest other) {
        return limit.equals(other.limit)
                && startingAfter.equals(other.startingAfter)
                && status.equals(other.status)
                && target.equals(other.target);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.limit, this.startingAfter, this.status, this.target);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Double> limit = Optional.empty();

        private Optional<String> startingAfter = Optional.empty();

        private Optional<ListFlagsRequestStatus> status = Optional.empty();

        private Optional<String> target = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListFlagsRequest other) {
            limit(other.getLimit());
            startingAfter(other.getStartingAfter());
            status(other.getStatus());
            target(other.getTarget());
            return this;
        }

        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Double> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Double limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>The <code>next_cursor</code> of the previous page.</p>
         */
        @JsonSetter(value = "starting_after", nulls = Nulls.SKIP)
        public Builder startingAfter(Optional<String> startingAfter) {
            this.startingAfter = startingAfter;
            return this;
        }

        public Builder startingAfter(String startingAfter) {
            this.startingAfter = Optional.ofNullable(startingAfter);
            return this;
        }

        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<ListFlagsRequestStatus> status) {
            this.status = status;
            return this;
        }

        public Builder status(ListFlagsRequestStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * <p>Only flags on this listing, seller, or review.</p>
         */
        @JsonSetter(value = "target", nulls = Nulls.SKIP)
        public Builder target(Optional<String> target) {
            this.target = target;
            return this;
        }

        public Builder target(String target) {
            this.target = Optional.ofNullable(target);
            return this;
        }

        public ListFlagsRequest build() {
            return new ListFlagsRequest(limit, startingAfter, status, target, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
