/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.resources.listings.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.ObjectMappers;
import com.marketsdk.resources.listings.types.CreateMediaDtoContentType;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateMediaDto.Builder.class)
public final class CreateMediaDto {
    private final CreateMediaDtoContentType contentType;

    private final double sizeBytes;

    private final Optional<Double> position;

    private final Map<String, Object> additionalProperties;

    private CreateMediaDto(
            CreateMediaDtoContentType contentType,
            double sizeBytes,
            Optional<Double> position,
            Map<String, Object> additionalProperties) {
        this.contentType = contentType;
        this.sizeBytes = sizeBytes;
        this.position = position;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("content_type")
    public CreateMediaDtoContentType getContentType() {
        return contentType;
    }

    /**
     * @return The exact size of the file, in bytes. At most 10 MB.
     */
    @JsonProperty("size_bytes")
    public double getSizeBytes() {
        return sizeBytes;
    }

    @JsonProperty("position")
    public Optional<Double> getPosition() {
        return position;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateMediaDto && equalTo((CreateMediaDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateMediaDto other) {
        return contentType.equals(other.contentType) && sizeBytes == other.sizeBytes && position.equals(other.position);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.contentType, this.sizeBytes, this.position);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ContentTypeStage builder() {
        return new Builder();
    }

    public interface ContentTypeStage {
        SizeBytesStage contentType(@NotNull CreateMediaDtoContentType contentType);

        Builder from(CreateMediaDto other);
    }

    public interface SizeBytesStage {
        /**
         * <p>The exact size of the file, in bytes. At most 10 MB.</p>
         */
        _FinalStage sizeBytes(double sizeBytes);
    }

    public interface _FinalStage {
        CreateMediaDto build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage position(Optional<Double> position);

        _FinalStage position(Double position);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ContentTypeStage, SizeBytesStage, _FinalStage {
        private CreateMediaDtoContentType contentType;

        private double sizeBytes;

        private Optional<Double> position = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateMediaDto other) {
            contentType(other.getContentType());
            sizeBytes(other.getSizeBytes());
            position(other.getPosition());
            return this;
        }

        @java.lang.Override
        @JsonSetter("content_type")
        public SizeBytesStage contentType(@NotNull CreateMediaDtoContentType contentType) {
            this.contentType = Objects.requireNonNull(contentType, "contentType must not be null");
            return this;
        }

        /**
         * <p>The exact size of the file, in bytes. At most 10 MB.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("size_bytes")
        public _FinalStage sizeBytes(double sizeBytes) {
            this.sizeBytes = sizeBytes;
            return this;
        }

        @java.lang.Override
        public _FinalStage position(Double position) {
            this.position = Optional.ofNullable(position);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "position", nulls = Nulls.SKIP)
        public _FinalStage position(Optional<Double> position) {
            this.position = position;
            return this;
        }

        @java.lang.Override
        public CreateMediaDto build() {
            return new CreateMediaDto(contentType, sizeBytes, position, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
