/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.resources.sellers;

import com.marketsdk.core.ClientOptions;
import com.marketsdk.core.MarketSDKHttpResponse;
import com.marketsdk.core.RequestOptions;
import com.marketsdk.resources.sellers.requests.EraseSellerRequest;
import com.marketsdk.resources.sellers.requests.GetSellerProfileRequest;
import com.marketsdk.resources.sellers.requests.GetSellerRequest;
import com.marketsdk.resources.sellers.requests.ListSellersRequest;
import com.marketsdk.resources.sellers.requests.OnboardingLinkDto;
import com.marketsdk.resources.sellers.requests.StorefrontDto;
import com.marketsdk.resources.sellers.requests.UpdateSellerRequest;
import com.marketsdk.types.CreatePartyDto;
import com.marketsdk.types.OnboardingLinkObject;
import com.marketsdk.types.SellerList;
import com.marketsdk.types.SellerObject;
import com.marketsdk.types.SellerProfileObject;
import com.marketsdk.types.StorefrontObject;
import java.util.concurrent.CompletableFuture;

public class AsyncSellersClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawSellersClient rawClient;

    public AsyncSellersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawSellersClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawSellersClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<SellerList> listSellers() {
        CompletableFuture<MarketSDKHttpResponse<SellerList>> rawFuture = this.rawClient.listSellers();
        CompletableFuture<SellerList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<SellerList> listSellers(RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<SellerList>> rawFuture = this.rawClient.listSellers(requestOptions);
        CompletableFuture<SellerList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<SellerList> listSellers(ListSellersRequest request) {
        CompletableFuture<MarketSDKHttpResponse<SellerList>> rawFuture = this.rawClient.listSellers(request);
        CompletableFuture<SellerList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<SellerList> listSellers(ListSellersRequest request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<SellerList>> rawFuture =
                this.rawClient.listSellers(request, requestOptions);
        CompletableFuture<SellerList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<SellerObject> createSeller(CreatePartyDto request) {
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> rawFuture = this.rawClient.createSeller(request);
        CompletableFuture<SellerObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<SellerObject> createSeller(CreatePartyDto request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> rawFuture =
                this.rawClient.createSeller(request, requestOptions);
        CompletableFuture<SellerObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<SellerObject> getSeller(String id) {
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> rawFuture = this.rawClient.getSeller(id);
        CompletableFuture<SellerObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<SellerObject> getSeller(String id, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> rawFuture = this.rawClient.getSeller(id, requestOptions);
        CompletableFuture<SellerObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<SellerObject> getSeller(String id, GetSellerRequest request) {
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> rawFuture = this.rawClient.getSeller(id, request);
        CompletableFuture<SellerObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<SellerObject> getSeller(
            String id, GetSellerRequest request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> rawFuture =
                this.rawClient.getSeller(id, request, requestOptions);
        CompletableFuture<SellerObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Removes the name, external id, metadata, storefront, and review text, and takes the listings down. Orders and reputation stay, without personal data.
     */
    public CompletableFuture<SellerObject> eraseSeller(String id) {
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> rawFuture = this.rawClient.eraseSeller(id);
        CompletableFuture<SellerObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Removes the name, external id, metadata, storefront, and review text, and takes the listings down. Orders and reputation stay, without personal data.
     */
    public CompletableFuture<SellerObject> eraseSeller(String id, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> rawFuture =
                this.rawClient.eraseSeller(id, requestOptions);
        CompletableFuture<SellerObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Removes the name, external id, metadata, storefront, and review text, and takes the listings down. Orders and reputation stay, without personal data.
     */
    public CompletableFuture<SellerObject> eraseSeller(String id, EraseSellerRequest request) {
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> rawFuture = this.rawClient.eraseSeller(id, request);
        CompletableFuture<SellerObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Removes the name, external id, metadata, storefront, and review text, and takes the listings down. Orders and reputation stay, without personal data.
     */
    public CompletableFuture<SellerObject> eraseSeller(
            String id, EraseSellerRequest request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> rawFuture =
                this.rawClient.eraseSeller(id, request, requestOptions);
        CompletableFuture<SellerObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<SellerObject> updateSeller(String id, UpdateSellerRequest request) {
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> rawFuture = this.rawClient.updateSeller(id, request);
        CompletableFuture<SellerObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<SellerObject> updateSeller(
            String id, UpdateSellerRequest request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> rawFuture =
                this.rawClient.updateSeller(id, request, requestOptions);
        CompletableFuture<SellerObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<StorefrontObject> putStorefront(String id, StorefrontDto request) {
        CompletableFuture<MarketSDKHttpResponse<StorefrontObject>> rawFuture =
                this.rawClient.putStorefront(id, request);
        CompletableFuture<StorefrontObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<StorefrontObject> putStorefront(
            String id, StorefrontDto request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<StorefrontObject>> rawFuture =
                this.rawClient.putStorefront(id, request, requestOptions);
        CompletableFuture<StorefrontObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * The first link creates the seller's connected account on your Stripe account: Express, with Stripe collecting what the law requires, your platform paying Stripe's fees and bearing losses, and only transfers requested. Send the seller to the link; their payouts status follows as Stripe reports it.
     */
    public CompletableFuture<OnboardingLinkObject> createOnboardingLink(String id, OnboardingLinkDto request) {
        CompletableFuture<MarketSDKHttpResponse<OnboardingLinkObject>> rawFuture =
                this.rawClient.createOnboardingLink(id, request);
        CompletableFuture<OnboardingLinkObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * The first link creates the seller's connected account on your Stripe account: Express, with Stripe collecting what the law requires, your platform paying Stripe's fees and bearing losses, and only transfers requested. Send the seller to the link; their payouts status follows as Stripe reports it.
     */
    public CompletableFuture<OnboardingLinkObject> createOnboardingLink(
            String id, OnboardingLinkDto request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<OnboardingLinkObject>> rawFuture =
                this.rawClient.createOnboardingLink(id, request, requestOptions);
        CompletableFuture<OnboardingLinkObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Callable with a publishable key. Shows only what a buyer may see.
     */
    public CompletableFuture<SellerProfileObject> getSellerProfile(String id) {
        CompletableFuture<MarketSDKHttpResponse<SellerProfileObject>> rawFuture = this.rawClient.getSellerProfile(id);
        CompletableFuture<SellerProfileObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Callable with a publishable key. Shows only what a buyer may see.
     */
    public CompletableFuture<SellerProfileObject> getSellerProfile(String id, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<SellerProfileObject>> rawFuture =
                this.rawClient.getSellerProfile(id, requestOptions);
        CompletableFuture<SellerProfileObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Callable with a publishable key. Shows only what a buyer may see.
     */
    public CompletableFuture<SellerProfileObject> getSellerProfile(String id, GetSellerProfileRequest request) {
        CompletableFuture<MarketSDKHttpResponse<SellerProfileObject>> rawFuture =
                this.rawClient.getSellerProfile(id, request);
        CompletableFuture<SellerProfileObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * Callable with a publishable key. Shows only what a buyer may see.
     */
    public CompletableFuture<SellerProfileObject> getSellerProfile(
            String id, GetSellerProfileRequest request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<SellerProfileObject>> rawFuture =
                this.rawClient.getSellerProfile(id, request, requestOptions);
        CompletableFuture<SellerProfileObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }
}
