/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.resources.sellers;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.marketsdk.core.BodyProperties;
import com.marketsdk.core.ClientOptions;
import com.marketsdk.core.MarketSDKApiException;
import com.marketsdk.core.MarketSDKException;
import com.marketsdk.core.MarketSDKHttpResponse;
import com.marketsdk.core.MediaTypes;
import com.marketsdk.core.ObjectMappers;
import com.marketsdk.core.QueryStringMapper;
import com.marketsdk.core.RequestOptions;
import com.marketsdk.core.RetryInterceptor;
import com.marketsdk.errors.BadRequestError;
import com.marketsdk.errors.ConflictError;
import com.marketsdk.errors.ForbiddenError;
import com.marketsdk.errors.NotFoundError;
import com.marketsdk.errors.TooManyRequestsError;
import com.marketsdk.errors.UnauthorizedError;
import com.marketsdk.resources.sellers.requests.EraseSellerRequest;
import com.marketsdk.resources.sellers.requests.GetSellerProfileRequest;
import com.marketsdk.resources.sellers.requests.GetSellerRequest;
import com.marketsdk.resources.sellers.requests.ListSellersRequest;
import com.marketsdk.resources.sellers.requests.OnboardingLinkDto;
import com.marketsdk.resources.sellers.requests.StorefrontDto;
import com.marketsdk.resources.sellers.requests.UpdateSellerRequest;
import com.marketsdk.types.CreatePartyDto;
import com.marketsdk.types.ErrorEnvelope;
import com.marketsdk.types.OnboardingLinkObject;
import com.marketsdk.types.SellerList;
import com.marketsdk.types.SellerObject;
import com.marketsdk.types.SellerProfileObject;
import com.marketsdk.types.StorefrontObject;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawSellersClient {
    protected final ClientOptions clientOptions;

    public AsyncRawSellersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public CompletableFuture<MarketSDKHttpResponse<SellerList>> listSellers() {
        return listSellers(ListSellersRequest.builder().build());
    }

    public CompletableFuture<MarketSDKHttpResponse<SellerList>> listSellers(RequestOptions requestOptions) {
        return listSellers(ListSellersRequest.builder().build(), requestOptions);
    }

    public CompletableFuture<MarketSDKHttpResponse<SellerList>> listSellers(ListSellersRequest request) {
        return listSellers(request, null);
    }

    public CompletableFuture<MarketSDKHttpResponse<SellerList>> listSellers(
            ListSellersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/sellers");
        if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limit", request.getLimit().get(), false);
        }
        if (request.getStartingAfter().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "starting_after", request.getStartingAfter().get(), false);
        }
        if (request.getExternalId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "external_id", request.getExternalId().get(), false);
        }
        if (request.getStatus().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "status", request.getStatus().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<MarketSDKHttpResponse<SellerList>> future = new CompletableFuture<>();
        Call okhttpCall = client.newCall(okhttpRequest);
        okhttpCall.enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new MarketSDKHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SellerList.class), response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MarketSDKApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
            }
        });
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                okhttpCall.cancel();
            }
        });
        return future;
    }

    public CompletableFuture<MarketSDKHttpResponse<SellerObject>> createSeller(CreatePartyDto request) {
        return createSeller(request, null);
    }

    public CompletableFuture<MarketSDKHttpResponse<SellerObject>> createSeller(
            CreatePartyDto request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/sellers");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(BodyProperties.merge(
                            request, requestOptions != null ? requestOptions.getBodyProperties() : null)),
                    MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> future = new CompletableFuture<>();
        Call okhttpCall = client.newCall(okhttpRequest);
        okhttpCall.enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new MarketSDKHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SellerObject.class), response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MarketSDKApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
            }
        });
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                okhttpCall.cancel();
            }
        });
        return future;
    }

    public CompletableFuture<MarketSDKHttpResponse<SellerObject>> getSeller(String id) {
        return getSeller(id, GetSellerRequest.builder().build());
    }

    public CompletableFuture<MarketSDKHttpResponse<SellerObject>> getSeller(String id, RequestOptions requestOptions) {
        return getSeller(id, GetSellerRequest.builder().build(), requestOptions);
    }

    public CompletableFuture<MarketSDKHttpResponse<SellerObject>> getSeller(String id, GetSellerRequest request) {
        return getSeller(id, request, null);
    }

    public CompletableFuture<MarketSDKHttpResponse<SellerObject>> getSeller(
            String id, GetSellerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/sellers")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> future = new CompletableFuture<>();
        Call okhttpCall = client.newCall(okhttpRequest);
        okhttpCall.enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new MarketSDKHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SellerObject.class), response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MarketSDKApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
            }
        });
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                okhttpCall.cancel();
            }
        });
        return future;
    }

    /**
     * Removes the name, external id, metadata, storefront, and review text, and takes the listings down. Orders and reputation stay, without personal data.
     */
    public CompletableFuture<MarketSDKHttpResponse<SellerObject>> eraseSeller(String id) {
        return eraseSeller(id, EraseSellerRequest.builder().build());
    }

    /**
     * Removes the name, external id, metadata, storefront, and review text, and takes the listings down. Orders and reputation stay, without personal data.
     */
    public CompletableFuture<MarketSDKHttpResponse<SellerObject>> eraseSeller(
            String id, RequestOptions requestOptions) {
        return eraseSeller(id, EraseSellerRequest.builder().build(), requestOptions);
    }

    /**
     * Removes the name, external id, metadata, storefront, and review text, and takes the listings down. Orders and reputation stay, without personal data.
     */
    public CompletableFuture<MarketSDKHttpResponse<SellerObject>> eraseSeller(String id, EraseSellerRequest request) {
        return eraseSeller(id, request, null);
    }

    /**
     * Removes the name, external id, metadata, storefront, and review text, and takes the listings down. Orders and reputation stay, without personal data.
     */
    public CompletableFuture<MarketSDKHttpResponse<SellerObject>> eraseSeller(
            String id, EraseSellerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/sellers")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method(
                        "DELETE",
                        BodyProperties.toRequestBody(
                                requestOptions != null ? requestOptions.getBodyProperties() : null, null))
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> future = new CompletableFuture<>();
        Call okhttpCall = client.newCall(okhttpRequest);
        okhttpCall.enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new MarketSDKHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SellerObject.class), response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MarketSDKApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
            }
        });
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                okhttpCall.cancel();
            }
        });
        return future;
    }

    public CompletableFuture<MarketSDKHttpResponse<SellerObject>> updateSeller(String id, UpdateSellerRequest request) {
        return updateSeller(id, request, null);
    }

    public CompletableFuture<MarketSDKHttpResponse<SellerObject>> updateSeller(
            String id, UpdateSellerRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/sellers")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(BodyProperties.merge(
                            request.getBody(), requestOptions != null ? requestOptions.getBodyProperties() : null)),
                    MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<MarketSDKHttpResponse<SellerObject>> future = new CompletableFuture<>();
        Call okhttpCall = client.newCall(okhttpRequest);
        okhttpCall.enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new MarketSDKHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SellerObject.class), response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MarketSDKApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
            }
        });
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                okhttpCall.cancel();
            }
        });
        return future;
    }

    public CompletableFuture<MarketSDKHttpResponse<StorefrontObject>> putStorefront(String id, StorefrontDto request) {
        return putStorefront(id, request, null);
    }

    public CompletableFuture<MarketSDKHttpResponse<StorefrontObject>> putStorefront(
            String id, StorefrontDto request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/sellers")
                .addPathSegment(id)
                .addPathSegments("storefront");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(BodyProperties.merge(
                            request, requestOptions != null ? requestOptions.getBodyProperties() : null)),
                    MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<MarketSDKHttpResponse<StorefrontObject>> future = new CompletableFuture<>();
        Call okhttpCall = client.newCall(okhttpRequest);
        okhttpCall.enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new MarketSDKHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, StorefrontObject.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MarketSDKApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
            }
        });
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                okhttpCall.cancel();
            }
        });
        return future;
    }

    /**
     * The first link creates the seller's connected account on your Stripe account: Express, with Stripe collecting what the law requires, your platform paying Stripe's fees and bearing losses, and only transfers requested. Send the seller to the link; their payouts status follows as Stripe reports it.
     */
    public CompletableFuture<MarketSDKHttpResponse<OnboardingLinkObject>> createOnboardingLink(
            String id, OnboardingLinkDto request) {
        return createOnboardingLink(id, request, null);
    }

    /**
     * The first link creates the seller's connected account on your Stripe account: Express, with Stripe collecting what the law requires, your platform paying Stripe's fees and bearing losses, and only transfers requested. Send the seller to the link; their payouts status follows as Stripe reports it.
     */
    public CompletableFuture<MarketSDKHttpResponse<OnboardingLinkObject>> createOnboardingLink(
            String id, OnboardingLinkDto request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/sellers")
                .addPathSegment(id)
                .addPathSegments("onboarding_links");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(BodyProperties.merge(
                            request, requestOptions != null ? requestOptions.getBodyProperties() : null)),
                    MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MarketSDKException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<MarketSDKHttpResponse<OnboardingLinkObject>> future = new CompletableFuture<>();
        Call okhttpCall = client.newCall(okhttpRequest);
        okhttpCall.enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new MarketSDKHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, OnboardingLinkObject.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MarketSDKApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
            }
        });
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                okhttpCall.cancel();
            }
        });
        return future;
    }

    /**
     * Callable with a publishable key. Shows only what a buyer may see.
     */
    public CompletableFuture<MarketSDKHttpResponse<SellerProfileObject>> getSellerProfile(String id) {
        return getSellerProfile(id, GetSellerProfileRequest.builder().build());
    }

    /**
     * Callable with a publishable key. Shows only what a buyer may see.
     */
    public CompletableFuture<MarketSDKHttpResponse<SellerProfileObject>> getSellerProfile(
            String id, RequestOptions requestOptions) {
        return getSellerProfile(id, GetSellerProfileRequest.builder().build(), requestOptions);
    }

    /**
     * Callable with a publishable key. Shows only what a buyer may see.
     */
    public CompletableFuture<MarketSDKHttpResponse<SellerProfileObject>> getSellerProfile(
            String id, GetSellerProfileRequest request) {
        return getSellerProfile(id, request, null);
    }

    /**
     * Callable with a publishable key. Shows only what a buyer may see.
     */
    public CompletableFuture<MarketSDKHttpResponse<SellerProfileObject>> getSellerProfile(
            String id, GetSellerProfileRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/sellers")
                .addPathSegment(id)
                .addPathSegments("profile");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<MarketSDKHttpResponse<SellerProfileObject>> future = new CompletableFuture<>();
        Call okhttpCall = client.newCall(okhttpRequest);
        okhttpCall.enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new MarketSDKHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SellerProfileObject.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorEnvelope.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MarketSDKApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new MarketSDKException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MarketSDKException("Network error executing HTTP request", e));
            }
        });
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                okhttpCall.cancel();
            }
        });
        return future;
    }
}
