/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.resources.reputation;

import com.marketsdk.core.ClientOptions;
import com.marketsdk.core.MarketSDKHttpResponse;
import com.marketsdk.core.RequestOptions;
import com.marketsdk.resources.reputation.requests.ListReputationEventsRequest;
import com.marketsdk.resources.reputation.requests.VoidDto;
import com.marketsdk.types.ReputationEventList;
import com.marketsdk.types.ReputationEventObject;
import java.util.concurrent.CompletableFuture;

public class AsyncReputationClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawReputationClient rawClient;

    public AsyncReputationClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawReputationClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawReputationClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<ReputationEventList> listReputationEvents(ListReputationEventsRequest request) {
        CompletableFuture<MarketSDKHttpResponse<ReputationEventList>> rawFuture =
                this.rawClient.listReputationEvents(request);
        CompletableFuture<ReputationEventList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    public CompletableFuture<ReputationEventList> listReputationEvents(
            ListReputationEventsRequest request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<ReputationEventList>> rawFuture =
                this.rawClient.listReputationEvents(request, requestOptions);
        CompletableFuture<ReputationEventList> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * For the customer's team. Writes a second event pointing at the first. The voided event stops counting. Nothing is deleted.
     */
    public CompletableFuture<ReputationEventObject> voidReputationEvent(String id, VoidDto request) {
        CompletableFuture<MarketSDKHttpResponse<ReputationEventObject>> rawFuture =
                this.rawClient.voidReputationEvent(id, request);
        CompletableFuture<ReputationEventObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }

    /**
     * For the customer's team. Writes a second event pointing at the first. The voided event stops counting. Nothing is deleted.
     */
    public CompletableFuture<ReputationEventObject> voidReputationEvent(
            String id, VoidDto request, RequestOptions requestOptions) {
        CompletableFuture<MarketSDKHttpResponse<ReputationEventObject>> rawFuture =
                this.rawClient.voidReputationEvent(id, request, requestOptions);
        CompletableFuture<ReputationEventObject> future = rawFuture.thenApply(response -> response.body());
        future.whenComplete((result_, throwable_) -> {
            if (future.isCancelled()) {
                rawFuture.cancel(true);
            }
        });
        return future;
    }
}
