/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.marketsdk.resources.webhooks.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.marketsdk.core.ObjectMappers;
import com.marketsdk.resources.webhooks.types.UpdateWebhookEndpointDtoEnabledEventsItem;
import com.marketsdk.resources.webhooks.types.UpdateWebhookEndpointDtoStatus;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateWebhookEndpointDto.Builder.class)
public final class UpdateWebhookEndpointDto {
    private final Optional<String> url;

    private final Optional<List<UpdateWebhookEndpointDtoEnabledEventsItem>> enabledEvents;

    private final Optional<String> description;

    private final Optional<UpdateWebhookEndpointDtoStatus> status;

    private final Optional<Map<String, String>> metadata;

    private final Map<String, Object> additionalProperties;

    private UpdateWebhookEndpointDto(
            Optional<String> url,
            Optional<List<UpdateWebhookEndpointDtoEnabledEventsItem>> enabledEvents,
            Optional<String> description,
            Optional<UpdateWebhookEndpointDtoStatus> status,
            Optional<Map<String, String>> metadata,
            Map<String, Object> additionalProperties) {
        this.url = url;
        this.enabledEvents = enabledEvents;
        this.description = description;
        this.status = status;
        this.metadata = metadata;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("url")
    public Optional<String> getUrl() {
        return url;
    }

    @JsonProperty("enabled_events")
    public Optional<List<UpdateWebhookEndpointDtoEnabledEventsItem>> getEnabledEvents() {
        return enabledEvents;
    }

    @JsonProperty("description")
    public Optional<String> getDescription() {
        return description;
    }

    /**
     * @return Turn the endpoint off, or back on after it was turned off.
     */
    @JsonProperty("status")
    public Optional<UpdateWebhookEndpointDtoStatus> getStatus() {
        return status;
    }

    @JsonProperty("metadata")
    public Optional<Map<String, String>> getMetadata() {
        return metadata;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateWebhookEndpointDto && equalTo((UpdateWebhookEndpointDto) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateWebhookEndpointDto other) {
        return url.equals(other.url)
                && enabledEvents.equals(other.enabledEvents)
                && description.equals(other.description)
                && status.equals(other.status)
                && metadata.equals(other.metadata);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.url, this.enabledEvents, this.description, this.status, this.metadata);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> url = Optional.empty();

        private Optional<List<UpdateWebhookEndpointDtoEnabledEventsItem>> enabledEvents = Optional.empty();

        private Optional<String> description = Optional.empty();

        private Optional<UpdateWebhookEndpointDtoStatus> status = Optional.empty();

        private Optional<Map<String, String>> metadata = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateWebhookEndpointDto other) {
            url(other.getUrl());
            enabledEvents(other.getEnabledEvents());
            description(other.getDescription());
            status(other.getStatus());
            metadata(other.getMetadata());
            return this;
        }

        @JsonSetter(value = "url", nulls = Nulls.SKIP)
        public Builder url(Optional<String> url) {
            this.url = url;
            return this;
        }

        public Builder url(String url) {
            this.url = Optional.ofNullable(url);
            return this;
        }

        @JsonSetter(value = "enabled_events", nulls = Nulls.SKIP)
        public Builder enabledEvents(Optional<List<UpdateWebhookEndpointDtoEnabledEventsItem>> enabledEvents) {
            this.enabledEvents = enabledEvents;
            return this;
        }

        public Builder enabledEvents(List<UpdateWebhookEndpointDtoEnabledEventsItem> enabledEvents) {
            this.enabledEvents = Optional.ofNullable(enabledEvents);
            return this;
        }

        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public Builder description(Optional<String> description) {
            this.description = description;
            return this;
        }

        public Builder description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>Turn the endpoint off, or back on after it was turned off.</p>
         */
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<UpdateWebhookEndpointDtoStatus> status) {
            this.status = status;
            return this;
        }

        public Builder status(UpdateWebhookEndpointDtoStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public Builder metadata(Optional<Map<String, String>> metadata) {
            this.metadata = metadata;
            return this;
        }

        public Builder metadata(Map<String, String> metadata) {
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        public UpdateWebhookEndpointDto build() {
            return new UpdateWebhookEndpointDto(
                    url, enabledEvents, description, status, metadata, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
